-- ============================================================================
-- SEGUIMIENTO · Dirección de Operación
-- Órdenes, renovaciones, certificados y pendientes, por subdirección.
--
-- Módulo de acceso restringido: sólo entran las cuentas registradas en
-- public.seguimiento_acceso. La regla vive aquí, en la base (RLS), y no sólo en
-- la página: aunque alguien abra #seguimiento, sin estar en la lista no lee ni
-- escribe nada.
--
--   admin  → todo, y además administra quién entra
--   editor → crea, edita y comenta
--   lector → consulta y comenta
--
-- Las evidencias (PDF, JPG, PNG) van a un bucket PRIVADO y se abren con
-- enlaces firmados que vencen.
--
-- Es idempotente: se puede correr de nuevo. No toca tablas de otros módulos.
-- Supabase → SQL Editor → pegar → Run.
-- ============================================================================

BEGIN;

-- ── 1. Quién entra ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.seguimiento_acceso (
  email         text PRIMARY KEY,                 -- siempre en minúsculas
  nombre        text,
  rol           text NOT NULL DEFAULT 'editor',
  agregado_por  text,
  creado_en     timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT seguimiento_acceso_rol_chk CHECK (rol IN ('admin', 'editor', 'lector')),
  CONSTRAINT seguimiento_acceso_email_chk CHECK (email = lower(btrim(email)) AND email LIKE '%@%')
);

COMMENT ON TABLE public.seguimiento_acceso IS
  'Cuentas que pueden entrar al módulo Seguimiento y con qué rol.';

-- El rol de quien está conectado, o NULL si no tiene acceso. SECURITY DEFINER
-- para que las políticas puedan consultarla sin abrir la tabla a todos.
CREATE OR REPLACE FUNCTION public.seguimiento_mi_rol()
RETURNS text
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT a.rol
  FROM public.seguimiento_acceso a
  WHERE a.email = lower(coalesce(auth.jwt() ->> 'email', ''))
  LIMIT 1;
$$;

REVOKE ALL ON FUNCTION public.seguimiento_mi_rol() FROM public;
GRANT EXECUTE ON FUNCTION public.seguimiento_mi_rol() TO authenticated;

CREATE OR REPLACE FUNCTION public.seguimiento_puede_ver()
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$ SELECT public.seguimiento_mi_rol() IS NOT NULL; $$;

CREATE OR REPLACE FUNCTION public.seguimiento_puede_editar()
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$ SELECT coalesce(public.seguimiento_mi_rol() IN ('admin', 'editor'), false); $$;

CREATE OR REPLACE FUNCTION public.seguimiento_es_admin()
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$ SELECT coalesce(public.seguimiento_mi_rol() = 'admin', false); $$;

REVOKE ALL ON FUNCTION public.seguimiento_puede_ver() FROM public;
REVOKE ALL ON FUNCTION public.seguimiento_puede_editar() FROM public;
REVOKE ALL ON FUNCTION public.seguimiento_es_admin() FROM public;
GRANT EXECUTE ON FUNCTION public.seguimiento_puede_ver() TO authenticated;
GRANT EXECUTE ON FUNCTION public.seguimiento_puede_editar() TO authenticated;
GRANT EXECUTE ON FUNCTION public.seguimiento_es_admin() TO authenticated;

-- ── 2. Tareas ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.seguimiento_tareas (
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  folio                bigint GENERATED BY DEFAULT AS IDENTITY,
  titulo               text NOT NULL,
  descripcion          text,
  tipo                 text NOT NULL DEFAULT 'orden',
  subdireccion         text NOT NULL,
  gerencia             text,
  estatus              text NOT NULL DEFAULT 'pendiente',
  prioridad            text NOT NULL DEFAULT 'normal',
  responsable          text,
  responsable_num      text,           -- No. Empleado en agenda_2026, si se eligió del directorio
  responsable_tel      text,           -- para el recordatorio por WhatsApp
  fecha_inicio         date,
  fecha_limite         date,
  completada_en        timestamptz,
  recurrencia          text NOT NULL DEFAULT 'ninguna',
  recurrencia_meses    integer,        -- sólo con recurrencia 'personalizada': cada cuántos meses (18, 36…)
  aviso_dias           integer NOT NULL DEFAULT 7,
  referencia           text,           -- oficio, minuta o documento que la origina
  etiquetas            text[] NOT NULL DEFAULT '{}',
  checklist            jsonb NOT NULL DEFAULT '[]'::jsonb,   -- [{id, texto, hecho}]
  evidencias           jsonb NOT NULL DEFAULT '[]'::jsonb,   -- [{path, nombre, tipo, tam, subido_por, subido_en}]
  tarea_origen         uuid,           -- primera de la cadena, en las recurrentes
  siguiente_id         uuid,           -- la ocurrencia que se programó al completarla
  ultimo_recordatorio  timestamptz,
  creado_por           text,
  creado_por_email     text,
  actualizado_por      text,
  creado_en            timestamptz NOT NULL DEFAULT now(),
  actualizado_en       timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT seguimiento_tareas_titulo_chk     CHECK (length(btrim(titulo)) BETWEEN 1 AND 300),
  CONSTRAINT seguimiento_tareas_tipo_chk       CHECK (tipo IN ('orden', 'renovacion', 'certificado', 'compromiso', 'tarea')),
  CONSTRAINT seguimiento_tareas_subdir_chk     CHECK (subdireccion IN ('DO', 'SSO', 'SSA', 'SSC', 'SI', 'SGE')),
  CONSTRAINT seguimiento_tareas_estatus_chk    CHECK (estatus IN ('pendiente', 'en_proceso', 'en_revision', 'detenida', 'completada', 'cancelada')),
  CONSTRAINT seguimiento_tareas_prioridad_chk  CHECK (prioridad IN ('urgente', 'alta', 'normal', 'baja')),
  CONSTRAINT seguimiento_tareas_recurr_chk     CHECK (recurrencia IN ('ninguna', 'mensual', 'bimestral', 'trimestral', 'semestral', 'anual', 'bienal', 'personalizada')),
  CONSTRAINT seguimiento_tareas_recurr_meses_chk CHECK (recurrencia <> 'personalizada' OR recurrencia_meses BETWEEN 1 AND 240),
  CONSTRAINT seguimiento_tareas_aviso_chk      CHECK (aviso_dias BETWEEN 0 AND 365),
  CONSTRAINT seguimiento_tareas_fechas_chk     CHECK (fecha_inicio IS NULL OR fecha_limite IS NULL OR fecha_limite >= fecha_inicio),
  CONSTRAINT seguimiento_tareas_checklist_chk  CHECK (jsonb_typeof(checklist) = 'array'),
  CONSTRAINT seguimiento_tareas_evidencias_chk CHECK (jsonb_typeof(evidencias) = 'array')
);

-- Para quien ya tenía la tabla de la primera versión: repetir con un tiempo
-- personalizado (cada 18 meses, cada 3 años…).
ALTER TABLE public.seguimiento_tareas ADD COLUMN IF NOT EXISTS recurrencia_meses integer;
ALTER TABLE public.seguimiento_tareas DROP CONSTRAINT IF EXISTS seguimiento_tareas_recurr_chk;
ALTER TABLE public.seguimiento_tareas ADD CONSTRAINT seguimiento_tareas_recurr_chk
  CHECK (recurrencia IN ('ninguna', 'mensual', 'bimestral', 'trimestral', 'semestral', 'anual', 'bienal', 'personalizada'));
ALTER TABLE public.seguimiento_tareas DROP CONSTRAINT IF EXISTS seguimiento_tareas_recurr_meses_chk;
ALTER TABLE public.seguimiento_tareas ADD CONSTRAINT seguimiento_tareas_recurr_meses_chk
  CHECK (recurrencia <> 'personalizada' OR recurrencia_meses BETWEEN 1 AND 240);

CREATE UNIQUE INDEX IF NOT EXISTS uq_seguimiento_tareas_folio ON public.seguimiento_tareas (folio);
CREATE INDEX IF NOT EXISTS idx_seguimiento_tareas_limite  ON public.seguimiento_tareas (fecha_limite);
CREATE INDEX IF NOT EXISTS idx_seguimiento_tareas_subdir  ON public.seguimiento_tareas (subdireccion, estatus);

COMMENT ON TABLE public.seguimiento_tareas IS
  'Seguimiento de la Dirección de Operación: órdenes, renovaciones, certificados y pendientes por subdirección.';

CREATE OR REPLACE FUNCTION public._touch_seguimiento()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.actualizado_en := now();
  -- La fecha de cierre la pone la base: así no depende del reloj de cada equipo.
  IF NEW.estatus = 'completada' AND (TG_OP = 'INSERT' OR OLD.estatus IS DISTINCT FROM 'completada') THEN
    NEW.completada_en := coalesce(NEW.completada_en, now());
  ELSIF NEW.estatus <> 'completada' THEN
    NEW.completada_en := NULL;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_touch_seguimiento ON public.seguimiento_tareas;
CREATE TRIGGER trg_touch_seguimiento
BEFORE INSERT OR UPDATE ON public.seguimiento_tareas
FOR EACH ROW EXECUTE FUNCTION public._touch_seguimiento();

-- ── 3. Comentarios y bitácora ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.seguimiento_comentarios (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tarea_id     uuid NOT NULL REFERENCES public.seguimiento_tareas(id) ON DELETE CASCADE,
  autor        text,
  autor_email  text DEFAULT lower(auth.jwt() ->> 'email'),
  texto        text NOT NULL,
  creado_en    timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT seguimiento_comentarios_texto_chk CHECK (length(btrim(texto)) BETWEEN 1 AND 4000)
);
CREATE INDEX IF NOT EXISTS idx_seguimiento_comentarios_tarea ON public.seguimiento_comentarios (tarea_id, creado_en);

CREATE TABLE IF NOT EXISTS public.seguimiento_actividad (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tarea_id     uuid NOT NULL REFERENCES public.seguimiento_tareas(id) ON DELETE CASCADE,
  autor        text,
  autor_email  text DEFAULT lower(auth.jwt() ->> 'email'),
  accion       text NOT NULL,
  detalle      jsonb NOT NULL DEFAULT '{}'::jsonb,
  creado_en    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_seguimiento_actividad_tarea ON public.seguimiento_actividad (tarea_id, creado_en DESC);

-- ── 4. Permisos ──────────────────────────────────────────────────────────────
ALTER TABLE public.seguimiento_acceso      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.seguimiento_tareas      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.seguimiento_comentarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.seguimiento_actividad   ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "seguimiento_acceso_select" ON public.seguimiento_acceso;
DROP POLICY IF EXISTS "seguimiento_acceso_write"  ON public.seguimiento_acceso;
-- Los que tienen acceso ven quién más lo tiene (para asignar y mencionar).
CREATE POLICY "seguimiento_acceso_select" ON public.seguimiento_acceso
  FOR SELECT TO authenticated USING (public.seguimiento_puede_ver());
CREATE POLICY "seguimiento_acceso_write" ON public.seguimiento_acceso
  FOR ALL TO authenticated
  USING (public.seguimiento_es_admin())
  WITH CHECK (public.seguimiento_es_admin());

DROP POLICY IF EXISTS "seguimiento_tareas_select" ON public.seguimiento_tareas;
DROP POLICY IF EXISTS "seguimiento_tareas_insert" ON public.seguimiento_tareas;
DROP POLICY IF EXISTS "seguimiento_tareas_update" ON public.seguimiento_tareas;
DROP POLICY IF EXISTS "seguimiento_tareas_delete" ON public.seguimiento_tareas;
CREATE POLICY "seguimiento_tareas_select" ON public.seguimiento_tareas
  FOR SELECT TO authenticated USING (public.seguimiento_puede_ver());
CREATE POLICY "seguimiento_tareas_insert" ON public.seguimiento_tareas
  FOR INSERT TO authenticated WITH CHECK (public.seguimiento_puede_editar());
CREATE POLICY "seguimiento_tareas_update" ON public.seguimiento_tareas
  FOR UPDATE TO authenticated
  USING (public.seguimiento_puede_editar())
  WITH CHECK (public.seguimiento_puede_editar());
-- Borrar sólo el admin: lo normal es completar o cancelar, que deja rastro.
CREATE POLICY "seguimiento_tareas_delete" ON public.seguimiento_tareas
  FOR DELETE TO authenticated USING (public.seguimiento_es_admin());

DROP POLICY IF EXISTS "seguimiento_comentarios_select" ON public.seguimiento_comentarios;
DROP POLICY IF EXISTS "seguimiento_comentarios_insert" ON public.seguimiento_comentarios;
DROP POLICY IF EXISTS "seguimiento_comentarios_delete" ON public.seguimiento_comentarios;
CREATE POLICY "seguimiento_comentarios_select" ON public.seguimiento_comentarios
  FOR SELECT TO authenticated USING (public.seguimiento_puede_ver());
CREATE POLICY "seguimiento_comentarios_insert" ON public.seguimiento_comentarios
  FOR INSERT TO authenticated
  WITH CHECK (public.seguimiento_puede_ver() AND autor_email = lower(auth.jwt() ->> 'email'));
-- Cada quien borra lo suyo; el admin, cualquiera.
CREATE POLICY "seguimiento_comentarios_delete" ON public.seguimiento_comentarios
  FOR DELETE TO authenticated
  USING (public.seguimiento_es_admin() OR autor_email = lower(auth.jwt() ->> 'email'));

DROP POLICY IF EXISTS "seguimiento_actividad_select" ON public.seguimiento_actividad;
DROP POLICY IF EXISTS "seguimiento_actividad_insert" ON public.seguimiento_actividad;
CREATE POLICY "seguimiento_actividad_select" ON public.seguimiento_actividad
  FOR SELECT TO authenticated USING (public.seguimiento_puede_ver());
CREATE POLICY "seguimiento_actividad_insert" ON public.seguimiento_actividad
  FOR INSERT TO authenticated WITH CHECK (public.seguimiento_puede_ver());

GRANT SELECT, INSERT, UPDATE, DELETE ON public.seguimiento_acceso      TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.seguimiento_tareas      TO authenticated;
GRANT SELECT, INSERT, DELETE         ON public.seguimiento_comentarios TO authenticated;
GRANT SELECT, INSERT                 ON public.seguimiento_actividad   TO authenticated;

-- ── 5. Evidencias: bucket privado ────────────────────────────────────────────
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'seguimiento-evidencias',
  'seguimiento-evidencias',
  false,
  10485760,  -- 10 MB
  ARRAY['application/pdf', 'image/jpeg', 'image/png']
)
ON CONFLICT (id) DO UPDATE SET
  public             = EXCLUDED.public,
  file_size_limit    = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

DROP POLICY IF EXISTS "seguimiento_evidencias_select" ON storage.objects;
DROP POLICY IF EXISTS "seguimiento_evidencias_insert" ON storage.objects;
DROP POLICY IF EXISTS "seguimiento_evidencias_delete" ON storage.objects;

-- Ruta que genera la aplicación: <id de la tarea>/<aleatorio>.<pdf|jpg|png>
CREATE POLICY "seguimiento_evidencias_select" ON storage.objects
  FOR SELECT TO authenticated
  USING (bucket_id = 'seguimiento-evidencias' AND public.seguimiento_puede_ver());

CREATE POLICY "seguimiento_evidencias_insert" ON storage.objects
  FOR INSERT TO authenticated
  WITH CHECK (
    bucket_id = 'seguimiento-evidencias'
    AND public.seguimiento_puede_editar()
    AND name ~ '^[0-9a-f-]{36}/[A-Za-z0-9_-]{6,64}\.(pdf|jpg|png)$'
  );

CREATE POLICY "seguimiento_evidencias_delete" ON storage.objects
  FOR DELETE TO authenticated
  USING (bucket_id = 'seguimiento-evidencias' AND public.seguimiento_puede_editar());

-- ── 6. Tiempo real: que Gonzalo vea al momento lo que otro actualiza ──────────
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    IF NOT EXISTS (SELECT 1 FROM pg_publication_tables
                   WHERE pubname = 'supabase_realtime' AND tablename = 'seguimiento_tareas') THEN
      ALTER PUBLICATION supabase_realtime ADD TABLE public.seguimiento_tareas;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_publication_tables
                   WHERE pubname = 'supabase_realtime' AND tablename = 'seguimiento_comentarios') THEN
      ALTER PUBLICATION supabase_realtime ADD TABLE public.seguimiento_comentarios;
    END IF;
  END IF;
END $$;

-- ── 7. Primeras cuentas ──────────────────────────────────────────────────────
-- Isaac administra el acceso. Las demás cuentas se agregan desde el propio
-- módulo (botón "Acceso") o con una línea como la de abajo.
INSERT INTO public.seguimiento_acceso (email, nombre, rol, agregado_por)
VALUES ('isaac.lopez@aifa.operaciones', 'Isaac Azhael López Cancino', 'admin', 'instalación')
ON CONFLICT (email) DO NOTHING;

-- Jefe Gonzalo (Director de Operación): poner aquí su usuario de inicio de sesión.
-- INSERT INTO public.seguimiento_acceso (email, nombre, rol, agregado_por)
-- VALUES ('<usuario>@aifa.operaciones', 'Gonzalo Sandoval González', 'admin', 'instalación')
-- ON CONFLICT (email) DO NOTHING;

COMMIT;

-- Que la API vea las columnas nuevas sin esperar.
NOTIFY pgrst, 'reload schema';

-- Verificación:
-- SELECT * FROM public.seguimiento_acceso;
-- SELECT policyname, tablename, cmd FROM pg_policies WHERE tablename LIKE 'seguimiento_%';
-- SELECT id, public, file_size_limit FROM storage.buckets WHERE id = 'seguimiento-evidencias';
