BEGIN;

-- [VACANTE 1] Plaza 34
DO $$
BEGIN
  UPDATE public.agenda_2026
  SET
      "Nombre" = 'VACANTE',
      "Fecha de alta" = 'VACANTE',
      "Sueldo_Bruto" = NULL,
      "Plaza" = '34',
      "Nivel" = 'K21',
      "Dir. Orgánica" = 'Subdirección General Operativa',
      "Subdir. Orgánica" = 'Subdirección General Operativa',
      "Gerencia Orgánica" = '----',
      "Coordinación Orgánica" = '----',
      "Puesto" = 'Subdirector General Operativo',
      "Personal Comisionado" = 'NO',
      "Dirección Comisionado" = 'NO',
      "Subdirección Comisionado" = 'NO',
      "Gerencia Comisionado" = 'NO',
      "Coordinación Comisionado" = 'NO',
      "Comentarios" = NULL,
      "Amonestaciones" = NULL,
      "Rúbrica" = NULL,
      "Anexo ""A"" Turno especial" = NULL,
      "Anexo ""A"" Fecha de activación" = NULL,
      "Anexo ""B"" Riesgos" = NULL,
      "Anexo ""B"" Fecha de activación" = NULL,
      "Antigüedad" = NULL,
      "Días de vacaciones disponibles" = NULL,
      "Fecha de nacimiento" = NULL,
      "Sexo" = NULL,
      "CURP" = NULL,
      "RFC" = NULL,
      "NSS" = NULL,
      "Vigencia de INE" = NULL,
      "Fotografia de INE" = NULL,
      "No. telefónico" = NULL,
      "Domicilio (calle, colonia, municipio, estado y código postal)" = NULL,
      "Persona Civil o Militar" = NULL,
      "Grado Militar" = NULL,
      "Personal en activo o retirado" = NULL,
      "Matrícula Militar" = NULL,
      "Estado civil" = NULL,
      "Dependientes (hijos)" = NULL,
      "RUSP" = NULL,
      "Tipo de sangre" = NULL,
      "Alérgico a algún medicamento Si ó No (Especificar)" = NULL,
      "Alérgico a algún alimento. Si ó No (Especificar)" = NULL,
      "Contacto de emergencia 1 Nombre completo" = NULL,
      "Parentesco 1" = NULL,
      "Teléfono de emergencia 1" = NULL,
      "Contacto de emergencia 2 Nombre completo" = NULL,
      "Parentesco 2" = NULL,
      "Teléfono de emergencia 2" = NULL,
      "Nivel de estudio" = NULL,
      "Nombre de la Licenciatura y/o Maestria" = NULL,
      "Grado Acad?mico" = NULL,
      "Estatus" = 'Baja',
      "Nombre de la Universidad" = NULL,
      "Año de Titulación" = NULL,
      "No. Cédula Profesional" = NULL,
      "Fotografía (vest. Formal)" = NULL,
      "Correo Personal" = NULL,
      "Correo Institucional" = NULL,
      "Extensión" = NULL,
      "Vigencia de la TIA" = NULL,
      "Fotografía de la TIA" = NULL,
      "Licencia de Manejo" = NULL,
      "Tipo de licencia" = NULL,
      "Licencia Vigencia" = NULL,
      "Fotografia de licencia" = NULL,
      "Edad" = NULL,
      "Cumpleaños" = NULL,
      "Doc. Para ingreso" = NULL
  WHERE ("No. Empleado" IS NULL OR btrim("No. Empleado"::text) = '')
    AND "Plaza"::text = '34';

  IF NOT FOUND THEN
    INSERT INTO public.agenda_2026 ("No. Empleado", "Nombre", "Fecha de alta", "Sueldo_Bruto", "Plaza", "Nivel", "Dir. Orgánica", "Subdir. Orgánica", "Gerencia Orgánica", "Coordinación Orgánica", "Puesto", "Personal Comisionado", "Dirección Comisionado", "Subdirección Comisionado", "Gerencia Comisionado", "Coordinación Comisionado", "Comentarios", "Amonestaciones", "Rúbrica", "Anexo ""A"" Turno especial", "Anexo ""A"" Fecha de activación", "Anexo ""B"" Riesgos", "Anexo ""B"" Fecha de activación", "Antigüedad", "Días de vacaciones disponibles", "Fecha de nacimiento", "Sexo", "CURP", "RFC", "NSS", "Vigencia de INE", "Fotografia de INE", "No. telefónico", "Domicilio (calle, colonia, municipio, estado y código postal)", "Persona Civil o Militar", "Grado Militar", "Personal en activo o retirado", "Matrícula Militar", "Estado civil", "Dependientes (hijos)", "RUSP", "Tipo de sangre", "Alérgico a algún medicamento Si ó No (Especificar)", "Alérgico a algún alimento. Si ó No (Especificar)", "Contacto de emergencia 1 Nombre completo", "Parentesco 1", "Teléfono de emergencia 1", "Contacto de emergencia 2 Nombre completo", "Parentesco 2", "Teléfono de emergencia 2", "Nivel de estudio", "Nombre de la Licenciatura y/o Maestria", "Grado Acad?mico", "Estatus", "Nombre de la Universidad", "Año de Titulación", "No. Cédula Profesional", "Fotografía (vest. Formal)", "Correo Personal", "Correo Institucional", "Extensión", "Vigencia de la TIA", "Fotografía de la TIA", "Licencia de Manejo", "Tipo de licencia", "Licencia Vigencia", "Fotografia de licencia", "Edad", "Cumpleaños", "Doc. Para ingreso")
    VALUES (NULL, 'VACANTE', 'VACANTE', NULL, '34', 'K21', 'Subdirección General Operativa', 'Subdirección General Operativa', '----', '----', 'Subdirector General Operativo', 'NO', 'NO', 'NO', 'NO', 'NO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
  END IF;
END $$;

-- [VACANTE 2] Plaza 211
DO $$
BEGIN
  UPDATE public.agenda_2026
  SET
      "Nombre" = 'VACANTE',
      "Fecha de alta" = 'VACANTE',
      "Sueldo_Bruto" = '$60,034.00',
      "Plaza" = '211',
      "Nivel" = 'N32',
      "Dir. Orgánica" = 'Dirección de Operación',
      "Subdir. Orgánica" = 'Subdirección de Seguridad de la Aviación',
      "Gerencia Orgánica" = 'Gerencia de Seguridad',
      "Coordinación Orgánica" = '----',
      "Puesto" = 'Gerente de Seguridad',
      "Personal Comisionado" = 'NO',
      "Dirección Comisionado" = 'NO',
      "Subdirección Comisionado" = 'NO',
      "Gerencia Comisionado" = 'NO',
      "Coordinación Comisionado" = 'NO',
      "Comentarios" = NULL,
      "Amonestaciones" = NULL,
      "Rúbrica" = NULL,
      "Anexo ""A"" Turno especial" = NULL,
      "Anexo ""A"" Fecha de activación" = NULL,
      "Anexo ""B"" Riesgos" = NULL,
      "Anexo ""B"" Fecha de activación" = NULL,
      "Antigüedad" = NULL,
      "Días de vacaciones disponibles" = NULL,
      "Fecha de nacimiento" = NULL,
      "Sexo" = NULL,
      "CURP" = NULL,
      "RFC" = NULL,
      "NSS" = NULL,
      "Vigencia de INE" = NULL,
      "Fotografia de INE" = NULL,
      "No. telefónico" = NULL,
      "Domicilio (calle, colonia, municipio, estado y código postal)" = NULL,
      "Persona Civil o Militar" = NULL,
      "Grado Militar" = NULL,
      "Personal en activo o retirado" = NULL,
      "Matrícula Militar" = NULL,
      "Estado civil" = NULL,
      "Dependientes (hijos)" = NULL,
      "RUSP" = NULL,
      "Tipo de sangre" = NULL,
      "Alérgico a algún medicamento Si ó No (Especificar)" = NULL,
      "Alérgico a algún alimento. Si ó No (Especificar)" = NULL,
      "Contacto de emergencia 1 Nombre completo" = NULL,
      "Parentesco 1" = NULL,
      "Teléfono de emergencia 1" = NULL,
      "Contacto de emergencia 2 Nombre completo" = NULL,
      "Parentesco 2" = NULL,
      "Teléfono de emergencia 2" = NULL,
      "Nivel de estudio" = NULL,
      "Nombre de la Licenciatura y/o Maestria" = NULL,
      "Grado Acad?mico" = NULL,
      "Estatus" = 'Baja',
      "Nombre de la Universidad" = NULL,
      "Año de Titulación" = NULL,
      "No. Cédula Profesional" = NULL,
      "Fotografía (vest. Formal)" = NULL,
      "Correo Personal" = NULL,
      "Correo Institucional" = NULL,
      "Extensión" = NULL,
      "Vigencia de la TIA" = NULL,
      "Fotografía de la TIA" = NULL,
      "Licencia de Manejo" = NULL,
      "Tipo de licencia" = NULL,
      "Licencia Vigencia" = NULL,
      "Fotografia de licencia" = NULL,
      "Edad" = NULL,
      "Cumpleaños" = NULL,
      "Doc. Para ingreso" = NULL
  WHERE ("No. Empleado" IS NULL OR btrim("No. Empleado"::text) = '')
    AND "Plaza"::text = '211';

  IF NOT FOUND THEN
    INSERT INTO public.agenda_2026 ("No. Empleado", "Nombre", "Fecha de alta", "Sueldo_Bruto", "Plaza", "Nivel", "Dir. Orgánica", "Subdir. Orgánica", "Gerencia Orgánica", "Coordinación Orgánica", "Puesto", "Personal Comisionado", "Dirección Comisionado", "Subdirección Comisionado", "Gerencia Comisionado", "Coordinación Comisionado", "Comentarios", "Amonestaciones", "Rúbrica", "Anexo ""A"" Turno especial", "Anexo ""A"" Fecha de activación", "Anexo ""B"" Riesgos", "Anexo ""B"" Fecha de activación", "Antigüedad", "Días de vacaciones disponibles", "Fecha de nacimiento", "Sexo", "CURP", "RFC", "NSS", "Vigencia de INE", "Fotografia de INE", "No. telefónico", "Domicilio (calle, colonia, municipio, estado y código postal)", "Persona Civil o Militar", "Grado Militar", "Personal en activo o retirado", "Matrícula Militar", "Estado civil", "Dependientes (hijos)", "RUSP", "Tipo de sangre", "Alérgico a algún medicamento Si ó No (Especificar)", "Alérgico a algún alimento. Si ó No (Especificar)", "Contacto de emergencia 1 Nombre completo", "Parentesco 1", "Teléfono de emergencia 1", "Contacto de emergencia 2 Nombre completo", "Parentesco 2", "Teléfono de emergencia 2", "Nivel de estudio", "Nombre de la Licenciatura y/o Maestria", "Grado Acad?mico", "Estatus", "Nombre de la Universidad", "Año de Titulación", "No. Cédula Profesional", "Fotografía (vest. Formal)", "Correo Personal", "Correo Institucional", "Extensión", "Vigencia de la TIA", "Fotografía de la TIA", "Licencia de Manejo", "Tipo de licencia", "Licencia Vigencia", "Fotografia de licencia", "Edad", "Cumpleaños", "Doc. Para ingreso")
    VALUES (NULL, 'VACANTE', 'VACANTE', '$60,034.00', '211', 'N32', 'Dirección de Operación', 'Subdirección de Seguridad de la Aviación', 'Gerencia de Seguridad', '----', 'Gerente de Seguridad', 'NO', 'NO', 'NO', 'NO', 'NO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
  END IF;
END $$;

-- [VACANTE 3] Plaza 226
DO $$
BEGIN
  UPDATE public.agenda_2026
  SET
      "Nombre" = 'VACANTE',
      "Fecha de alta" = 'VACANTE',
      "Sueldo_Bruto" = '$45,280.81',
      "Plaza" = '226',
      "Nivel" = 'N6',
      "Dir. Orgánica" = 'Dirección de Operación',
      "Subdir. Orgánica" = 'Subdirección de Seguridad de la Aviación',
      "Gerencia Orgánica" = 'Gerencia de Seguridad',
      "Coordinación Orgánica" = 'Coordinación de Seguridad Aeroportuaria',
      "Puesto" = 'Profesional en Seguridad de la Aviación',
      "Personal Comisionado" = 'NO',
      "Dirección Comisionado" = 'NO',
      "Subdirección Comisionado" = 'NO',
      "Gerencia Comisionado" = 'NO',
      "Coordinación Comisionado" = 'NO',
      "Comentarios" = NULL,
      "Amonestaciones" = NULL,
      "Rúbrica" = NULL,
      "Anexo ""A"" Turno especial" = NULL,
      "Anexo ""A"" Fecha de activación" = NULL,
      "Anexo ""B"" Riesgos" = NULL,
      "Anexo ""B"" Fecha de activación" = NULL,
      "Antigüedad" = NULL,
      "Días de vacaciones disponibles" = NULL,
      "Fecha de nacimiento" = NULL,
      "Sexo" = NULL,
      "CURP" = NULL,
      "RFC" = NULL,
      "NSS" = NULL,
      "Vigencia de INE" = NULL,
      "Fotografia de INE" = NULL,
      "No. telefónico" = NULL,
      "Domicilio (calle, colonia, municipio, estado y código postal)" = NULL,
      "Persona Civil o Militar" = NULL,
      "Grado Militar" = NULL,
      "Personal en activo o retirado" = NULL,
      "Matrícula Militar" = NULL,
      "Estado civil" = NULL,
      "Dependientes (hijos)" = NULL,
      "RUSP" = NULL,
      "Tipo de sangre" = NULL,
      "Alérgico a algún medicamento Si ó No (Especificar)" = NULL,
      "Alérgico a algún alimento. Si ó No (Especificar)" = NULL,
      "Contacto de emergencia 1 Nombre completo" = NULL,
      "Parentesco 1" = NULL,
      "Teléfono de emergencia 1" = NULL,
      "Contacto de emergencia 2 Nombre completo" = NULL,
      "Parentesco 2" = NULL,
      "Teléfono de emergencia 2" = NULL,
      "Nivel de estudio" = NULL,
      "Nombre de la Licenciatura y/o Maestria" = NULL,
      "Grado Acad?mico" = NULL,
      "Estatus" = 'Baja',
      "Nombre de la Universidad" = NULL,
      "Año de Titulación" = NULL,
      "No. Cédula Profesional" = NULL,
      "Fotografía (vest. Formal)" = NULL,
      "Correo Personal" = NULL,
      "Correo Institucional" = NULL,
      "Extensión" = NULL,
      "Vigencia de la TIA" = NULL,
      "Fotografía de la TIA" = NULL,
      "Licencia de Manejo" = NULL,
      "Tipo de licencia" = NULL,
      "Licencia Vigencia" = NULL,
      "Fotografia de licencia" = NULL,
      "Edad" = NULL,
      "Cumpleaños" = NULL,
      "Doc. Para ingreso" = NULL
  WHERE ("No. Empleado" IS NULL OR btrim("No. Empleado"::text) = '')
    AND "Plaza"::text = '226';

  IF NOT FOUND THEN
    INSERT INTO public.agenda_2026 ("No. Empleado", "Nombre", "Fecha de alta", "Sueldo_Bruto", "Plaza", "Nivel", "Dir. Orgánica", "Subdir. Orgánica", "Gerencia Orgánica", "Coordinación Orgánica", "Puesto", "Personal Comisionado", "Dirección Comisionado", "Subdirección Comisionado", "Gerencia Comisionado", "Coordinación Comisionado", "Comentarios", "Amonestaciones", "Rúbrica", "Anexo ""A"" Turno especial", "Anexo ""A"" Fecha de activación", "Anexo ""B"" Riesgos", "Anexo ""B"" Fecha de activación", "Antigüedad", "Días de vacaciones disponibles", "Fecha de nacimiento", "Sexo", "CURP", "RFC", "NSS", "Vigencia de INE", "Fotografia de INE", "No. telefónico", "Domicilio (calle, colonia, municipio, estado y código postal)", "Persona Civil o Militar", "Grado Militar", "Personal en activo o retirado", "Matrícula Militar", "Estado civil", "Dependientes (hijos)", "RUSP", "Tipo de sangre", "Alérgico a algún medicamento Si ó No (Especificar)", "Alérgico a algún alimento. Si ó No (Especificar)", "Contacto de emergencia 1 Nombre completo", "Parentesco 1", "Teléfono de emergencia 1", "Contacto de emergencia 2 Nombre completo", "Parentesco 2", "Teléfono de emergencia 2", "Nivel de estudio", "Nombre de la Licenciatura y/o Maestria", "Grado Acad?mico", "Estatus", "Nombre de la Universidad", "Año de Titulación", "No. Cédula Profesional", "Fotografía (vest. Formal)", "Correo Personal", "Correo Institucional", "Extensión", "Vigencia de la TIA", "Fotografía de la TIA", "Licencia de Manejo", "Tipo de licencia", "Licencia Vigencia", "Fotografia de licencia", "Edad", "Cumpleaños", "Doc. Para ingreso")
    VALUES (NULL, 'VACANTE', 'VACANTE', '$45,280.81', '226', 'N6', 'Dirección de Operación', 'Subdirección de Seguridad de la Aviación', 'Gerencia de Seguridad', 'Coordinación de Seguridad Aeroportuaria', 'Profesional en Seguridad de la Aviación', 'NO', 'NO', 'NO', 'NO', 'NO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
  END IF;
END $$;

-- [VACANTE 4] Plaza 240
DO $$
BEGIN
  UPDATE public.agenda_2026
  SET
      "Nombre" = 'VACANTE',
      "Fecha de alta" = 'VACANTE',
      "Sueldo_Bruto" = '$36,065.96',
      "Plaza" = '240',
      "Nivel" = 'N5',
      "Dir. Orgánica" = 'Dirección de Operación',
      "Subdir. Orgánica" = 'Subdirección de Seguridad de la Aviación',
      "Gerencia Orgánica" = 'Gerencia de Seguridad',
      "Coordinación Orgánica" = 'Supervisor de Seguridad Aeroportuaria',
      "Puesto" = 'Supervisor de Seguridad Aeroportuaria',
      "Personal Comisionado" = 'NO',
      "Dirección Comisionado" = 'NO',
      "Subdirección Comisionado" = 'NO',
      "Gerencia Comisionado" = 'NO',
      "Coordinación Comisionado" = 'NO',
      "Comentarios" = NULL,
      "Amonestaciones" = NULL,
      "Rúbrica" = NULL,
      "Anexo ""A"" Turno especial" = NULL,
      "Anexo ""A"" Fecha de activación" = NULL,
      "Anexo ""B"" Riesgos" = NULL,
      "Anexo ""B"" Fecha de activación" = NULL,
      "Antigüedad" = NULL,
      "Días de vacaciones disponibles" = NULL,
      "Fecha de nacimiento" = NULL,
      "Sexo" = NULL,
      "CURP" = NULL,
      "RFC" = NULL,
      "NSS" = NULL,
      "Vigencia de INE" = NULL,
      "Fotografia de INE" = NULL,
      "No. telefónico" = NULL,
      "Domicilio (calle, colonia, municipio, estado y código postal)" = NULL,
      "Persona Civil o Militar" = NULL,
      "Grado Militar" = NULL,
      "Personal en activo o retirado" = NULL,
      "Matrícula Militar" = NULL,
      "Estado civil" = NULL,
      "Dependientes (hijos)" = NULL,
      "RUSP" = NULL,
      "Tipo de sangre" = NULL,
      "Alérgico a algún medicamento Si ó No (Especificar)" = NULL,
      "Alérgico a algún alimento. Si ó No (Especificar)" = NULL,
      "Contacto de emergencia 1 Nombre completo" = NULL,
      "Parentesco 1" = NULL,
      "Teléfono de emergencia 1" = NULL,
      "Contacto de emergencia 2 Nombre completo" = NULL,
      "Parentesco 2" = NULL,
      "Teléfono de emergencia 2" = NULL,
      "Nivel de estudio" = NULL,
      "Nombre de la Licenciatura y/o Maestria" = NULL,
      "Grado Acad?mico" = NULL,
      "Estatus" = 'Baja',
      "Nombre de la Universidad" = NULL,
      "Año de Titulación" = NULL,
      "No. Cédula Profesional" = NULL,
      "Fotografía (vest. Formal)" = NULL,
      "Correo Personal" = NULL,
      "Correo Institucional" = NULL,
      "Extensión" = NULL,
      "Vigencia de la TIA" = NULL,
      "Fotografía de la TIA" = NULL,
      "Licencia de Manejo" = NULL,
      "Tipo de licencia" = NULL,
      "Licencia Vigencia" = NULL,
      "Fotografia de licencia" = NULL,
      "Edad" = NULL,
      "Cumpleaños" = NULL,
      "Doc. Para ingreso" = NULL
  WHERE ("No. Empleado" IS NULL OR btrim("No. Empleado"::text) = '')
    AND "Plaza"::text = '240';

  IF NOT FOUND THEN
    INSERT INTO public.agenda_2026 ("No. Empleado", "Nombre", "Fecha de alta", "Sueldo_Bruto", "Plaza", "Nivel", "Dir. Orgánica", "Subdir. Orgánica", "Gerencia Orgánica", "Coordinación Orgánica", "Puesto", "Personal Comisionado", "Dirección Comisionado", "Subdirección Comisionado", "Gerencia Comisionado", "Coordinación Comisionado", "Comentarios", "Amonestaciones", "Rúbrica", "Anexo ""A"" Turno especial", "Anexo ""A"" Fecha de activación", "Anexo ""B"" Riesgos", "Anexo ""B"" Fecha de activación", "Antigüedad", "Días de vacaciones disponibles", "Fecha de nacimiento", "Sexo", "CURP", "RFC", "NSS", "Vigencia de INE", "Fotografia de INE", "No. telefónico", "Domicilio (calle, colonia, municipio, estado y código postal)", "Persona Civil o Militar", "Grado Militar", "Personal en activo o retirado", "Matrícula Militar", "Estado civil", "Dependientes (hijos)", "RUSP", "Tipo de sangre", "Alérgico a algún medicamento Si ó No (Especificar)", "Alérgico a algún alimento. Si ó No (Especificar)", "Contacto de emergencia 1 Nombre completo", "Parentesco 1", "Teléfono de emergencia 1", "Contacto de emergencia 2 Nombre completo", "Parentesco 2", "Teléfono de emergencia 2", "Nivel de estudio", "Nombre de la Licenciatura y/o Maestria", "Grado Acad?mico", "Estatus", "Nombre de la Universidad", "Año de Titulación", "No. Cédula Profesional", "Fotografía (vest. Formal)", "Correo Personal", "Correo Institucional", "Extensión", "Vigencia de la TIA", "Fotografía de la TIA", "Licencia de Manejo", "Tipo de licencia", "Licencia Vigencia", "Fotografia de licencia", "Edad", "Cumpleaños", "Doc. Para ingreso")
    VALUES (NULL, 'VACANTE', 'VACANTE', '$36,065.96', '240', 'N5', 'Dirección de Operación', 'Subdirección de Seguridad de la Aviación', 'Gerencia de Seguridad', 'Supervisor de Seguridad Aeroportuaria', 'Supervisor de Seguridad Aeroportuaria', 'NO', 'NO', 'NO', 'NO', 'NO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
  END IF;
END $$;

-- [VACANTE 5] Plaza 247
DO $$
BEGIN
  UPDATE public.agenda_2026
  SET
      "Nombre" = 'VACANTE',
      "Fecha de alta" = 'VACANTE',
      "Sueldo_Bruto" = '$60,034.00',
      "Plaza" = '247',
      "Nivel" = 'N32',
      "Dir. Orgánica" = 'Dirección de Operación',
      "Subdir. Orgánica" = 'Subdirección de Seguridad de la Aviación',
      "Gerencia Orgánica" = 'Gerencia de Identificación Aeroportuaria',
      "Coordinación Orgánica" = '----',
      "Puesto" = 'Gerente de Identificación Aeroportuaria',
      "Personal Comisionado" = 'NO',
      "Dirección Comisionado" = 'NO',
      "Subdirección Comisionado" = 'NO',
      "Gerencia Comisionado" = 'NO',
      "Coordinación Comisionado" = 'NO',
      "Comentarios" = NULL,
      "Amonestaciones" = NULL,
      "Rúbrica" = NULL,
      "Anexo ""A"" Turno especial" = NULL,
      "Anexo ""A"" Fecha de activación" = NULL,
      "Anexo ""B"" Riesgos" = NULL,
      "Anexo ""B"" Fecha de activación" = NULL,
      "Antigüedad" = NULL,
      "Días de vacaciones disponibles" = NULL,
      "Fecha de nacimiento" = NULL,
      "Sexo" = NULL,
      "CURP" = NULL,
      "RFC" = NULL,
      "NSS" = NULL,
      "Vigencia de INE" = NULL,
      "Fotografia de INE" = NULL,
      "No. telefónico" = NULL,
      "Domicilio (calle, colonia, municipio, estado y código postal)" = NULL,
      "Persona Civil o Militar" = NULL,
      "Grado Militar" = NULL,
      "Personal en activo o retirado" = NULL,
      "Matrícula Militar" = NULL,
      "Estado civil" = NULL,
      "Dependientes (hijos)" = NULL,
      "RUSP" = NULL,
      "Tipo de sangre" = NULL,
      "Alérgico a algún medicamento Si ó No (Especificar)" = NULL,
      "Alérgico a algún alimento. Si ó No (Especificar)" = NULL,
      "Contacto de emergencia 1 Nombre completo" = NULL,
      "Parentesco 1" = NULL,
      "Teléfono de emergencia 1" = NULL,
      "Contacto de emergencia 2 Nombre completo" = NULL,
      "Parentesco 2" = NULL,
      "Teléfono de emergencia 2" = NULL,
      "Nivel de estudio" = NULL,
      "Nombre de la Licenciatura y/o Maestria" = NULL,
      "Grado Acad?mico" = NULL,
      "Estatus" = 'Baja',
      "Nombre de la Universidad" = NULL,
      "Año de Titulación" = NULL,
      "No. Cédula Profesional" = NULL,
      "Fotografía (vest. Formal)" = NULL,
      "Correo Personal" = NULL,
      "Correo Institucional" = NULL,
      "Extensión" = NULL,
      "Vigencia de la TIA" = NULL,
      "Fotografía de la TIA" = NULL,
      "Licencia de Manejo" = NULL,
      "Tipo de licencia" = NULL,
      "Licencia Vigencia" = NULL,
      "Fotografia de licencia" = NULL,
      "Edad" = NULL,
      "Cumpleaños" = NULL,
      "Doc. Para ingreso" = NULL
  WHERE ("No. Empleado" IS NULL OR btrim("No. Empleado"::text) = '')
    AND "Plaza"::text = '247';

  IF NOT FOUND THEN
    INSERT INTO public.agenda_2026 ("No. Empleado", "Nombre", "Fecha de alta", "Sueldo_Bruto", "Plaza", "Nivel", "Dir. Orgánica", "Subdir. Orgánica", "Gerencia Orgánica", "Coordinación Orgánica", "Puesto", "Personal Comisionado", "Dirección Comisionado", "Subdirección Comisionado", "Gerencia Comisionado", "Coordinación Comisionado", "Comentarios", "Amonestaciones", "Rúbrica", "Anexo ""A"" Turno especial", "Anexo ""A"" Fecha de activación", "Anexo ""B"" Riesgos", "Anexo ""B"" Fecha de activación", "Antigüedad", "Días de vacaciones disponibles", "Fecha de nacimiento", "Sexo", "CURP", "RFC", "NSS", "Vigencia de INE", "Fotografia de INE", "No. telefónico", "Domicilio (calle, colonia, municipio, estado y código postal)", "Persona Civil o Militar", "Grado Militar", "Personal en activo o retirado", "Matrícula Militar", "Estado civil", "Dependientes (hijos)", "RUSP", "Tipo de sangre", "Alérgico a algún medicamento Si ó No (Especificar)", "Alérgico a algún alimento. Si ó No (Especificar)", "Contacto de emergencia 1 Nombre completo", "Parentesco 1", "Teléfono de emergencia 1", "Contacto de emergencia 2 Nombre completo", "Parentesco 2", "Teléfono de emergencia 2", "Nivel de estudio", "Nombre de la Licenciatura y/o Maestria", "Grado Acad?mico", "Estatus", "Nombre de la Universidad", "Año de Titulación", "No. Cédula Profesional", "Fotografía (vest. Formal)", "Correo Personal", "Correo Institucional", "Extensión", "Vigencia de la TIA", "Fotografía de la TIA", "Licencia de Manejo", "Tipo de licencia", "Licencia Vigencia", "Fotografia de licencia", "Edad", "Cumpleaños", "Doc. Para ingreso")
    VALUES (NULL, 'VACANTE', 'VACANTE', '$60,034.00', '247', 'N32', 'Dirección de Operación', 'Subdirección de Seguridad de la Aviación', 'Gerencia de Identificación Aeroportuaria', '----', 'Gerente de Identificación Aeroportuaria', 'NO', 'NO', 'NO', 'NO', 'NO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
  END IF;
END $$;

-- [VACANTE 6] Plaza 293
DO $$
BEGIN
  UPDATE public.agenda_2026
  SET
      "Nombre" = 'VACANTE',
      "Fecha de alta" = 'VACANTE',
      "Sueldo_Bruto" = '$29,958.98',
      "Plaza" = '293',
      "Nivel" = 'N4',
      "Dir. Orgánica" = 'Dirección de Operación',
      "Subdir. Orgánica" = 'Subdirección de Ingeniería',
      "Gerencia Orgánica" = 'Gerencia de Proyectos y Concursos',
      "Coordinación Orgánica" = 'Coord. de Área de Apoyo Téc.',
      "Puesto" = 'Profesional de Servicios Especializados Aeroportuarios',
      "Personal Comisionado" = 'NO',
      "Dirección Comisionado" = 'NO',
      "Subdirección Comisionado" = 'NO',
      "Gerencia Comisionado" = 'NO',
      "Coordinación Comisionado" = 'NO',
      "Comentarios" = NULL,
      "Amonestaciones" = NULL,
      "Rúbrica" = NULL,
      "Anexo ""A"" Turno especial" = NULL,
      "Anexo ""A"" Fecha de activación" = NULL,
      "Anexo ""B"" Riesgos" = NULL,
      "Anexo ""B"" Fecha de activación" = NULL,
      "Antigüedad" = NULL,
      "Días de vacaciones disponibles" = NULL,
      "Fecha de nacimiento" = NULL,
      "Sexo" = NULL,
      "CURP" = NULL,
      "RFC" = NULL,
      "NSS" = NULL,
      "Vigencia de INE" = NULL,
      "Fotografia de INE" = NULL,
      "No. telefónico" = NULL,
      "Domicilio (calle, colonia, municipio, estado y código postal)" = NULL,
      "Persona Civil o Militar" = NULL,
      "Grado Militar" = NULL,
      "Personal en activo o retirado" = NULL,
      "Matrícula Militar" = NULL,
      "Estado civil" = NULL,
      "Dependientes (hijos)" = NULL,
      "RUSP" = NULL,
      "Tipo de sangre" = NULL,
      "Alérgico a algún medicamento Si ó No (Especificar)" = NULL,
      "Alérgico a algún alimento. Si ó No (Especificar)" = NULL,
      "Contacto de emergencia 1 Nombre completo" = NULL,
      "Parentesco 1" = NULL,
      "Teléfono de emergencia 1" = NULL,
      "Contacto de emergencia 2 Nombre completo" = NULL,
      "Parentesco 2" = NULL,
      "Teléfono de emergencia 2" = NULL,
      "Nivel de estudio" = NULL,
      "Nombre de la Licenciatura y/o Maestria" = NULL,
      "Grado Acad?mico" = NULL,
      "Estatus" = 'Baja',
      "Nombre de la Universidad" = NULL,
      "Año de Titulación" = NULL,
      "No. Cédula Profesional" = NULL,
      "Fotografía (vest. Formal)" = NULL,
      "Correo Personal" = NULL,
      "Correo Institucional" = NULL,
      "Extensión" = NULL,
      "Vigencia de la TIA" = NULL,
      "Fotografía de la TIA" = NULL,
      "Licencia de Manejo" = NULL,
      "Tipo de licencia" = NULL,
      "Licencia Vigencia" = NULL,
      "Fotografia de licencia" = NULL,
      "Edad" = NULL,
      "Cumpleaños" = NULL,
      "Doc. Para ingreso" = NULL
  WHERE ("No. Empleado" IS NULL OR btrim("No. Empleado"::text) = '')
    AND "Plaza"::text = '293';

  IF NOT FOUND THEN
    INSERT INTO public.agenda_2026 ("No. Empleado", "Nombre", "Fecha de alta", "Sueldo_Bruto", "Plaza", "Nivel", "Dir. Orgánica", "Subdir. Orgánica", "Gerencia Orgánica", "Coordinación Orgánica", "Puesto", "Personal Comisionado", "Dirección Comisionado", "Subdirección Comisionado", "Gerencia Comisionado", "Coordinación Comisionado", "Comentarios", "Amonestaciones", "Rúbrica", "Anexo ""A"" Turno especial", "Anexo ""A"" Fecha de activación", "Anexo ""B"" Riesgos", "Anexo ""B"" Fecha de activación", "Antigüedad", "Días de vacaciones disponibles", "Fecha de nacimiento", "Sexo", "CURP", "RFC", "NSS", "Vigencia de INE", "Fotografia de INE", "No. telefónico", "Domicilio (calle, colonia, municipio, estado y código postal)", "Persona Civil o Militar", "Grado Militar", "Personal en activo o retirado", "Matrícula Militar", "Estado civil", "Dependientes (hijos)", "RUSP", "Tipo de sangre", "Alérgico a algún medicamento Si ó No (Especificar)", "Alérgico a algún alimento. Si ó No (Especificar)", "Contacto de emergencia 1 Nombre completo", "Parentesco 1", "Teléfono de emergencia 1", "Contacto de emergencia 2 Nombre completo", "Parentesco 2", "Teléfono de emergencia 2", "Nivel de estudio", "Nombre de la Licenciatura y/o Maestria", "Grado Acad?mico", "Estatus", "Nombre de la Universidad", "Año de Titulación", "No. Cédula Profesional", "Fotografía (vest. Formal)", "Correo Personal", "Correo Institucional", "Extensión", "Vigencia de la TIA", "Fotografía de la TIA", "Licencia de Manejo", "Tipo de licencia", "Licencia Vigencia", "Fotografia de licencia", "Edad", "Cumpleaños", "Doc. Para ingreso")
    VALUES (NULL, 'VACANTE', 'VACANTE', '$29,958.98', '293', 'N4', 'Dirección de Operación', 'Subdirección de Ingeniería', 'Gerencia de Proyectos y Concursos', 'Coord. de Área de Apoyo Téc.', 'Profesional de Servicios Especializados Aeroportuarios', 'NO', 'NO', 'NO', 'NO', 'NO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
  END IF;
END $$;

-- [VACANTE 7] Plaza 362
DO $$
BEGIN
  UPDATE public.agenda_2026
  SET
      "Nombre" = 'VACANTE',
      "Fecha de alta" = 'VACANTE',
      "Sueldo_Bruto" = '$45,280.81',
      "Plaza" = '362',
      "Nivel" = 'N6',
      "Dir. Orgánica" = 'Dirección de Operación',
      "Subdir. Orgánica" = 'Subdirección de Ingeniería',
      "Gerencia Orgánica" = 'Gerencia de Ingeniería Electromecánica',
      "Coordinación Orgánica" = 'Coordinación de Equipos Mecánicos',
      "Puesto" = 'Coordinador de Ingeniería Electromecánica',
      "Personal Comisionado" = 'NO',
      "Dirección Comisionado" = 'NO',
      "Subdirección Comisionado" = 'NO',
      "Gerencia Comisionado" = 'NO',
      "Coordinación Comisionado" = 'NO',
      "Comentarios" = NULL,
      "Amonestaciones" = NULL,
      "Rúbrica" = NULL,
      "Anexo ""A"" Turno especial" = NULL,
      "Anexo ""A"" Fecha de activación" = NULL,
      "Anexo ""B"" Riesgos" = NULL,
      "Anexo ""B"" Fecha de activación" = NULL,
      "Antigüedad" = NULL,
      "Días de vacaciones disponibles" = NULL,
      "Fecha de nacimiento" = NULL,
      "Sexo" = NULL,
      "CURP" = NULL,
      "RFC" = NULL,
      "NSS" = NULL,
      "Vigencia de INE" = NULL,
      "Fotografia de INE" = NULL,
      "No. telefónico" = NULL,
      "Domicilio (calle, colonia, municipio, estado y código postal)" = NULL,
      "Persona Civil o Militar" = NULL,
      "Grado Militar" = NULL,
      "Personal en activo o retirado" = NULL,
      "Matrícula Militar" = NULL,
      "Estado civil" = NULL,
      "Dependientes (hijos)" = NULL,
      "RUSP" = NULL,
      "Tipo de sangre" = NULL,
      "Alérgico a algún medicamento Si ó No (Especificar)" = NULL,
      "Alérgico a algún alimento. Si ó No (Especificar)" = NULL,
      "Contacto de emergencia 1 Nombre completo" = NULL,
      "Parentesco 1" = NULL,
      "Teléfono de emergencia 1" = NULL,
      "Contacto de emergencia 2 Nombre completo" = NULL,
      "Parentesco 2" = NULL,
      "Teléfono de emergencia 2" = NULL,
      "Nivel de estudio" = NULL,
      "Nombre de la Licenciatura y/o Maestria" = NULL,
      "Grado Acad?mico" = NULL,
      "Estatus" = 'Baja',
      "Nombre de la Universidad" = NULL,
      "Año de Titulación" = NULL,
      "No. Cédula Profesional" = NULL,
      "Fotografía (vest. Formal)" = NULL,
      "Correo Personal" = NULL,
      "Correo Institucional" = NULL,
      "Extensión" = NULL,
      "Vigencia de la TIA" = NULL,
      "Fotografía de la TIA" = NULL,
      "Licencia de Manejo" = NULL,
      "Tipo de licencia" = NULL,
      "Licencia Vigencia" = NULL,
      "Fotografia de licencia" = NULL,
      "Edad" = NULL,
      "Cumpleaños" = NULL,
      "Doc. Para ingreso" = NULL
  WHERE ("No. Empleado" IS NULL OR btrim("No. Empleado"::text) = '')
    AND "Plaza"::text = '362';

  IF NOT FOUND THEN
    INSERT INTO public.agenda_2026 ("No. Empleado", "Nombre", "Fecha de alta", "Sueldo_Bruto", "Plaza", "Nivel", "Dir. Orgánica", "Subdir. Orgánica", "Gerencia Orgánica", "Coordinación Orgánica", "Puesto", "Personal Comisionado", "Dirección Comisionado", "Subdirección Comisionado", "Gerencia Comisionado", "Coordinación Comisionado", "Comentarios", "Amonestaciones", "Rúbrica", "Anexo ""A"" Turno especial", "Anexo ""A"" Fecha de activación", "Anexo ""B"" Riesgos", "Anexo ""B"" Fecha de activación", "Antigüedad", "Días de vacaciones disponibles", "Fecha de nacimiento", "Sexo", "CURP", "RFC", "NSS", "Vigencia de INE", "Fotografia de INE", "No. telefónico", "Domicilio (calle, colonia, municipio, estado y código postal)", "Persona Civil o Militar", "Grado Militar", "Personal en activo o retirado", "Matrícula Militar", "Estado civil", "Dependientes (hijos)", "RUSP", "Tipo de sangre", "Alérgico a algún medicamento Si ó No (Especificar)", "Alérgico a algún alimento. Si ó No (Especificar)", "Contacto de emergencia 1 Nombre completo", "Parentesco 1", "Teléfono de emergencia 1", "Contacto de emergencia 2 Nombre completo", "Parentesco 2", "Teléfono de emergencia 2", "Nivel de estudio", "Nombre de la Licenciatura y/o Maestria", "Grado Acad?mico", "Estatus", "Nombre de la Universidad", "Año de Titulación", "No. Cédula Profesional", "Fotografía (vest. Formal)", "Correo Personal", "Correo Institucional", "Extensión", "Vigencia de la TIA", "Fotografía de la TIA", "Licencia de Manejo", "Tipo de licencia", "Licencia Vigencia", "Fotografia de licencia", "Edad", "Cumpleaños", "Doc. Para ingreso")
    VALUES (NULL, 'VACANTE', 'VACANTE', '$45,280.81', '362', 'N6', 'Dirección de Operación', 'Subdirección de Ingeniería', 'Gerencia de Ingeniería Electromecánica', 'Coordinación de Equipos Mecánicos', 'Coordinador de Ingeniería Electromecánica', 'NO', 'NO', 'NO', 'NO', 'NO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
  END IF;
END $$;

-- [VACANTE 8] Plaza 395
DO $$
BEGIN
  UPDATE public.agenda_2026
  SET
      "Nombre" = 'VACANTE',
      "Fecha de alta" = 'VACANTE',
      "Sueldo_Bruto" = '$60,034.00',
      "Plaza" = '395',
      "Nivel" = 'N32',
      "Dir. Orgánica" = 'Dirección de Operación',
      "Subdir. Orgánica" = 'Subdirección de Servicios Conexos',
      "Gerencia Orgánica" = 'Gerencia de Aviación General',
      "Coordinación Orgánica" = '----',
      "Puesto" = 'Gerente de Aviación General',
      "Personal Comisionado" = 'NO',
      "Dirección Comisionado" = 'NO',
      "Subdirección Comisionado" = 'NO',
      "Gerencia Comisionado" = 'NO',
      "Coordinación Comisionado" = 'NO',
      "Comentarios" = NULL,
      "Amonestaciones" = NULL,
      "Rúbrica" = NULL,
      "Anexo ""A"" Turno especial" = NULL,
      "Anexo ""A"" Fecha de activación" = NULL,
      "Anexo ""B"" Riesgos" = NULL,
      "Anexo ""B"" Fecha de activación" = NULL,
      "Antigüedad" = NULL,
      "Días de vacaciones disponibles" = NULL,
      "Fecha de nacimiento" = NULL,
      "Sexo" = NULL,
      "CURP" = NULL,
      "RFC" = NULL,
      "NSS" = NULL,
      "Vigencia de INE" = NULL,
      "Fotografia de INE" = NULL,
      "No. telefónico" = NULL,
      "Domicilio (calle, colonia, municipio, estado y código postal)" = NULL,
      "Persona Civil o Militar" = NULL,
      "Grado Militar" = NULL,
      "Personal en activo o retirado" = NULL,
      "Matrícula Militar" = NULL,
      "Estado civil" = NULL,
      "Dependientes (hijos)" = NULL,
      "RUSP" = NULL,
      "Tipo de sangre" = NULL,
      "Alérgico a algún medicamento Si ó No (Especificar)" = NULL,
      "Alérgico a algún alimento. Si ó No (Especificar)" = NULL,
      "Contacto de emergencia 1 Nombre completo" = NULL,
      "Parentesco 1" = NULL,
      "Teléfono de emergencia 1" = NULL,
      "Contacto de emergencia 2 Nombre completo" = NULL,
      "Parentesco 2" = NULL,
      "Teléfono de emergencia 2" = NULL,
      "Nivel de estudio" = NULL,
      "Nombre de la Licenciatura y/o Maestria" = NULL,
      "Grado Acad?mico" = NULL,
      "Estatus" = 'Baja',
      "Nombre de la Universidad" = NULL,
      "Año de Titulación" = NULL,
      "No. Cédula Profesional" = NULL,
      "Fotografía (vest. Formal)" = NULL,
      "Correo Personal" = NULL,
      "Correo Institucional" = NULL,
      "Extensión" = NULL,
      "Vigencia de la TIA" = NULL,
      "Fotografía de la TIA" = NULL,
      "Licencia de Manejo" = NULL,
      "Tipo de licencia" = NULL,
      "Licencia Vigencia" = NULL,
      "Fotografia de licencia" = NULL,
      "Edad" = NULL,
      "Cumpleaños" = NULL,
      "Doc. Para ingreso" = NULL
  WHERE ("No. Empleado" IS NULL OR btrim("No. Empleado"::text) = '')
    AND "Plaza"::text = '395';

  IF NOT FOUND THEN
    INSERT INTO public.agenda_2026 ("No. Empleado", "Nombre", "Fecha de alta", "Sueldo_Bruto", "Plaza", "Nivel", "Dir. Orgánica", "Subdir. Orgánica", "Gerencia Orgánica", "Coordinación Orgánica", "Puesto", "Personal Comisionado", "Dirección Comisionado", "Subdirección Comisionado", "Gerencia Comisionado", "Coordinación Comisionado", "Comentarios", "Amonestaciones", "Rúbrica", "Anexo ""A"" Turno especial", "Anexo ""A"" Fecha de activación", "Anexo ""B"" Riesgos", "Anexo ""B"" Fecha de activación", "Antigüedad", "Días de vacaciones disponibles", "Fecha de nacimiento", "Sexo", "CURP", "RFC", "NSS", "Vigencia de INE", "Fotografia de INE", "No. telefónico", "Domicilio (calle, colonia, municipio, estado y código postal)", "Persona Civil o Militar", "Grado Militar", "Personal en activo o retirado", "Matrícula Militar", "Estado civil", "Dependientes (hijos)", "RUSP", "Tipo de sangre", "Alérgico a algún medicamento Si ó No (Especificar)", "Alérgico a algún alimento. Si ó No (Especificar)", "Contacto de emergencia 1 Nombre completo", "Parentesco 1", "Teléfono de emergencia 1", "Contacto de emergencia 2 Nombre completo", "Parentesco 2", "Teléfono de emergencia 2", "Nivel de estudio", "Nombre de la Licenciatura y/o Maestria", "Grado Acad?mico", "Estatus", "Nombre de la Universidad", "Año de Titulación", "No. Cédula Profesional", "Fotografía (vest. Formal)", "Correo Personal", "Correo Institucional", "Extensión", "Vigencia de la TIA", "Fotografía de la TIA", "Licencia de Manejo", "Tipo de licencia", "Licencia Vigencia", "Fotografia de licencia", "Edad", "Cumpleaños", "Doc. Para ingreso")
    VALUES (NULL, 'VACANTE', 'VACANTE', '$60,034.00', '395', 'N32', 'Dirección de Operación', 'Subdirección de Servicios Conexos', 'Gerencia de Aviación General', '----', 'Gerente de Aviación General', 'NO', 'NO', 'NO', 'NO', 'NO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
  END IF;
END $$;

-- [VACANTE 9] Plaza 
DO $$
BEGIN
  UPDATE public.agenda_2026
  SET
      "Nombre" = 'VACANTE',
      "Fecha de alta" = 'VACANTE',
      "Sueldo_Bruto" = NULL,
      "Plaza" = NULL,
      "Nivel" = NULL,
      "Dir. Orgánica" = NULL,
      "Subdir. Orgánica" = NULL,
      "Gerencia Orgánica" = NULL,
      "Coordinación Orgánica" = NULL,
      "Puesto" = NULL,
      "Personal Comisionado" = 'NO',
      "Dirección Comisionado" = 'NO',
      "Subdirección Comisionado" = 'NO',
      "Gerencia Comisionado" = 'NO',
      "Coordinación Comisionado" = 'NO',
      "Comentarios" = NULL,
      "Amonestaciones" = NULL,
      "Rúbrica" = NULL,
      "Anexo ""A"" Turno especial" = NULL,
      "Anexo ""A"" Fecha de activación" = NULL,
      "Anexo ""B"" Riesgos" = NULL,
      "Anexo ""B"" Fecha de activación" = NULL,
      "Antigüedad" = NULL,
      "Días de vacaciones disponibles" = NULL,
      "Fecha de nacimiento" = NULL,
      "Sexo" = NULL,
      "CURP" = NULL,
      "RFC" = NULL,
      "NSS" = NULL,
      "Vigencia de INE" = NULL,
      "Fotografia de INE" = NULL,
      "No. telefónico" = NULL,
      "Domicilio (calle, colonia, municipio, estado y código postal)" = NULL,
      "Persona Civil o Militar" = NULL,
      "Grado Militar" = NULL,
      "Personal en activo o retirado" = NULL,
      "Matrícula Militar" = NULL,
      "Estado civil" = NULL,
      "Dependientes (hijos)" = NULL,
      "RUSP" = NULL,
      "Tipo de sangre" = NULL,
      "Alérgico a algún medicamento Si ó No (Especificar)" = NULL,
      "Alérgico a algún alimento. Si ó No (Especificar)" = NULL,
      "Contacto de emergencia 1 Nombre completo" = NULL,
      "Parentesco 1" = NULL,
      "Teléfono de emergencia 1" = NULL,
      "Contacto de emergencia 2 Nombre completo" = NULL,
      "Parentesco 2" = NULL,
      "Teléfono de emergencia 2" = NULL,
      "Nivel de estudio" = NULL,
      "Nombre de la Licenciatura y/o Maestria" = NULL,
      "Grado Acad?mico" = NULL,
      "Estatus" = 'Baja',
      "Nombre de la Universidad" = NULL,
      "Año de Titulación" = NULL,
      "No. Cédula Profesional" = NULL,
      "Fotografía (vest. Formal)" = NULL,
      "Correo Personal" = NULL,
      "Correo Institucional" = NULL,
      "Extensión" = NULL,
      "Vigencia de la TIA" = NULL,
      "Fotografía de la TIA" = NULL,
      "Licencia de Manejo" = NULL,
      "Tipo de licencia" = NULL,
      "Licencia Vigencia" = NULL,
      "Fotografia de licencia" = NULL,
      "Edad" = NULL,
      "Cumpleaños" = NULL,
      "Doc. Para ingreso" = NULL
  WHERE ("No. Empleado" IS NULL OR btrim("No. Empleado"::text) = '')
    AND "Plaza"::text = NULL;

  IF NOT FOUND THEN
    INSERT INTO public.agenda_2026 ("No. Empleado", "Nombre", "Fecha de alta", "Sueldo_Bruto", "Plaza", "Nivel", "Dir. Orgánica", "Subdir. Orgánica", "Gerencia Orgánica", "Coordinación Orgánica", "Puesto", "Personal Comisionado", "Dirección Comisionado", "Subdirección Comisionado", "Gerencia Comisionado", "Coordinación Comisionado", "Comentarios", "Amonestaciones", "Rúbrica", "Anexo ""A"" Turno especial", "Anexo ""A"" Fecha de activación", "Anexo ""B"" Riesgos", "Anexo ""B"" Fecha de activación", "Antigüedad", "Días de vacaciones disponibles", "Fecha de nacimiento", "Sexo", "CURP", "RFC", "NSS", "Vigencia de INE", "Fotografia de INE", "No. telefónico", "Domicilio (calle, colonia, municipio, estado y código postal)", "Persona Civil o Militar", "Grado Militar", "Personal en activo o retirado", "Matrícula Militar", "Estado civil", "Dependientes (hijos)", "RUSP", "Tipo de sangre", "Alérgico a algún medicamento Si ó No (Especificar)", "Alérgico a algún alimento. Si ó No (Especificar)", "Contacto de emergencia 1 Nombre completo", "Parentesco 1", "Teléfono de emergencia 1", "Contacto de emergencia 2 Nombre completo", "Parentesco 2", "Teléfono de emergencia 2", "Nivel de estudio", "Nombre de la Licenciatura y/o Maestria", "Grado Acad?mico", "Estatus", "Nombre de la Universidad", "Año de Titulación", "No. Cédula Profesional", "Fotografía (vest. Formal)", "Correo Personal", "Correo Institucional", "Extensión", "Vigencia de la TIA", "Fotografía de la TIA", "Licencia de Manejo", "Tipo de licencia", "Licencia Vigencia", "Fotografia de licencia", "Edad", "Cumpleaños", "Doc. Para ingreso")
    VALUES (NULL, 'VACANTE', 'VACANTE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NO', 'NO', 'NO', 'NO', 'NO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
  END IF;
END $$;

-- [VACANTE 10] Plaza 23E
DO $$
BEGIN
  UPDATE public.agenda_2026
  SET
      "Nombre" = 'VACANTE',
      "Fecha de alta" = 'VACANTE',
      "Sueldo_Bruto" = NULL,
      "Plaza" = '23E',
      "Nivel" = 'N32',
      "Dir. Orgánica" = 'Dirección de Operación',
      "Subdir. Orgánica" = 'Subdirección de Gestión Energética',
      "Gerencia Orgánica" = 'Gerente de Generación',
      "Coordinación Orgánica" = '----',
      "Puesto" = 'Gerente de Generación',
      "Personal Comisionado" = 'NO',
      "Dirección Comisionado" = 'NO',
      "Subdirección Comisionado" = 'NO',
      "Gerencia Comisionado" = 'NO',
      "Coordinación Comisionado" = 'NO',
      "Comentarios" = NULL,
      "Amonestaciones" = NULL,
      "Rúbrica" = NULL,
      "Anexo ""A"" Turno especial" = NULL,
      "Anexo ""A"" Fecha de activación" = NULL,
      "Anexo ""B"" Riesgos" = NULL,
      "Anexo ""B"" Fecha de activación" = NULL,
      "Antigüedad" = NULL,
      "Días de vacaciones disponibles" = NULL,
      "Fecha de nacimiento" = NULL,
      "Sexo" = NULL,
      "CURP" = NULL,
      "RFC" = NULL,
      "NSS" = NULL,
      "Vigencia de INE" = NULL,
      "Fotografia de INE" = NULL,
      "No. telefónico" = NULL,
      "Domicilio (calle, colonia, municipio, estado y código postal)" = NULL,
      "Persona Civil o Militar" = NULL,
      "Grado Militar" = NULL,
      "Personal en activo o retirado" = NULL,
      "Matrícula Militar" = NULL,
      "Estado civil" = NULL,
      "Dependientes (hijos)" = NULL,
      "RUSP" = NULL,
      "Tipo de sangre" = NULL,
      "Alérgico a algún medicamento Si ó No (Especificar)" = NULL,
      "Alérgico a algún alimento. Si ó No (Especificar)" = NULL,
      "Contacto de emergencia 1 Nombre completo" = NULL,
      "Parentesco 1" = NULL,
      "Teléfono de emergencia 1" = NULL,
      "Contacto de emergencia 2 Nombre completo" = NULL,
      "Parentesco 2" = NULL,
      "Teléfono de emergencia 2" = NULL,
      "Nivel de estudio" = NULL,
      "Nombre de la Licenciatura y/o Maestria" = NULL,
      "Grado Acad?mico" = NULL,
      "Estatus" = 'Baja',
      "Nombre de la Universidad" = NULL,
      "Año de Titulación" = NULL,
      "No. Cédula Profesional" = NULL,
      "Fotografía (vest. Formal)" = NULL,
      "Correo Personal" = NULL,
      "Correo Institucional" = NULL,
      "Extensión" = NULL,
      "Vigencia de la TIA" = NULL,
      "Fotografía de la TIA" = NULL,
      "Licencia de Manejo" = NULL,
      "Tipo de licencia" = NULL,
      "Licencia Vigencia" = NULL,
      "Fotografia de licencia" = NULL,
      "Edad" = NULL,
      "Cumpleaños" = NULL,
      "Doc. Para ingreso" = NULL
  WHERE ("No. Empleado" IS NULL OR btrim("No. Empleado"::text) = '')
    AND "Plaza"::text = '23E';

  IF NOT FOUND THEN
    INSERT INTO public.agenda_2026 ("No. Empleado", "Nombre", "Fecha de alta", "Sueldo_Bruto", "Plaza", "Nivel", "Dir. Orgánica", "Subdir. Orgánica", "Gerencia Orgánica", "Coordinación Orgánica", "Puesto", "Personal Comisionado", "Dirección Comisionado", "Subdirección Comisionado", "Gerencia Comisionado", "Coordinación Comisionado", "Comentarios", "Amonestaciones", "Rúbrica", "Anexo ""A"" Turno especial", "Anexo ""A"" Fecha de activación", "Anexo ""B"" Riesgos", "Anexo ""B"" Fecha de activación", "Antigüedad", "Días de vacaciones disponibles", "Fecha de nacimiento", "Sexo", "CURP", "RFC", "NSS", "Vigencia de INE", "Fotografia de INE", "No. telefónico", "Domicilio (calle, colonia, municipio, estado y código postal)", "Persona Civil o Militar", "Grado Militar", "Personal en activo o retirado", "Matrícula Militar", "Estado civil", "Dependientes (hijos)", "RUSP", "Tipo de sangre", "Alérgico a algún medicamento Si ó No (Especificar)", "Alérgico a algún alimento. Si ó No (Especificar)", "Contacto de emergencia 1 Nombre completo", "Parentesco 1", "Teléfono de emergencia 1", "Contacto de emergencia 2 Nombre completo", "Parentesco 2", "Teléfono de emergencia 2", "Nivel de estudio", "Nombre de la Licenciatura y/o Maestria", "Grado Acad?mico", "Estatus", "Nombre de la Universidad", "Año de Titulación", "No. Cédula Profesional", "Fotografía (vest. Formal)", "Correo Personal", "Correo Institucional", "Extensión", "Vigencia de la TIA", "Fotografía de la TIA", "Licencia de Manejo", "Tipo de licencia", "Licencia Vigencia", "Fotografia de licencia", "Edad", "Cumpleaños", "Doc. Para ingreso")
    VALUES (NULL, 'VACANTE', 'VACANTE', NULL, '23E', 'N32', 'Dirección de Operación', 'Subdirección de Gestión Energética', 'Gerente de Generación', '----', 'Gerente de Generación', 'NO', 'NO', 'NO', 'NO', 'NO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
  END IF;
END $$;

-- [VACANTE 11] Plaza 54E
DO $$
BEGIN
  UPDATE public.agenda_2026
  SET
      "Nombre" = 'VACANTE',
      "Fecha de alta" = 'VACANTE',
      "Sueldo_Bruto" = NULL,
      "Plaza" = '54E',
      "Nivel" = 'N4',
      "Dir. Orgánica" = 'Dirección de Operación',
      "Subdir. Orgánica" = 'Subdirección de Seguridad Operacional',
      "Gerencia Orgánica" = 'Gerencia de Operaciones Edificio Terminal',
      "Coordinación Orgánica" = 'Técnico de BHS y Carruseles',
      "Puesto" = 'Técnico de BHS y Carruseles',
      "Personal Comisionado" = 'NO',
      "Dirección Comisionado" = 'NO',
      "Subdirección Comisionado" = 'NO',
      "Gerencia Comisionado" = 'NO',
      "Coordinación Comisionado" = 'NO',
      "Comentarios" = NULL,
      "Amonestaciones" = NULL,
      "Rúbrica" = NULL,
      "Anexo ""A"" Turno especial" = NULL,
      "Anexo ""A"" Fecha de activación" = NULL,
      "Anexo ""B"" Riesgos" = NULL,
      "Anexo ""B"" Fecha de activación" = NULL,
      "Antigüedad" = NULL,
      "Días de vacaciones disponibles" = NULL,
      "Fecha de nacimiento" = NULL,
      "Sexo" = NULL,
      "CURP" = NULL,
      "RFC" = NULL,
      "NSS" = NULL,
      "Vigencia de INE" = NULL,
      "Fotografia de INE" = NULL,
      "No. telefónico" = NULL,
      "Domicilio (calle, colonia, municipio, estado y código postal)" = NULL,
      "Persona Civil o Militar" = NULL,
      "Grado Militar" = NULL,
      "Personal en activo o retirado" = NULL,
      "Matrícula Militar" = NULL,
      "Estado civil" = NULL,
      "Dependientes (hijos)" = NULL,
      "RUSP" = NULL,
      "Tipo de sangre" = NULL,
      "Alérgico a algún medicamento Si ó No (Especificar)" = NULL,
      "Alérgico a algún alimento. Si ó No (Especificar)" = NULL,
      "Contacto de emergencia 1 Nombre completo" = NULL,
      "Parentesco 1" = NULL,
      "Teléfono de emergencia 1" = NULL,
      "Contacto de emergencia 2 Nombre completo" = NULL,
      "Parentesco 2" = NULL,
      "Teléfono de emergencia 2" = NULL,
      "Nivel de estudio" = NULL,
      "Nombre de la Licenciatura y/o Maestria" = NULL,
      "Grado Acad?mico" = NULL,
      "Estatus" = 'Baja',
      "Nombre de la Universidad" = NULL,
      "Año de Titulación" = NULL,
      "No. Cédula Profesional" = NULL,
      "Fotografía (vest. Formal)" = NULL,
      "Correo Personal" = NULL,
      "Correo Institucional" = NULL,
      "Extensión" = NULL,
      "Vigencia de la TIA" = NULL,
      "Fotografía de la TIA" = NULL,
      "Licencia de Manejo" = NULL,
      "Tipo de licencia" = NULL,
      "Licencia Vigencia" = NULL,
      "Fotografia de licencia" = NULL,
      "Edad" = NULL,
      "Cumpleaños" = NULL,
      "Doc. Para ingreso" = NULL
  WHERE ("No. Empleado" IS NULL OR btrim("No. Empleado"::text) = '')
    AND "Plaza"::text = '54E';

  IF NOT FOUND THEN
    INSERT INTO public.agenda_2026 ("No. Empleado", "Nombre", "Fecha de alta", "Sueldo_Bruto", "Plaza", "Nivel", "Dir. Orgánica", "Subdir. Orgánica", "Gerencia Orgánica", "Coordinación Orgánica", "Puesto", "Personal Comisionado", "Dirección Comisionado", "Subdirección Comisionado", "Gerencia Comisionado", "Coordinación Comisionado", "Comentarios", "Amonestaciones", "Rúbrica", "Anexo ""A"" Turno especial", "Anexo ""A"" Fecha de activación", "Anexo ""B"" Riesgos", "Anexo ""B"" Fecha de activación", "Antigüedad", "Días de vacaciones disponibles", "Fecha de nacimiento", "Sexo", "CURP", "RFC", "NSS", "Vigencia de INE", "Fotografia de INE", "No. telefónico", "Domicilio (calle, colonia, municipio, estado y código postal)", "Persona Civil o Militar", "Grado Militar", "Personal en activo o retirado", "Matrícula Militar", "Estado civil", "Dependientes (hijos)", "RUSP", "Tipo de sangre", "Alérgico a algún medicamento Si ó No (Especificar)", "Alérgico a algún alimento. Si ó No (Especificar)", "Contacto de emergencia 1 Nombre completo", "Parentesco 1", "Teléfono de emergencia 1", "Contacto de emergencia 2 Nombre completo", "Parentesco 2", "Teléfono de emergencia 2", "Nivel de estudio", "Nombre de la Licenciatura y/o Maestria", "Grado Acad?mico", "Estatus", "Nombre de la Universidad", "Año de Titulación", "No. Cédula Profesional", "Fotografía (vest. Formal)", "Correo Personal", "Correo Institucional", "Extensión", "Vigencia de la TIA", "Fotografía de la TIA", "Licencia de Manejo", "Tipo de licencia", "Licencia Vigencia", "Fotografia de licencia", "Edad", "Cumpleaños", "Doc. Para ingreso")
    VALUES (NULL, 'VACANTE', 'VACANTE', NULL, '54E', 'N4', 'Dirección de Operación', 'Subdirección de Seguridad Operacional', 'Gerencia de Operaciones Edificio Terminal', 'Técnico de BHS y Carruseles', 'Técnico de BHS y Carruseles', 'NO', 'NO', 'NO', 'NO', 'NO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
  END IF;
END $$;

-- [VACANTE 12] Plaza 65E
DO $$
BEGIN
  UPDATE public.agenda_2026
  SET
      "Nombre" = 'VACANTE',
      "Fecha de alta" = 'VACANTE',
      "Sueldo_Bruto" = NULL,
      "Plaza" = '65E',
      "Nivel" = 'N3',
      "Dir. Orgánica" = 'Dirección de Operación',
      "Subdir. Orgánica" = 'Subdirección de Seguridad Operacional',
      "Gerencia Orgánica" = 'Gerencia de Operaciones Parte Aeronáutica',
      "Coordinación Orgánica" = 'Operador de Aerocares',
      "Puesto" = 'Operador de Vehiculo Especializado',
      "Personal Comisionado" = 'NO',
      "Dirección Comisionado" = 'NO',
      "Subdirección Comisionado" = 'NO',
      "Gerencia Comisionado" = 'NO',
      "Coordinación Comisionado" = 'NO',
      "Comentarios" = NULL,
      "Amonestaciones" = NULL,
      "Rúbrica" = NULL,
      "Anexo ""A"" Turno especial" = NULL,
      "Anexo ""A"" Fecha de activación" = NULL,
      "Anexo ""B"" Riesgos" = NULL,
      "Anexo ""B"" Fecha de activación" = NULL,
      "Antigüedad" = NULL,
      "Días de vacaciones disponibles" = NULL,
      "Fecha de nacimiento" = NULL,
      "Sexo" = NULL,
      "CURP" = NULL,
      "RFC" = NULL,
      "NSS" = NULL,
      "Vigencia de INE" = NULL,
      "Fotografia de INE" = NULL,
      "No. telefónico" = NULL,
      "Domicilio (calle, colonia, municipio, estado y código postal)" = NULL,
      "Persona Civil o Militar" = NULL,
      "Grado Militar" = NULL,
      "Personal en activo o retirado" = NULL,
      "Matrícula Militar" = NULL,
      "Estado civil" = NULL,
      "Dependientes (hijos)" = NULL,
      "RUSP" = NULL,
      "Tipo de sangre" = NULL,
      "Alérgico a algún medicamento Si ó No (Especificar)" = NULL,
      "Alérgico a algún alimento. Si ó No (Especificar)" = NULL,
      "Contacto de emergencia 1 Nombre completo" = NULL,
      "Parentesco 1" = NULL,
      "Teléfono de emergencia 1" = NULL,
      "Contacto de emergencia 2 Nombre completo" = NULL,
      "Parentesco 2" = NULL,
      "Teléfono de emergencia 2" = NULL,
      "Nivel de estudio" = NULL,
      "Nombre de la Licenciatura y/o Maestria" = NULL,
      "Grado Acad?mico" = NULL,
      "Estatus" = 'Baja',
      "Nombre de la Universidad" = NULL,
      "Año de Titulación" = NULL,
      "No. Cédula Profesional" = NULL,
      "Fotografía (vest. Formal)" = NULL,
      "Correo Personal" = NULL,
      "Correo Institucional" = NULL,
      "Extensión" = NULL,
      "Vigencia de la TIA" = NULL,
      "Fotografía de la TIA" = NULL,
      "Licencia de Manejo" = NULL,
      "Tipo de licencia" = NULL,
      "Licencia Vigencia" = NULL,
      "Fotografia de licencia" = NULL,
      "Edad" = NULL,
      "Cumpleaños" = NULL,
      "Doc. Para ingreso" = NULL
  WHERE ("No. Empleado" IS NULL OR btrim("No. Empleado"::text) = '')
    AND "Plaza"::text = '65E';

  IF NOT FOUND THEN
    INSERT INTO public.agenda_2026 ("No. Empleado", "Nombre", "Fecha de alta", "Sueldo_Bruto", "Plaza", "Nivel", "Dir. Orgánica", "Subdir. Orgánica", "Gerencia Orgánica", "Coordinación Orgánica", "Puesto", "Personal Comisionado", "Dirección Comisionado", "Subdirección Comisionado", "Gerencia Comisionado", "Coordinación Comisionado", "Comentarios", "Amonestaciones", "Rúbrica", "Anexo ""A"" Turno especial", "Anexo ""A"" Fecha de activación", "Anexo ""B"" Riesgos", "Anexo ""B"" Fecha de activación", "Antigüedad", "Días de vacaciones disponibles", "Fecha de nacimiento", "Sexo", "CURP", "RFC", "NSS", "Vigencia de INE", "Fotografia de INE", "No. telefónico", "Domicilio (calle, colonia, municipio, estado y código postal)", "Persona Civil o Militar", "Grado Militar", "Personal en activo o retirado", "Matrícula Militar", "Estado civil", "Dependientes (hijos)", "RUSP", "Tipo de sangre", "Alérgico a algún medicamento Si ó No (Especificar)", "Alérgico a algún alimento. Si ó No (Especificar)", "Contacto de emergencia 1 Nombre completo", "Parentesco 1", "Teléfono de emergencia 1", "Contacto de emergencia 2 Nombre completo", "Parentesco 2", "Teléfono de emergencia 2", "Nivel de estudio", "Nombre de la Licenciatura y/o Maestria", "Grado Acad?mico", "Estatus", "Nombre de la Universidad", "Año de Titulación", "No. Cédula Profesional", "Fotografía (vest. Formal)", "Correo Personal", "Correo Institucional", "Extensión", "Vigencia de la TIA", "Fotografía de la TIA", "Licencia de Manejo", "Tipo de licencia", "Licencia Vigencia", "Fotografia de licencia", "Edad", "Cumpleaños", "Doc. Para ingreso")
    VALUES (NULL, 'VACANTE', 'VACANTE', NULL, '65E', 'N3', 'Dirección de Operación', 'Subdirección de Seguridad Operacional', 'Gerencia de Operaciones Parte Aeronáutica', 'Operador de Aerocares', 'Operador de Vehiculo Especializado', 'NO', 'NO', 'NO', 'NO', 'NO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
  END IF;
END $$;

-- [VACANTE 13] Plaza 105E
DO $$
BEGIN
  UPDATE public.agenda_2026
  SET
      "Nombre" = 'VACANTE',
      "Fecha de alta" = 'VACANTE',
      "Sueldo_Bruto" = NULL,
      "Plaza" = '105E',
      "Nivel" = 'N32',
      "Dir. Orgánica" = 'Dirección de Operación',
      "Subdir. Orgánica" = 'Subdirección de Ingeniería',
      "Gerencia Orgánica" = 'Gerencia de Operación y Manteniemiento de Instalaciones Hidráulicas',
      "Coordinación Orgánica" = '---',
      "Puesto" = 'Gerente de Área',
      "Personal Comisionado" = 'NO',
      "Dirección Comisionado" = 'NO',
      "Subdirección Comisionado" = 'NO',
      "Gerencia Comisionado" = 'NO',
      "Coordinación Comisionado" = 'NO',
      "Comentarios" = NULL,
      "Amonestaciones" = NULL,
      "Rúbrica" = NULL,
      "Anexo ""A"" Turno especial" = NULL,
      "Anexo ""A"" Fecha de activación" = NULL,
      "Anexo ""B"" Riesgos" = NULL,
      "Anexo ""B"" Fecha de activación" = NULL,
      "Antigüedad" = NULL,
      "Días de vacaciones disponibles" = NULL,
      "Fecha de nacimiento" = NULL,
      "Sexo" = NULL,
      "CURP" = NULL,
      "RFC" = NULL,
      "NSS" = NULL,
      "Vigencia de INE" = NULL,
      "Fotografia de INE" = NULL,
      "No. telefónico" = NULL,
      "Domicilio (calle, colonia, municipio, estado y código postal)" = NULL,
      "Persona Civil o Militar" = NULL,
      "Grado Militar" = NULL,
      "Personal en activo o retirado" = NULL,
      "Matrícula Militar" = NULL,
      "Estado civil" = NULL,
      "Dependientes (hijos)" = NULL,
      "RUSP" = NULL,
      "Tipo de sangre" = NULL,
      "Alérgico a algún medicamento Si ó No (Especificar)" = NULL,
      "Alérgico a algún alimento. Si ó No (Especificar)" = NULL,
      "Contacto de emergencia 1 Nombre completo" = NULL,
      "Parentesco 1" = NULL,
      "Teléfono de emergencia 1" = NULL,
      "Contacto de emergencia 2 Nombre completo" = NULL,
      "Parentesco 2" = NULL,
      "Teléfono de emergencia 2" = NULL,
      "Nivel de estudio" = NULL,
      "Nombre de la Licenciatura y/o Maestria" = NULL,
      "Grado Acad?mico" = NULL,
      "Estatus" = 'Baja',
      "Nombre de la Universidad" = NULL,
      "Año de Titulación" = NULL,
      "No. Cédula Profesional" = NULL,
      "Fotografía (vest. Formal)" = NULL,
      "Correo Personal" = NULL,
      "Correo Institucional" = NULL,
      "Extensión" = NULL,
      "Vigencia de la TIA" = NULL,
      "Fotografía de la TIA" = NULL,
      "Licencia de Manejo" = NULL,
      "Tipo de licencia" = NULL,
      "Licencia Vigencia" = NULL,
      "Fotografia de licencia" = NULL,
      "Edad" = NULL,
      "Cumpleaños" = NULL,
      "Doc. Para ingreso" = NULL
  WHERE ("No. Empleado" IS NULL OR btrim("No. Empleado"::text) = '')
    AND "Plaza"::text = '105E';

  IF NOT FOUND THEN
    INSERT INTO public.agenda_2026 ("No. Empleado", "Nombre", "Fecha de alta", "Sueldo_Bruto", "Plaza", "Nivel", "Dir. Orgánica", "Subdir. Orgánica", "Gerencia Orgánica", "Coordinación Orgánica", "Puesto", "Personal Comisionado", "Dirección Comisionado", "Subdirección Comisionado", "Gerencia Comisionado", "Coordinación Comisionado", "Comentarios", "Amonestaciones", "Rúbrica", "Anexo ""A"" Turno especial", "Anexo ""A"" Fecha de activación", "Anexo ""B"" Riesgos", "Anexo ""B"" Fecha de activación", "Antigüedad", "Días de vacaciones disponibles", "Fecha de nacimiento", "Sexo", "CURP", "RFC", "NSS", "Vigencia de INE", "Fotografia de INE", "No. telefónico", "Domicilio (calle, colonia, municipio, estado y código postal)", "Persona Civil o Militar", "Grado Militar", "Personal en activo o retirado", "Matrícula Militar", "Estado civil", "Dependientes (hijos)", "RUSP", "Tipo de sangre", "Alérgico a algún medicamento Si ó No (Especificar)", "Alérgico a algún alimento. Si ó No (Especificar)", "Contacto de emergencia 1 Nombre completo", "Parentesco 1", "Teléfono de emergencia 1", "Contacto de emergencia 2 Nombre completo", "Parentesco 2", "Teléfono de emergencia 2", "Nivel de estudio", "Nombre de la Licenciatura y/o Maestria", "Grado Acad?mico", "Estatus", "Nombre de la Universidad", "Año de Titulación", "No. Cédula Profesional", "Fotografía (vest. Formal)", "Correo Personal", "Correo Institucional", "Extensión", "Vigencia de la TIA", "Fotografía de la TIA", "Licencia de Manejo", "Tipo de licencia", "Licencia Vigencia", "Fotografia de licencia", "Edad", "Cumpleaños", "Doc. Para ingreso")
    VALUES (NULL, 'VACANTE', 'VACANTE', NULL, '105E', 'N32', 'Dirección de Operación', 'Subdirección de Ingeniería', 'Gerencia de Operación y Manteniemiento de Instalaciones Hidráulicas', '---', 'Gerente de Área', 'NO', 'NO', 'NO', 'NO', 'NO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
  END IF;
END $$;

-- 8) Consultas de verificaci?n posteriores
SELECT COUNT(*) AS total_registros FROM public.agenda_2026;
SELECT "Estatus", COUNT(*) AS total FROM public.agenda_2026 GROUP BY "Estatus" ORDER BY "Estatus";
SELECT "No. Empleado", COUNT(*) AS total
FROM public.agenda_2026
WHERE "No. Empleado" IS NOT NULL AND btrim("No. Empleado"::text) <> ''
GROUP BY "No. Empleado"
HAVING COUNT(*) > 1;
SELECT COUNT(*) AS colaboradores_excel_presentes
FROM public.agenda_2026
WHERE "No. Empleado"::text IN ('320', '1602', '1151', '754-2', '1020', '222', '990', '1686', '1305', '1537-2', '1224', '1064-2', '1135', '676', '1723', '95-2', '12-2´', '319-2', '1501', '654', '1369', '678', '52', '574', '1502', '713', '1477-2', '1468-2', '471', '206', '642', '18', '32', '1593', '1442', '1610', '245', '1559', '1067', '884', '1213', '847', '402', '525', '575', '48', '576', '1260', '655', '537', '1130', '23', '24', '1394-3', '26', '266', '1484', '543', '33', '944', '1043', '1411-2', '274', '1139', '674', '1466-3', '1551', '56-2', '1161', '669', '902', '1519', '1203', '31', '34', '35', '17', '1202', '1001', '538', '40', '41', '1254', '43', '289', '577', '927', '526', '1154', '204', '675', '579', '44', '1405', '46', '1600', '1639', '1503', '569', '51', '1467-3', '194', '565', '1486', '1304', '1320', '1504', '1677-2', '1606', '1289', '1724', '1443', '36', '1014', '916', '466', '1230', '261', '59', '663', '1255', '58', '1531', '1397-3', '61', '891', '20', '64', '946', '905', '1529', '1155', '1544-2', '1091', '1290', '1482', '62-2', '1558', '1679', '978', '1489-3', '22', '1015', '488', '57', '666', '1357', '1358', '1414-2', '49', '71', '72', '73', '582', '428', '521', '910', '1375-2', '429', '1370', '452', '493', '1157', '1081', '290', '1306', '504', '1460', '1376-2', '494', '1310', '688', '686', '1051', '1434', '1625', '257', '947', '197', '1588', '1229', '1123', '1698', '284', '207', '463', '764', '81', '510', '502', '1163', '724', '85', '755-2', '458', '477', '753', '250', '512', '932', '573', '751', '794', '1164', '487', '632', '408', '200-3', '677', '643', '1133', '1364', '953', '1106', '547', '1248', '1267', '1725', '513', '1603', '1444', '1612', '544', '1268', '249', '1092', '1398-2', '1441', '292', '1321', '1691', '1200', '583-2', '1615', '823', '1059', '1279', '744', '467', '1226', '363', '1322', '1237', '1147-2', '1227', '1057', '1685', '987', '1225', '1008', '461', '219', '1250', '991', '1204', '1607', '1483', '635', '255', '1118', '935', '660', '1292', '650', '943', '1044', '651', '518', '968', '1108', '1071', '1299-2', '359', '364', '1115-2', '963', '472', '1399-2', '976', '974', '801', '484', '710', '268', '302', '1435', '639', '609', '641', '1242', '659-3', '432-2', '1448', '491', '90', '1160', '456', '379', '1687', '1138', '873', '1635', '903', '942', '936', '696', '1378-2', '516', '819', '1295', '1452', '839', '1462', '478', '1712', '1011', '806', '804', '814', '1169', '959', '365', '247', '293', '1187', '515', '1617', '1506', '469', '728', '1211', '585', '809', '1522', '318', '1023', '1199', '539', '668', '981', '739', '1315', '1223', '94', '778', '1720', '55', '581', '1252', '1312', '54', '745', '1599', '1022', '1078', '1288', '227', '91-3', '1351-2', '1353-2', '1572-2', '1683', '1333-2', '1331-2', '1332-2', '1343-2', '1327-2', '1334-2', '1346-2', '1389-2', '1335-2', '1354-2', '1328-2', '1336-2', '1350-2', '1337-2', '1344-2', '1348-3', '1403-2', '1352-2', '1330-2', '1338-2', '1345-2', '1339-2', '1349-2', '1329-2', '1340-2', '1341-2', '1342-2', '60-2', '1665', '1553-2', '1457-2', '1459-2', '1660-2', '1541-2', '1542-2', '1526-2', '1417-2', '1413-2', '1440-2', '1670', '1647', '1699', '1701', '1706', '1666', '1697', '1451-2', '1630-2', '1415-2', '1525-2', '1648', '288-2', '1395-3', '1418-3', '1657', '1696', '703-3', '1212-2', '1649', '1621-2', '1563-2', '1564-2', '1565-2', '1695', '1377-2', '1730', '1667', '1732', '1469-2', '1470-2', '1661', '1580-2', '1652', '1731', '1439-2', '1715', '1618-2', '1643', '1663', '1614-2', '1436-2', '1458-2', '1555-2', '1510-2', '1543-2', '1664', '1400-2', '1396-3', '1708', '1719', '1727', '590', '1693', '1205', '1412-2', '1590-2', '986');

COMMIT;
