-- =============================================================================
-- 058 · Catálogo de aeronaves: tabla de equivalencias de AERONAVE
--
-- SÍNTOMA
--   La columna "AERONAVE" de los manifiestos mezcla tres cosas: códigos IATA
--   del itinerario (32N, 7M8), códigos ICAO tecleados (B738) y texto libre de
--   los Excel y del portal ("A-320", "A320 ", "B737-8MAX", "E-195", "C208B").
--   Muestra de junio 2026 (4,589 manifiestos): 31 escrituras distintas, ninguna
--   es un código IATA del catálogo.
--
-- CAUSA
--   El catálogo de modelos (data/master/aircraft type.csv) sólo traduce
--   códigos; el texto libre entra tal cual por la importación de Excel y por el
--   campo EQUIPO del portal, y nada registra a qué modelo corresponde.
--
-- QUÉ HACE
--   Crea public.catalogo_aeronaves_equivalencias: cada valor original
--   observado, el código canónico (IATA del catálogo / ICAO Doc 8643) cuando
--   hay evidencia, el estado (confirmado / pendiente), la evidencia y la
--   cantidad de registros en la muestra de junio 2026.
--     · NO modifica ningún manifiesto: el valor original se queda donde está.
--       La equivalencia sólo se usa al consultar (ver
--       scripts/diagnostico-catalogo-aeronaves.sql).
--     · Sólo las filas con estado = 'confirmado' deben usarse para traducir.
--       En las 'pendiente', codigo_iata/codigo_icao son PROPUESTAS sin validar.
--     · nivel: 'variante' = se sabe el código IATA exacto; 'tipo' = sólo se
--       sabe el ICAO (p. ej. A320-233 es A320ceo, pero no si es 320 o 32A);
--       'ninguno' = no se puede asignar sin revisar la matrícula.
--     · matricula: cuando la equivalencia sólo vale para una aeronave
--       (p. ej. "A340-800" en YV3535).
--   Fuentes: ICAO Doc 8643 (doc8643.icao.int, consultado 2026-10-06), FAA
--   Aircraft Registry (registry.faa.gov, 2026-10-06), EASA TCDS A.064.
--   Detalle y casos pendientes: docs/catalogo-aeronaves-revision.md
--
-- REQUIERE
--   008 (conci_catalogos_can_edit y conci_catalogos_set_updated_at).
--   No se pudo ejecutar contra una base al prepararla: correrla primero con
--   el ROLLBACK final, tal como indica el modo de uso.
--
-- MODO DE USO (igual que 036)
--   1) Correr el archivo completo tal cual. Termina en ROLLBACK: no persiste
--      nada. Revisar el bloque de VERIFICACIÓN del final.
--   2) Si se ve bien, cambiar la última línea ROLLBACK por COMMIT y volver a
--      correr el archivo completo.
--
-- REVERSA
--   La tabla es nueva y nada depende de ella:
--     DROP TABLE IF EXISTS public.catalogo_aeronaves_equivalencias;
-- =============================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS public.catalogo_aeronaves_equivalencias (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valor_original text NOT NULL,
    -- Llave de búsqueda: mayúsculas, sin espacios sobrantes. "A320 " y "A320"
    -- comparten llave pero se conservan como filas distintas (trazabilidad).
    valor_clave text GENERATED ALWAYS AS
        (upper(btrim(regexp_replace(valor_original, '\s+', ' ', 'g')))) STORED,
    matricula text,
    codigo_iata text,
    codigo_icao text,
    nivel text NOT NULL,
    tipo_problema text NOT NULL,
    estado text NOT NULL,
    evidencia text NOT NULL,
    fuentes text,
    registros_muestra_jun2026 integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT catalogo_aeronaves_equiv_estado_ck
        CHECK (estado IN ('confirmado', 'pendiente')),
    CONSTRAINT catalogo_aeronaves_equiv_nivel_ck
        CHECK (nivel IN ('variante', 'tipo', 'ninguno')),
    -- Un confirmado de nivel 'variante' trae IATA; uno de nivel 'tipo', ICAO.
    CONSTRAINT catalogo_aeronaves_equiv_confirmado_ck
        CHECK (estado <> 'confirmado'
               OR (nivel = 'variante' AND codigo_iata IS NOT NULL)
               OR (nivel = 'tipo' AND codigo_icao IS NOT NULL AND codigo_iata IS NULL)
               OR (nivel = 'ninguno' AND codigo_iata IS NULL AND codigo_icao IS NULL))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_catalogo_aeronaves_equiv_valor
    ON public.catalogo_aeronaves_equivalencias (valor_original, coalesce(matricula, ''));
CREATE INDEX IF NOT EXISTS idx_catalogo_aeronaves_equiv_clave
    ON public.catalogo_aeronaves_equivalencias (valor_clave);

COMMENT ON TABLE public.catalogo_aeronaves_equivalencias IS
    'Equivalencias de valores observados en "AERONAVE" de manifiestos hacia el catálogo '
    '(data/master/aircraft type.csv, IATA) y el ICAO Doc 8643. No modifica manifiestos. '
    'Sólo estado = confirmado debe usarse para traducir.';
COMMENT ON COLUMN public.catalogo_aeronaves_equivalencias.nivel IS
    'variante: código IATA exacto confirmado; tipo: sólo ICAO confirmado; ninguno: requiere revisar matrícula.';
COMMENT ON COLUMN public.catalogo_aeronaves_equivalencias.matricula IS
    'Si no es nulo, la equivalencia sólo aplica a esa matrícula (sin guiones ni espacios).';
COMMENT ON COLUMN public.catalogo_aeronaves_equivalencias.registros_muestra_jun2026 IS
    'Manifiestos con ese valor en la muestra de junio 2026 (supabase/migrations/jun2026_parts).';

-- Mismo patrón que los catálogos de Conciliación (008).
DROP TRIGGER IF EXISTS catalogo_aeronaves_equivalencias_updated_at
    ON public.catalogo_aeronaves_equivalencias;
CREATE TRIGGER catalogo_aeronaves_equivalencias_updated_at
    BEFORE UPDATE ON public.catalogo_aeronaves_equivalencias
    FOR EACH ROW EXECUTE FUNCTION public.conci_catalogos_set_updated_at();

ALTER TABLE public.catalogo_aeronaves_equivalencias ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS catalogo_aeronaves_equiv_read ON public.catalogo_aeronaves_equivalencias;
CREATE POLICY catalogo_aeronaves_equiv_read
    ON public.catalogo_aeronaves_equivalencias
    FOR SELECT TO authenticated
    USING (true);

DROP POLICY IF EXISTS catalogo_aeronaves_equiv_write ON public.catalogo_aeronaves_equivalencias;
CREATE POLICY catalogo_aeronaves_equiv_write
    ON public.catalogo_aeronaves_equivalencias
    FOR ALL TO authenticated
    USING (public.conci_catalogos_can_edit())
    WITH CHECK (public.conci_catalogos_can_edit());

GRANT SELECT ON TABLE public.catalogo_aeronaves_equivalencias TO authenticated;
GRANT INSERT, UPDATE, DELETE ON TABLE public.catalogo_aeronaves_equivalencias TO authenticated;
GRANT ALL ON TABLE public.catalogo_aeronaves_equivalencias TO service_role;

-- -----------------------------------------------------------------------------
-- Propuesta revisada. Fuentes abreviadas:
--   DOC8643 = https://doc8643.icao.int/external/aircrafttypes (2026-10-06)
--   FAA     = https://registry.faa.gov/AircraftInquiry (2026-10-06)
--   TCDS    = EASA TCDS A.064 (familia A318/A319/A320/A321, incluye neo)
-- -----------------------------------------------------------------------------
INSERT INTO public.catalogo_aeronaves_equivalencias
    (valor_original, matricula, codigo_iata, codigo_icao, nivel, tipo_problema, estado, evidencia, fuentes, registros_muestra_jun2026)
VALUES
    -- Confirmados: variante exacta (IATA del catálogo)
    ('A320-271N', NULL, '32N', 'A20N', 'variante', 'modelo_tecnico_en_lugar_de_codigo', 'confirmado',
     'A320-271N es A320neo (TCDS). FAA: N528VL–N533VL, N538VL, N539VL, N541VL y N552VL son A320-271N y aircraft.csv los tiene en 32N.',
     'TCDS; FAA; DOC8643', 124),
    ('A321-271NX', NULL, '32Q', 'A21N', 'variante', 'modelo_tecnico_en_lugar_de_codigo', 'confirmado',
     'A321-271NX es A321neo (TCDS); DOC8643 A21N = A-321neo; el catálogo usa 32Q para A321neo.',
     'TCDS; DOC8643', 10),
    ('A321-271N', NULL, '32Q', 'A21N', 'variante', 'modelo_tecnico_en_lugar_de_codigo', 'confirmado',
     'A321-271N es A321neo (TCDS). FAA: N534VL–N537VL, N542VL y N543VL son A321-271N; aircraft.csv los tiene en 32Q.',
     'TCDS; FAA; DOC8643', 1),
    ('A340-600', NULL, '346', 'A346', 'variante', 'nombre_en_lugar_de_codigo', 'confirmado',
     'Nombre idéntico al de la entrada 346 del catálogo; DOC8643 A346 = A-340-600.',
     'DOC8643', 6),
    ('A340-800', 'YV3535', '346', 'A346', 'variante', 'modelo_inexistente', 'confirmado',
     'No existe el A340-800 (no figura en DOC8643). YV3535 es A340-600: aircraft.csv (346), prensa aeronáutica y 6 de sus 8 manifiestos de junio. Sólo para esta matrícula.',
     'DOC8643; aircraft.csv; https://www.aviacionline.com/conviasa-takes-delivery-of-a-second-airbus-a340-600-from-mahan-air-and-programs-regular-flights-to-iran', 2),
    ('B737-8MAX', NULL, '7M8', 'B38M', 'variante', 'nombre_en_lugar_de_codigo', 'confirmado',
     'Boeing 737 MAX 8: DOC8643 B38M; entrada 7M8 del catálogo.', 'DOC8643', 14),
    ('B-737-8MAX', NULL, '7M8', 'B38M', 'variante', 'nombre_en_lugar_de_codigo', 'confirmado',
     'Igual que B737-8MAX con guion.', 'DOC8643', 1),
    ('B737-MAX8', NULL, '7M8', 'B38M', 'variante', 'nombre_en_lugar_de_codigo', 'confirmado',
     'Igual que B737-8MAX con otro orden.', 'DOC8643', 2),
    ('B737-9MAX', NULL, '7M9', 'B39M', 'variante', 'nombre_en_lugar_de_codigo', 'confirmado',
     'Boeing 737 MAX 9: DOC8643 B39M; entrada 7M9 del catálogo.', 'DOC8643', 21),
    ('B-737-9MAX', NULL, '7M9', 'B39M', 'variante', 'nombre_en_lugar_de_codigo', 'confirmado',
     'Igual que B737-9MAX con guion.', 'DOC8643', 1),
    ('YA', NULL, 'SF3', 'SF34', 'variante', 'codigo_de_operador_como_tipo', 'confirmado',
     '"YA" es el código del operador Berry Aviation (columna Aircraft Owner de aircraft.csv), no un tipo: los códigos IATA de tipo tienen 3 caracteres. La única aeronave que lo usaba, N3172, es SAAB 340B (FAA); DOC8643 SF34 = Saab 340. Se quitó la fila YA del catálogo.',
     'FAA; DOC8643', 0),

    -- Confirmados: sólo el tipo ICAO (la variante IATA queda abierta)
    ('A320-233', NULL, NULL, 'A320', 'tipo', 'modelo_tecnico_en_lugar_de_codigo', 'confirmado',
     'A320-233 es A320ceo (TCDS). FAA: N505VL–N527VL son A320-233. IATA abierto: 320 (A320) o 32A (A320 con sharklets).',
     'TCDS; FAA', 51),
    ('A321-231', NULL, NULL, 'A321', 'tipo', 'modelo_tecnico_en_lugar_de_codigo', 'confirmado',
     'A321-231 es A321ceo (TCDS); FAA N530FL es A321-231. El catálogo sólo tiene 321; no se fija IATA sin saber si tiene sharklets.',
     'TCDS; FAA', 2),
    ('B737-800', NULL, NULL, 'B738', 'tipo', 'nombre_en_lugar_de_codigo', 'confirmado',
     '737-800 = DOC8643 B738 (FAA N368AR y N377AR, 737-86J). IATA abierto: 738, 73H (winglets), 7S8 (scimitar) o 73K (carguero).',
     'DOC8643; FAA', 49),
    ('C208B', NULL, NULL, 'C208', 'tipo', 'nombre_en_lugar_de_codigo', 'confirmado',
     'Cessna 208B Grand Caravan: DOC8643 lo agrupa en C208. El catálogo tiene dos IATA para C208 (CNF "CESSNA 208B" y CES "CESSNA") sin validar contra SSIM.',
     'DOC8643', 147),

    -- Confirmado como inválido (sin equivalente)
    ('770', NULL, NULL, NULL, 'ninguno', 'registro_de_prueba', 'confirmado',
     'Fila "Test 770" del catálogo: sin ICAO, medidas 10/10/10 de relleno, no existe en DOC8643 ni en la lista IATA. Se quitó del catálogo; un "770" capturado queda marcado para revisión.',
     'DOC8643', 0),

    -- Pendientes: no se asignan automáticamente
    ('A320', NULL, NULL, NULL, 'ninguno', 'familia_sin_variante', 'pendiente',
     'Familia A320 sin ceo/neo. En la muestra se usa en A320ceo (FAA N509VL A320-233) y en A320neo (FAA N529VL A320-271N), así que no equivale al ICAO A320 (sólo ceo). Resolver por matrícula.',
     'FAA; aircraft.csv', 1103),
    ('A320 ', NULL, NULL, NULL, 'ninguno', 'familia_sin_variante_y_espacios', 'pendiente',
     'Igual que A320, con espacio sobrante.', 'FAA; aircraft.csv', 3),
    ('A-320', NULL, NULL, NULL, 'ninguno', 'familia_sin_variante_y_escritura', 'pendiente',
     'Igual que A320, con guion. FAA N528VL (A320-271N) y N291GX (A320-214) aparecen así.', 'FAA', 634),
    ('A321', NULL, NULL, NULL, 'ninguno', 'familia_sin_variante', 'pendiente',
     'Familia A321 sin ceo/neo: en aircraft.csv las matrículas capturadas así son 321 (ceo) y 32Q (neo). FAA N524VL (A320-233) también aparece como A321.',
     'FAA; aircraft.csv', 743),
    ('A321 ', NULL, NULL, NULL, 'ninguno', 'familia_sin_variante_y_espacios', 'pendiente',
     'Igual que A321, con espacio sobrante.', 'aircraft.csv', 2),
    ('A-321', NULL, NULL, NULL, 'ninguno', 'familia_sin_variante_y_escritura', 'pendiente',
     'Igual que A321, con guion. FAA N506VL (A320-233) aparece así: además de ambiguo, mal capturado.', 'FAA; aircraft.csv', 443),
    ('A320-271', NULL, '32N', 'A20N', 'ninguno', 'modelo_inexistente', 'pendiente',
     'No existe A320-271 sin sufijo N (TCDS); propuesta A320-271N truncado. Matrícula XATVB, cuyos otros registros dicen A-320 y A320-271N.',
     'TCDS', 1),
    ('E-195', NULL, NULL, NULL, 'ninguno', 'familia_sin_generacion', 'pendiente',
     'Embraer 195 sin generación: E1 = E195 (IATA E95), E2 = E295 (DOC8643). XA-MXA–MXE figuran como E-195/E2 en matriculas_manifiestos y como E95 en aircraft.csv. Falta el registro AFAC.',
     'DOC8643; matriculas_manifiestos; aircraft.csv', 635),
    ('E195', NULL, NULL, NULL, 'ninguno', 'familia_sin_generacion', 'pendiente',
     'Igual que E-195. Coincide con el ICAO E195 (sólo E1), pero se capturó en XA-MXA, que el catálogo de matrículas tiene como E2.',
     'DOC8643', 2),
    ('E-190', NULL, NULL, NULL, 'ninguno', 'familia_sin_generacion', 'pendiente',
     'Embraer 190 sin generación: E1 = E190 (IATA E90), E2 = E290 (DOC8643). También se capturó en XA-MXA–MXF, cuya mayoría de registros dice E-195.',
     'DOC8643', 508),
    ('E190', NULL, NULL, NULL, 'ninguno', 'familia_sin_generacion', 'pendiente',
     'Igual que E-190.', 'DOC8643', 1),
    ('B737-8', NULL, '7M8', 'B38M', 'ninguno', 'designacion_ambigua', 'pendiente',
     'Oficialmente "737-8" es el 737 MAX 8 (DOC8643 lo lista en B38M; FAA registra así N105JS y N868AM), pero en captura también se usa para el 737-800 (XAOOO aparece como B-737-8 y como B737-800). Propuesta 7M8; resolver por matrícula.',
     'DOC8643; FAA', 48),
    ('B-737-8', NULL, '7M8', 'B38M', 'ninguno', 'designacion_ambigua', 'pendiente',
     'Igual que B737-8, con guion.', 'DOC8643; FAA', 27),
    ('B737-80', NULL, NULL, NULL, 'ninguno', 'valor_truncado', 'pendiente',
     'Truncado: puede ser 737-800 o 737-8 (MAX 8). Matrículas HI1078 y HI1082, que aircraft.csv tiene como 7M8.',
     'aircraft.csv', 3),
    ('B37-800', NULL, NULL, 'B738', 'ninguno', 'error_de_escritura', 'pendiente',
     'Propuesta: B737-800 sin el 7. Matrícula XAADT, cuyos otros 5 registros dicen B737-800.',
     'muestra jun 2026', 1),
    ('B737', NULL, NULL, NULL, 'ninguno', 'familia_sin_variante', 'pendiente',
     'Familia 737 sin serie. No equivale al ICAO B737 (737-700): se usó para N377AR (FAA 737-86J, un 737-800) y N173AM (FAA 737-8, un MAX 8).',
     'FAA', 3),
    ('B-737', NULL, NULL, NULL, 'ninguno', 'familia_sin_variante', 'pendiente',
     'Igual que B737, con guion.', 'FAA', 1)
ON CONFLICT (valor_original, coalesce(matricula, '')) DO NOTHING;

-- La API reconoce la tabla nueva sin reiniciar.
NOTIFY pgrst, 'reload schema';

-- =============================================================================
-- VERIFICACIÓN (leer antes de cambiar ROLLBACK por COMMIT)
-- =============================================================================

-- 1) 33 filas: 16 confirmadas y 17 pendientes.
SELECT 'equivalencias por estado' AS reporte, estado, nivel, count(*) AS filas,
       sum(registros_muestra_jun2026) AS manifiestos_muestra
  FROM public.catalogo_aeronaves_equivalencias
 GROUP BY estado, nivel
 ORDER BY estado, nivel;

-- 2) La muestra de junio suma 4,589 manifiestos (31 valores observados).
SELECT 'muestra junio 2026' AS reporte, sum(registros_muestra_jun2026) AS manifiestos
  FROM public.catalogo_aeronaves_equivalencias;

-- 3) Ninguna clave normalizada tiene dos destinos confirmados distintos.
SELECT 'claves con destinos en conflicto (debe salir vacío)' AS reporte, valor_clave, matricula
  FROM public.catalogo_aeronaves_equivalencias
 WHERE estado = 'confirmado'
 GROUP BY valor_clave, matricula
HAVING count(DISTINCT (coalesce(codigo_iata, ''), coalesce(codigo_icao, ''))) > 1;

-- -----------------------------------------------------------------------------
-- Cambiar por COMMIT cuando la verificación se vea bien.
-- -----------------------------------------------------------------------------
ROLLBACK;
