-- ================================================================
-- agenda_2026 actualizaci?n controlada - lote 10
-- Registros 451 al 459 de 459
-- No contiene DROP, DELETE ni TRUNCATE.
-- ================================================================
BEGIN;

-- [451] 1708 | Eugenio Alonso
INSERT INTO public.agenda_2026 (
  "No. Empleado",
  "Nombre",
  "Fecha de alta",
  "Sueldo_Bruto",
  "Plaza",
  "Nivel",
  "Dir. Orgánica",
  "Subdir. Orgánica",
  "Gerencia Orgánica",
  "Coordinación Orgánica",
  "Puesto",
  "Personal Comisionado",
  "Dirección Comisionado",
  "Subdirección Comisionado",
  "Gerencia Comisionado",
  "Coordinación Comisionado",
  "Comentarios",
  "Amonestaciones",
  "Rúbrica",
  "Anexo ""A"" Turno especial",
  "Anexo ""A"" Fecha de activación",
  "Anexo ""B"" Riesgos",
  "Anexo ""B"" Fecha de activación",
  "Antigüedad",
  "Días de vacaciones disponibles",
  "Fecha de nacimiento",
  "Sexo",
  "CURP",
  "RFC",
  "NSS",
  "Vigencia de INE",
  "Fotografia de INE",
  "No. telefónico",
  "Domicilio (calle, colonia, municipio, estado y código postal)",
  "Persona Civil o Militar",
  "Grado Militar",
  "Personal en activo o retirado",
  "Matrícula Militar",
  "Estado civil",
  "Dependientes (hijos)",
  "RUSP",
  "Tipo de sangre",
  "Alérgico a algún medicamento Si ó No (Especificar)",
  "Alérgico a algún alimento. Si ó No (Especificar)",
  "Contacto de emergencia 1 Nombre completo",
  "Parentesco 1",
  "Teléfono de emergencia 1",
  "Contacto de emergencia 2 Nombre completo",
  "Parentesco 2",
  "Teléfono de emergencia 2",
  "Nivel de estudio",
  "Nombre de la Licenciatura y/o Maestria",
  "Nombre de la Universidad",
  "Año de Titulación",
  "No. Cédula Profesional",
  "Fotografía (vest. Formal)",
  "Correo Personal",
  "Correo Institucional",
  "Extensión",
  "Vigencia de la TIA",
  "Fotografía de la TIA",
  "Licencia de Manejo",
  "Tipo de licencia",
  "Licencia Vigencia",
  "Fotografia de licencia",
  "Edad",
  "Cumpleaños",
  "Doc. Para ingreso"
) VALUES (
  '1708',
  'Eugenio Alonso',
  '2026-04-23',
  NULL,
  '115E',
  'N6',
  'Dirección de Operación',
  'Subdirección de Servicios Conexos',
  'Gerencia de Aviación General',
  '---',
  'Profesional de Operaciones Aeroportuarias',
  '1',
  'Dir. Admón.',
  'Subdirección de Recursos Materiales',
  'Gerencia de Recursos Materiales',
  '0',
  '0',
  '0',
  '0',
  '0',
  NULL,
  'RyR',
  '2026-04-23',
  '0',
  '0',
  NULL,
  'Masculino',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  'Civil',
  NULL,
  NULL,
  '0',
  '0',
  '0',
  NULL,
  '0',
  'No',
  'No',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  NULL,
  '0',
  '0',
  '0',
  NULL,
  '0',
  '0',
  NULL,
  'Ingresa comisionado'
) ON CONFLICT ("No. Empleado") DO UPDATE SET
  "Nombre" = COALESCE(EXCLUDED."Nombre", public.agenda_2026."Nombre"),
  "Fecha de alta" = COALESCE(EXCLUDED."Fecha de alta", public.agenda_2026."Fecha de alta"),
  "Sueldo_Bruto" = COALESCE(EXCLUDED."Sueldo_Bruto", public.agenda_2026."Sueldo_Bruto"),
  "Plaza" = COALESCE(EXCLUDED."Plaza", public.agenda_2026."Plaza"),
  "Nivel" = COALESCE(EXCLUDED."Nivel", public.agenda_2026."Nivel"),
  "Dir. Orgánica" = COALESCE(EXCLUDED."Dir. Orgánica", public.agenda_2026."Dir. Orgánica"),
  "Subdir. Orgánica" = COALESCE(EXCLUDED."Subdir. Orgánica", public.agenda_2026."Subdir. Orgánica"),
  "Gerencia Orgánica" = COALESCE(EXCLUDED."Gerencia Orgánica", public.agenda_2026."Gerencia Orgánica"),
  "Coordinación Orgánica" = COALESCE(EXCLUDED."Coordinación Orgánica", public.agenda_2026."Coordinación Orgánica"),
  "Puesto" = COALESCE(EXCLUDED."Puesto", public.agenda_2026."Puesto"),
  "Personal Comisionado" = COALESCE(EXCLUDED."Personal Comisionado", public.agenda_2026."Personal Comisionado"),
  "Dirección Comisionado" = COALESCE(EXCLUDED."Dirección Comisionado", public.agenda_2026."Dirección Comisionado"),
  "Subdirección Comisionado" = COALESCE(EXCLUDED."Subdirección Comisionado", public.agenda_2026."Subdirección Comisionado"),
  "Gerencia Comisionado" = COALESCE(EXCLUDED."Gerencia Comisionado", public.agenda_2026."Gerencia Comisionado"),
  "Coordinación Comisionado" = COALESCE(EXCLUDED."Coordinación Comisionado", public.agenda_2026."Coordinación Comisionado"),
  "Comentarios" = COALESCE(EXCLUDED."Comentarios", public.agenda_2026."Comentarios"),
  "Amonestaciones" = COALESCE(EXCLUDED."Amonestaciones", public.agenda_2026."Amonestaciones"),
  "Rúbrica" = COALESCE(EXCLUDED."Rúbrica", public.agenda_2026."Rúbrica"),
  "Anexo ""A"" Turno especial" = COALESCE(EXCLUDED."Anexo ""A"" Turno especial", public.agenda_2026."Anexo ""A"" Turno especial"),
  "Anexo ""A"" Fecha de activación" = COALESCE(EXCLUDED."Anexo ""A"" Fecha de activación", public.agenda_2026."Anexo ""A"" Fecha de activación"),
  "Anexo ""B"" Riesgos" = COALESCE(EXCLUDED."Anexo ""B"" Riesgos", public.agenda_2026."Anexo ""B"" Riesgos"),
  "Anexo ""B"" Fecha de activación" = COALESCE(EXCLUDED."Anexo ""B"" Fecha de activación", public.agenda_2026."Anexo ""B"" Fecha de activación"),
  "Antigüedad" = COALESCE(EXCLUDED."Antigüedad", public.agenda_2026."Antigüedad"),
  "Días de vacaciones disponibles" = COALESCE(EXCLUDED."Días de vacaciones disponibles", public.agenda_2026."Días de vacaciones disponibles"),
  "Fecha de nacimiento" = COALESCE(EXCLUDED."Fecha de nacimiento", public.agenda_2026."Fecha de nacimiento"),
  "Sexo" = COALESCE(EXCLUDED."Sexo", public.agenda_2026."Sexo"),
  "CURP" = COALESCE(EXCLUDED."CURP", public.agenda_2026."CURP"),
  "RFC" = COALESCE(EXCLUDED."RFC", public.agenda_2026."RFC"),
  "NSS" = COALESCE(EXCLUDED."NSS", public.agenda_2026."NSS"),
  "Vigencia de INE" = COALESCE(EXCLUDED."Vigencia de INE", public.agenda_2026."Vigencia de INE"),
  "Fotografia de INE" = COALESCE(EXCLUDED."Fotografia de INE", public.agenda_2026."Fotografia de INE"),
  "No. telefónico" = COALESCE(EXCLUDED."No. telefónico", public.agenda_2026."No. telefónico"),
  "Domicilio (calle, colonia, municipio, estado y código postal)" = COALESCE(EXCLUDED."Domicilio (calle, colonia, municipio, estado y código postal)", public.agenda_2026."Domicilio (calle, colonia, municipio, estado y código postal)"),
  "Persona Civil o Militar" = COALESCE(EXCLUDED."Persona Civil o Militar", public.agenda_2026."Persona Civil o Militar"),
  "Grado Militar" = COALESCE(EXCLUDED."Grado Militar", public.agenda_2026."Grado Militar"),
  "Personal en activo o retirado" = COALESCE(EXCLUDED."Personal en activo o retirado", public.agenda_2026."Personal en activo o retirado"),
  "Matrícula Militar" = COALESCE(EXCLUDED."Matrícula Militar", public.agenda_2026."Matrícula Militar"),
  "Estado civil" = COALESCE(EXCLUDED."Estado civil", public.agenda_2026."Estado civil"),
  "Dependientes (hijos)" = COALESCE(EXCLUDED."Dependientes (hijos)", public.agenda_2026."Dependientes (hijos)"),
  "RUSP" = COALESCE(EXCLUDED."RUSP", public.agenda_2026."RUSP"),
  "Tipo de sangre" = COALESCE(EXCLUDED."Tipo de sangre", public.agenda_2026."Tipo de sangre"),
  "Alérgico a algún medicamento Si ó No (Especificar)" = COALESCE(EXCLUDED."Alérgico a algún medicamento Si ó No (Especificar)", public.agenda_2026."Alérgico a algún medicamento Si ó No (Especificar)"),
  "Alérgico a algún alimento. Si ó No (Especificar)" = COALESCE(EXCLUDED."Alérgico a algún alimento. Si ó No (Especificar)", public.agenda_2026."Alérgico a algún alimento. Si ó No (Especificar)"),
  "Contacto de emergencia 1 Nombre completo" = COALESCE(EXCLUDED."Contacto de emergencia 1 Nombre completo", public.agenda_2026."Contacto de emergencia 1 Nombre completo"),
  "Parentesco 1" = COALESCE(EXCLUDED."Parentesco 1", public.agenda_2026."Parentesco 1"),
  "Teléfono de emergencia 1" = COALESCE(EXCLUDED."Teléfono de emergencia 1", public.agenda_2026."Teléfono de emergencia 1"),
  "Contacto de emergencia 2 Nombre completo" = COALESCE(EXCLUDED."Contacto de emergencia 2 Nombre completo", public.agenda_2026."Contacto de emergencia 2 Nombre completo"),
  "Parentesco 2" = COALESCE(EXCLUDED."Parentesco 2", public.agenda_2026."Parentesco 2"),
  "Teléfono de emergencia 2" = COALESCE(EXCLUDED."Teléfono de emergencia 2", public.agenda_2026."Teléfono de emergencia 2"),
  "Nivel de estudio" = COALESCE(EXCLUDED."Nivel de estudio", public.agenda_2026."Nivel de estudio"),
  "Nombre de la Licenciatura y/o Maestria" = COALESCE(EXCLUDED."Nombre de la Licenciatura y/o Maestria", public.agenda_2026."Nombre de la Licenciatura y/o Maestria"),
  "Nombre de la Universidad" = COALESCE(EXCLUDED."Nombre de la Universidad", public.agenda_2026."Nombre de la Universidad"),
  "Año de Titulación" = COALESCE(EXCLUDED."Año de Titulación", public.agenda_2026."Año de Titulación"),
  "No. Cédula Profesional" = COALESCE(EXCLUDED."No. Cédula Profesional", public.agenda_2026."No. Cédula Profesional"),
  "Fotografía (vest. Formal)" = COALESCE(EXCLUDED."Fotografía (vest. Formal)", public.agenda_2026."Fotografía (vest. Formal)"),
  "Correo Personal" = COALESCE(EXCLUDED."Correo Personal", public.agenda_2026."Correo Personal"),
  "Correo Institucional" = COALESCE(EXCLUDED."Correo Institucional", public.agenda_2026."Correo Institucional"),
  "Extensión" = COALESCE(EXCLUDED."Extensión", public.agenda_2026."Extensión"),
  "Vigencia de la TIA" = COALESCE(EXCLUDED."Vigencia de la TIA", public.agenda_2026."Vigencia de la TIA"),
  "Fotografía de la TIA" = COALESCE(EXCLUDED."Fotografía de la TIA", public.agenda_2026."Fotografía de la TIA"),
  "Licencia de Manejo" = COALESCE(EXCLUDED."Licencia de Manejo", public.agenda_2026."Licencia de Manejo"),
  "Tipo de licencia" = COALESCE(EXCLUDED."Tipo de licencia", public.agenda_2026."Tipo de licencia"),
  "Licencia Vigencia" = COALESCE(EXCLUDED."Licencia Vigencia", public.agenda_2026."Licencia Vigencia"),
  "Fotografia de licencia" = COALESCE(EXCLUDED."Fotografia de licencia", public.agenda_2026."Fotografia de licencia"),
  "Edad" = COALESCE(EXCLUDED."Edad", public.agenda_2026."Edad"),
  "Cumpleaños" = COALESCE(EXCLUDED."Cumpleaños", public.agenda_2026."Cumpleaños"),
  "Doc. Para ingreso" = COALESCE(EXCLUDED."Doc. Para ingreso", public.agenda_2026."Doc. Para ingreso");

-- [452] 1719 | Guillermo Jiménez Varela
INSERT INTO public.agenda_2026 (
  "No. Empleado",
  "Nombre",
  "Fecha de alta",
  "Sueldo_Bruto",
  "Plaza",
  "Nivel",
  "Dir. Orgánica",
  "Subdir. Orgánica",
  "Gerencia Orgánica",
  "Coordinación Orgánica",
  "Puesto",
  "Personal Comisionado",
  "Dirección Comisionado",
  "Subdirección Comisionado",
  "Gerencia Comisionado",
  "Coordinación Comisionado",
  "Comentarios",
  "Amonestaciones",
  "Rúbrica",
  "Anexo ""A"" Turno especial",
  "Anexo ""A"" Fecha de activación",
  "Anexo ""B"" Riesgos",
  "Anexo ""B"" Fecha de activación",
  "Antigüedad",
  "Días de vacaciones disponibles",
  "Fecha de nacimiento",
  "Sexo",
  "CURP",
  "RFC",
  "NSS",
  "Vigencia de INE",
  "Fotografia de INE",
  "No. telefónico",
  "Domicilio (calle, colonia, municipio, estado y código postal)",
  "Persona Civil o Militar",
  "Grado Militar",
  "Personal en activo o retirado",
  "Matrícula Militar",
  "Estado civil",
  "Dependientes (hijos)",
  "RUSP",
  "Tipo de sangre",
  "Alérgico a algún medicamento Si ó No (Especificar)",
  "Alérgico a algún alimento. Si ó No (Especificar)",
  "Contacto de emergencia 1 Nombre completo",
  "Parentesco 1",
  "Teléfono de emergencia 1",
  "Contacto de emergencia 2 Nombre completo",
  "Parentesco 2",
  "Teléfono de emergencia 2",
  "Nivel de estudio",
  "Nombre de la Licenciatura y/o Maestria",
  "Nombre de la Universidad",
  "Año de Titulación",
  "No. Cédula Profesional",
  "Fotografía (vest. Formal)",
  "Correo Personal",
  "Correo Institucional",
  "Extensión",
  "Vigencia de la TIA",
  "Fotografía de la TIA",
  "Licencia de Manejo",
  "Tipo de licencia",
  "Licencia Vigencia",
  "Fotografia de licencia",
  "Edad",
  "Cumpleaños",
  "Doc. Para ingreso"
) VALUES (
  '1719',
  'Guillermo Jiménez Varela',
  '2026-05-07',
  NULL,
  '116E',
  'N5',
  'Dirección de Operación',
  'Subdirección de Servicios Conexos',
  'Gerencia de Aviación General',
  '---',
  'Supervisor de Seguridad Aeroportuaria',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  'GJV',
  NULL,
  NULL,
  NULL,
  NULL,
  '0',
  '0',
  '1992-01-26',
  'Masculino',
  'JIVG920126HPLMRL04',
  'JIVG920126E36',
  '16169280530',
  '2030',
  NULL,
  '222 781 5291',
  'Paseo del Bosque M17 LT3 VIV11 Bosque Tabachines, Hacienda del Bosque, Tecámac, Estado de México. C.P. 5574',
  'Civil',
  NULL,
  NULL,
  NULL,
  'Soltero',
  '0',
  NULL,
  'O+',
  'No',
  'No',
  'Verónica Jiménez Varela',
  'Madre',
  '23 8393 8964',
  'Rodolfo Flores Jiménez',
  'Hermano',
  '23 8194 5913',
  'Superior',
  'Ingeniería Civil',
  'Benemérita Universidad Autónoma de Puebla',
  'En trámite',
  '0',
  NULL,
  'wsuitemx@gmail.com',
  'gjimenezv@aifa.aero',
  '20085',
  '2028-05-12',
  NULL,
  'No',
  NULL,
  NULL,
  NULL,
  '0',
  NULL,
  '0'
) ON CONFLICT ("No. Empleado") DO UPDATE SET
  "Nombre" = COALESCE(EXCLUDED."Nombre", public.agenda_2026."Nombre"),
  "Fecha de alta" = COALESCE(EXCLUDED."Fecha de alta", public.agenda_2026."Fecha de alta"),
  "Sueldo_Bruto" = COALESCE(EXCLUDED."Sueldo_Bruto", public.agenda_2026."Sueldo_Bruto"),
  "Plaza" = COALESCE(EXCLUDED."Plaza", public.agenda_2026."Plaza"),
  "Nivel" = COALESCE(EXCLUDED."Nivel", public.agenda_2026."Nivel"),
  "Dir. Orgánica" = COALESCE(EXCLUDED."Dir. Orgánica", public.agenda_2026."Dir. Orgánica"),
  "Subdir. Orgánica" = COALESCE(EXCLUDED."Subdir. Orgánica", public.agenda_2026."Subdir. Orgánica"),
  "Gerencia Orgánica" = COALESCE(EXCLUDED."Gerencia Orgánica", public.agenda_2026."Gerencia Orgánica"),
  "Coordinación Orgánica" = COALESCE(EXCLUDED."Coordinación Orgánica", public.agenda_2026."Coordinación Orgánica"),
  "Puesto" = COALESCE(EXCLUDED."Puesto", public.agenda_2026."Puesto"),
  "Personal Comisionado" = COALESCE(EXCLUDED."Personal Comisionado", public.agenda_2026."Personal Comisionado"),
  "Dirección Comisionado" = COALESCE(EXCLUDED."Dirección Comisionado", public.agenda_2026."Dirección Comisionado"),
  "Subdirección Comisionado" = COALESCE(EXCLUDED."Subdirección Comisionado", public.agenda_2026."Subdirección Comisionado"),
  "Gerencia Comisionado" = COALESCE(EXCLUDED."Gerencia Comisionado", public.agenda_2026."Gerencia Comisionado"),
  "Coordinación Comisionado" = COALESCE(EXCLUDED."Coordinación Comisionado", public.agenda_2026."Coordinación Comisionado"),
  "Comentarios" = COALESCE(EXCLUDED."Comentarios", public.agenda_2026."Comentarios"),
  "Amonestaciones" = COALESCE(EXCLUDED."Amonestaciones", public.agenda_2026."Amonestaciones"),
  "Rúbrica" = COALESCE(EXCLUDED."Rúbrica", public.agenda_2026."Rúbrica"),
  "Anexo ""A"" Turno especial" = COALESCE(EXCLUDED."Anexo ""A"" Turno especial", public.agenda_2026."Anexo ""A"" Turno especial"),
  "Anexo ""A"" Fecha de activación" = COALESCE(EXCLUDED."Anexo ""A"" Fecha de activación", public.agenda_2026."Anexo ""A"" Fecha de activación"),
  "Anexo ""B"" Riesgos" = COALESCE(EXCLUDED."Anexo ""B"" Riesgos", public.agenda_2026."Anexo ""B"" Riesgos"),
  "Anexo ""B"" Fecha de activación" = COALESCE(EXCLUDED."Anexo ""B"" Fecha de activación", public.agenda_2026."Anexo ""B"" Fecha de activación"),
  "Antigüedad" = COALESCE(EXCLUDED."Antigüedad", public.agenda_2026."Antigüedad"),
  "Días de vacaciones disponibles" = COALESCE(EXCLUDED."Días de vacaciones disponibles", public.agenda_2026."Días de vacaciones disponibles"),
  "Fecha de nacimiento" = COALESCE(EXCLUDED."Fecha de nacimiento", public.agenda_2026."Fecha de nacimiento"),
  "Sexo" = COALESCE(EXCLUDED."Sexo", public.agenda_2026."Sexo"),
  "CURP" = COALESCE(EXCLUDED."CURP", public.agenda_2026."CURP"),
  "RFC" = COALESCE(EXCLUDED."RFC", public.agenda_2026."RFC"),
  "NSS" = COALESCE(EXCLUDED."NSS", public.agenda_2026."NSS"),
  "Vigencia de INE" = COALESCE(EXCLUDED."Vigencia de INE", public.agenda_2026."Vigencia de INE"),
  "Fotografia de INE" = COALESCE(EXCLUDED."Fotografia de INE", public.agenda_2026."Fotografia de INE"),
  "No. telefónico" = COALESCE(EXCLUDED."No. telefónico", public.agenda_2026."No. telefónico"),
  "Domicilio (calle, colonia, municipio, estado y código postal)" = COALESCE(EXCLUDED."Domicilio (calle, colonia, municipio, estado y código postal)", public.agenda_2026."Domicilio (calle, colonia, municipio, estado y código postal)"),
  "Persona Civil o Militar" = COALESCE(EXCLUDED."Persona Civil o Militar", public.agenda_2026."Persona Civil o Militar"),
  "Grado Militar" = COALESCE(EXCLUDED."Grado Militar", public.agenda_2026."Grado Militar"),
  "Personal en activo o retirado" = COALESCE(EXCLUDED."Personal en activo o retirado", public.agenda_2026."Personal en activo o retirado"),
  "Matrícula Militar" = COALESCE(EXCLUDED."Matrícula Militar", public.agenda_2026."Matrícula Militar"),
  "Estado civil" = COALESCE(EXCLUDED."Estado civil", public.agenda_2026."Estado civil"),
  "Dependientes (hijos)" = COALESCE(EXCLUDED."Dependientes (hijos)", public.agenda_2026."Dependientes (hijos)"),
  "RUSP" = COALESCE(EXCLUDED."RUSP", public.agenda_2026."RUSP"),
  "Tipo de sangre" = COALESCE(EXCLUDED."Tipo de sangre", public.agenda_2026."Tipo de sangre"),
  "Alérgico a algún medicamento Si ó No (Especificar)" = COALESCE(EXCLUDED."Alérgico a algún medicamento Si ó No (Especificar)", public.agenda_2026."Alérgico a algún medicamento Si ó No (Especificar)"),
  "Alérgico a algún alimento. Si ó No (Especificar)" = COALESCE(EXCLUDED."Alérgico a algún alimento. Si ó No (Especificar)", public.agenda_2026."Alérgico a algún alimento. Si ó No (Especificar)"),
  "Contacto de emergencia 1 Nombre completo" = COALESCE(EXCLUDED."Contacto de emergencia 1 Nombre completo", public.agenda_2026."Contacto de emergencia 1 Nombre completo"),
  "Parentesco 1" = COALESCE(EXCLUDED."Parentesco 1", public.agenda_2026."Parentesco 1"),
  "Teléfono de emergencia 1" = COALESCE(EXCLUDED."Teléfono de emergencia 1", public.agenda_2026."Teléfono de emergencia 1"),
  "Contacto de emergencia 2 Nombre completo" = COALESCE(EXCLUDED."Contacto de emergencia 2 Nombre completo", public.agenda_2026."Contacto de emergencia 2 Nombre completo"),
  "Parentesco 2" = COALESCE(EXCLUDED."Parentesco 2", public.agenda_2026."Parentesco 2"),
  "Teléfono de emergencia 2" = COALESCE(EXCLUDED."Teléfono de emergencia 2", public.agenda_2026."Teléfono de emergencia 2"),
  "Nivel de estudio" = COALESCE(EXCLUDED."Nivel de estudio", public.agenda_2026."Nivel de estudio"),
  "Nombre de la Licenciatura y/o Maestria" = COALESCE(EXCLUDED."Nombre de la Licenciatura y/o Maestria", public.agenda_2026."Nombre de la Licenciatura y/o Maestria"),
  "Nombre de la Universidad" = COALESCE(EXCLUDED."Nombre de la Universidad", public.agenda_2026."Nombre de la Universidad"),
  "Año de Titulación" = COALESCE(EXCLUDED."Año de Titulación", public.agenda_2026."Año de Titulación"),
  "No. Cédula Profesional" = COALESCE(EXCLUDED."No. Cédula Profesional", public.agenda_2026."No. Cédula Profesional"),
  "Fotografía (vest. Formal)" = COALESCE(EXCLUDED."Fotografía (vest. Formal)", public.agenda_2026."Fotografía (vest. Formal)"),
  "Correo Personal" = COALESCE(EXCLUDED."Correo Personal", public.agenda_2026."Correo Personal"),
  "Correo Institucional" = COALESCE(EXCLUDED."Correo Institucional", public.agenda_2026."Correo Institucional"),
  "Extensión" = COALESCE(EXCLUDED."Extensión", public.agenda_2026."Extensión"),
  "Vigencia de la TIA" = COALESCE(EXCLUDED."Vigencia de la TIA", public.agenda_2026."Vigencia de la TIA"),
  "Fotografía de la TIA" = COALESCE(EXCLUDED."Fotografía de la TIA", public.agenda_2026."Fotografía de la TIA"),
  "Licencia de Manejo" = COALESCE(EXCLUDED."Licencia de Manejo", public.agenda_2026."Licencia de Manejo"),
  "Tipo de licencia" = COALESCE(EXCLUDED."Tipo de licencia", public.agenda_2026."Tipo de licencia"),
  "Licencia Vigencia" = COALESCE(EXCLUDED."Licencia Vigencia", public.agenda_2026."Licencia Vigencia"),
  "Fotografia de licencia" = COALESCE(EXCLUDED."Fotografia de licencia", public.agenda_2026."Fotografia de licencia"),
  "Edad" = COALESCE(EXCLUDED."Edad", public.agenda_2026."Edad"),
  "Cumpleaños" = COALESCE(EXCLUDED."Cumpleaños", public.agenda_2026."Cumpleaños"),
  "Doc. Para ingreso" = COALESCE(EXCLUDED."Doc. Para ingreso", public.agenda_2026."Doc. Para ingreso");

-- [453] 1727 | Sammantha Delgado Serrano
INSERT INTO public.agenda_2026 (
  "No. Empleado",
  "Nombre",
  "Fecha de alta",
  "Sueldo_Bruto",
  "Plaza",
  "Nivel",
  "Dir. Orgánica",
  "Subdir. Orgánica",
  "Gerencia Orgánica",
  "Coordinación Orgánica",
  "Puesto",
  "Personal Comisionado",
  "Dirección Comisionado",
  "Subdirección Comisionado",
  "Gerencia Comisionado",
  "Coordinación Comisionado",
  "Comentarios",
  "Amonestaciones",
  "Rúbrica",
  "Anexo ""A"" Turno especial",
  "Anexo ""A"" Fecha de activación",
  "Anexo ""B"" Riesgos",
  "Anexo ""B"" Fecha de activación",
  "Antigüedad",
  "Días de vacaciones disponibles",
  "Fecha de nacimiento",
  "Sexo",
  "CURP",
  "RFC",
  "NSS",
  "Vigencia de INE",
  "Fotografia de INE",
  "No. telefónico",
  "Domicilio (calle, colonia, municipio, estado y código postal)",
  "Persona Civil o Militar",
  "Grado Militar",
  "Personal en activo o retirado",
  "Matrícula Militar",
  "Estado civil",
  "Dependientes (hijos)",
  "RUSP",
  "Tipo de sangre",
  "Alérgico a algún medicamento Si ó No (Especificar)",
  "Alérgico a algún alimento. Si ó No (Especificar)",
  "Contacto de emergencia 1 Nombre completo",
  "Parentesco 1",
  "Teléfono de emergencia 1",
  "Contacto de emergencia 2 Nombre completo",
  "Parentesco 2",
  "Teléfono de emergencia 2",
  "Nivel de estudio",
  "Nombre de la Licenciatura y/o Maestria",
  "Nombre de la Universidad",
  "Año de Titulación",
  "No. Cédula Profesional",
  "Fotografía (vest. Formal)",
  "Correo Personal",
  "Correo Institucional",
  "Extensión",
  "Vigencia de la TIA",
  "Fotografía de la TIA",
  "Licencia de Manejo",
  "Tipo de licencia",
  "Licencia Vigencia",
  "Fotografia de licencia",
  "Edad",
  "Cumpleaños",
  "Doc. Para ingreso"
) VALUES (
  '1727',
  'Sammantha Delgado Serrano',
  '2026-05-21',
  NULL,
  '117E',
  'N5',
  'Dirección de Operación',
  'Subdirección de Servicios Conexos',
  'Gerencia de Aviación General',
  '---',
  'Supervisor de Seguridad Aeroportuaria',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  'SDS',
  NULL,
  NULL,
  NULL,
  NULL,
  '0',
  '0',
  '1999-09-25',
  'Femenino',
  'DESS990925MMCLRM07',
  'DESS990925FW4',
  '75169939974',
  '2027',
  NULL,
  '55 4267 7061',
  'Calle la Merced, Colonia La Palma, Reyes Acozac,Tecámac,  Estado de México, C.P. 55755',
  'Civil',
  NULL,
  NULL,
  NULL,
  'Soltero(a)',
  '0',
  NULL,
  'O+',
  'No',
  'No',
  'Rosario Serrano Sanchez',
  'Madre',
  '55 3312 7705',
  'Ximena Delgado Serrano',
  'Hermana',
  '55 3846 6359',
  'Superior',
  'Licenciatura en contaduria',
  'Centro Universitario UAEM Zumpango',
  '2021',
  '12961211',
  NULL,
  'sammanthaserrano@gmail.com',
  '0',
  '0',
  '2028-05-22',
  NULL,
  'No',
  NULL,
  NULL,
  NULL,
  '0',
  NULL,
  '0'
) ON CONFLICT ("No. Empleado") DO UPDATE SET
  "Nombre" = COALESCE(EXCLUDED."Nombre", public.agenda_2026."Nombre"),
  "Fecha de alta" = COALESCE(EXCLUDED."Fecha de alta", public.agenda_2026."Fecha de alta"),
  "Sueldo_Bruto" = COALESCE(EXCLUDED."Sueldo_Bruto", public.agenda_2026."Sueldo_Bruto"),
  "Plaza" = COALESCE(EXCLUDED."Plaza", public.agenda_2026."Plaza"),
  "Nivel" = COALESCE(EXCLUDED."Nivel", public.agenda_2026."Nivel"),
  "Dir. Orgánica" = COALESCE(EXCLUDED."Dir. Orgánica", public.agenda_2026."Dir. Orgánica"),
  "Subdir. Orgánica" = COALESCE(EXCLUDED."Subdir. Orgánica", public.agenda_2026."Subdir. Orgánica"),
  "Gerencia Orgánica" = COALESCE(EXCLUDED."Gerencia Orgánica", public.agenda_2026."Gerencia Orgánica"),
  "Coordinación Orgánica" = COALESCE(EXCLUDED."Coordinación Orgánica", public.agenda_2026."Coordinación Orgánica"),
  "Puesto" = COALESCE(EXCLUDED."Puesto", public.agenda_2026."Puesto"),
  "Personal Comisionado" = COALESCE(EXCLUDED."Personal Comisionado", public.agenda_2026."Personal Comisionado"),
  "Dirección Comisionado" = COALESCE(EXCLUDED."Dirección Comisionado", public.agenda_2026."Dirección Comisionado"),
  "Subdirección Comisionado" = COALESCE(EXCLUDED."Subdirección Comisionado", public.agenda_2026."Subdirección Comisionado"),
  "Gerencia Comisionado" = COALESCE(EXCLUDED."Gerencia Comisionado", public.agenda_2026."Gerencia Comisionado"),
  "Coordinación Comisionado" = COALESCE(EXCLUDED."Coordinación Comisionado", public.agenda_2026."Coordinación Comisionado"),
  "Comentarios" = COALESCE(EXCLUDED."Comentarios", public.agenda_2026."Comentarios"),
  "Amonestaciones" = COALESCE(EXCLUDED."Amonestaciones", public.agenda_2026."Amonestaciones"),
  "Rúbrica" = COALESCE(EXCLUDED."Rúbrica", public.agenda_2026."Rúbrica"),
  "Anexo ""A"" Turno especial" = COALESCE(EXCLUDED."Anexo ""A"" Turno especial", public.agenda_2026."Anexo ""A"" Turno especial"),
  "Anexo ""A"" Fecha de activación" = COALESCE(EXCLUDED."Anexo ""A"" Fecha de activación", public.agenda_2026."Anexo ""A"" Fecha de activación"),
  "Anexo ""B"" Riesgos" = COALESCE(EXCLUDED."Anexo ""B"" Riesgos", public.agenda_2026."Anexo ""B"" Riesgos"),
  "Anexo ""B"" Fecha de activación" = COALESCE(EXCLUDED."Anexo ""B"" Fecha de activación", public.agenda_2026."Anexo ""B"" Fecha de activación"),
  "Antigüedad" = COALESCE(EXCLUDED."Antigüedad", public.agenda_2026."Antigüedad"),
  "Días de vacaciones disponibles" = COALESCE(EXCLUDED."Días de vacaciones disponibles", public.agenda_2026."Días de vacaciones disponibles"),
  "Fecha de nacimiento" = COALESCE(EXCLUDED."Fecha de nacimiento", public.agenda_2026."Fecha de nacimiento"),
  "Sexo" = COALESCE(EXCLUDED."Sexo", public.agenda_2026."Sexo"),
  "CURP" = COALESCE(EXCLUDED."CURP", public.agenda_2026."CURP"),
  "RFC" = COALESCE(EXCLUDED."RFC", public.agenda_2026."RFC"),
  "NSS" = COALESCE(EXCLUDED."NSS", public.agenda_2026."NSS"),
  "Vigencia de INE" = COALESCE(EXCLUDED."Vigencia de INE", public.agenda_2026."Vigencia de INE"),
  "Fotografia de INE" = COALESCE(EXCLUDED."Fotografia de INE", public.agenda_2026."Fotografia de INE"),
  "No. telefónico" = COALESCE(EXCLUDED."No. telefónico", public.agenda_2026."No. telefónico"),
  "Domicilio (calle, colonia, municipio, estado y código postal)" = COALESCE(EXCLUDED."Domicilio (calle, colonia, municipio, estado y código postal)", public.agenda_2026."Domicilio (calle, colonia, municipio, estado y código postal)"),
  "Persona Civil o Militar" = COALESCE(EXCLUDED."Persona Civil o Militar", public.agenda_2026."Persona Civil o Militar"),
  "Grado Militar" = COALESCE(EXCLUDED."Grado Militar", public.agenda_2026."Grado Militar"),
  "Personal en activo o retirado" = COALESCE(EXCLUDED."Personal en activo o retirado", public.agenda_2026."Personal en activo o retirado"),
  "Matrícula Militar" = COALESCE(EXCLUDED."Matrícula Militar", public.agenda_2026."Matrícula Militar"),
  "Estado civil" = COALESCE(EXCLUDED."Estado civil", public.agenda_2026."Estado civil"),
  "Dependientes (hijos)" = COALESCE(EXCLUDED."Dependientes (hijos)", public.agenda_2026."Dependientes (hijos)"),
  "RUSP" = COALESCE(EXCLUDED."RUSP", public.agenda_2026."RUSP"),
  "Tipo de sangre" = COALESCE(EXCLUDED."Tipo de sangre", public.agenda_2026."Tipo de sangre"),
  "Alérgico a algún medicamento Si ó No (Especificar)" = COALESCE(EXCLUDED."Alérgico a algún medicamento Si ó No (Especificar)", public.agenda_2026."Alérgico a algún medicamento Si ó No (Especificar)"),
  "Alérgico a algún alimento. Si ó No (Especificar)" = COALESCE(EXCLUDED."Alérgico a algún alimento. Si ó No (Especificar)", public.agenda_2026."Alérgico a algún alimento. Si ó No (Especificar)"),
  "Contacto de emergencia 1 Nombre completo" = COALESCE(EXCLUDED."Contacto de emergencia 1 Nombre completo", public.agenda_2026."Contacto de emergencia 1 Nombre completo"),
  "Parentesco 1" = COALESCE(EXCLUDED."Parentesco 1", public.agenda_2026."Parentesco 1"),
  "Teléfono de emergencia 1" = COALESCE(EXCLUDED."Teléfono de emergencia 1", public.agenda_2026."Teléfono de emergencia 1"),
  "Contacto de emergencia 2 Nombre completo" = COALESCE(EXCLUDED."Contacto de emergencia 2 Nombre completo", public.agenda_2026."Contacto de emergencia 2 Nombre completo"),
  "Parentesco 2" = COALESCE(EXCLUDED."Parentesco 2", public.agenda_2026."Parentesco 2"),
  "Teléfono de emergencia 2" = COALESCE(EXCLUDED."Teléfono de emergencia 2", public.agenda_2026."Teléfono de emergencia 2"),
  "Nivel de estudio" = COALESCE(EXCLUDED."Nivel de estudio", public.agenda_2026."Nivel de estudio"),
  "Nombre de la Licenciatura y/o Maestria" = COALESCE(EXCLUDED."Nombre de la Licenciatura y/o Maestria", public.agenda_2026."Nombre de la Licenciatura y/o Maestria"),
  "Nombre de la Universidad" = COALESCE(EXCLUDED."Nombre de la Universidad", public.agenda_2026."Nombre de la Universidad"),
  "Año de Titulación" = COALESCE(EXCLUDED."Año de Titulación", public.agenda_2026."Año de Titulación"),
  "No. Cédula Profesional" = COALESCE(EXCLUDED."No. Cédula Profesional", public.agenda_2026."No. Cédula Profesional"),
  "Fotografía (vest. Formal)" = COALESCE(EXCLUDED."Fotografía (vest. Formal)", public.agenda_2026."Fotografía (vest. Formal)"),
  "Correo Personal" = COALESCE(EXCLUDED."Correo Personal", public.agenda_2026."Correo Personal"),
  "Correo Institucional" = COALESCE(EXCLUDED."Correo Institucional", public.agenda_2026."Correo Institucional"),
  "Extensión" = COALESCE(EXCLUDED."Extensión", public.agenda_2026."Extensión"),
  "Vigencia de la TIA" = COALESCE(EXCLUDED."Vigencia de la TIA", public.agenda_2026."Vigencia de la TIA"),
  "Fotografía de la TIA" = COALESCE(EXCLUDED."Fotografía de la TIA", public.agenda_2026."Fotografía de la TIA"),
  "Licencia de Manejo" = COALESCE(EXCLUDED."Licencia de Manejo", public.agenda_2026."Licencia de Manejo"),
  "Tipo de licencia" = COALESCE(EXCLUDED."Tipo de licencia", public.agenda_2026."Tipo de licencia"),
  "Licencia Vigencia" = COALESCE(EXCLUDED."Licencia Vigencia", public.agenda_2026."Licencia Vigencia"),
  "Fotografia de licencia" = COALESCE(EXCLUDED."Fotografia de licencia", public.agenda_2026."Fotografia de licencia"),
  "Edad" = COALESCE(EXCLUDED."Edad", public.agenda_2026."Edad"),
  "Cumpleaños" = COALESCE(EXCLUDED."Cumpleaños", public.agenda_2026."Cumpleaños"),
  "Doc. Para ingreso" = COALESCE(EXCLUDED."Doc. Para ingreso", public.agenda_2026."Doc. Para ingreso");

-- [454] 590 | Paola Ochoa Alcantara
INSERT INTO public.agenda_2026 (
  "No. Empleado",
  "Nombre",
  "Fecha de alta",
  "Sueldo_Bruto",
  "Plaza",
  "Nivel",
  "Dir. Orgánica",
  "Subdir. Orgánica",
  "Gerencia Orgánica",
  "Coordinación Orgánica",
  "Puesto",
  "Personal Comisionado",
  "Dirección Comisionado",
  "Subdirección Comisionado",
  "Gerencia Comisionado",
  "Coordinación Comisionado",
  "Comentarios",
  "Amonestaciones",
  "Rúbrica",
  "Anexo ""A"" Turno especial",
  "Anexo ""A"" Fecha de activación",
  "Anexo ""B"" Riesgos",
  "Anexo ""B"" Fecha de activación",
  "Antigüedad",
  "Días de vacaciones disponibles",
  "Fecha de nacimiento",
  "Sexo",
  "CURP",
  "RFC",
  "NSS",
  "Vigencia de INE",
  "Fotografia de INE",
  "No. telefónico",
  "Domicilio (calle, colonia, municipio, estado y código postal)",
  "Persona Civil o Militar",
  "Grado Militar",
  "Personal en activo o retirado",
  "Matrícula Militar",
  "Estado civil",
  "Dependientes (hijos)",
  "RUSP",
  "Tipo de sangre",
  "Alérgico a algún medicamento Si ó No (Especificar)",
  "Alérgico a algún alimento. Si ó No (Especificar)",
  "Contacto de emergencia 1 Nombre completo",
  "Parentesco 1",
  "Teléfono de emergencia 1",
  "Contacto de emergencia 2 Nombre completo",
  "Parentesco 2",
  "Teléfono de emergencia 2",
  "Nivel de estudio",
  "Nombre de la Licenciatura y/o Maestria",
  "Nombre de la Universidad",
  "Año de Titulación",
  "No. Cédula Profesional",
  "Fotografía (vest. Formal)",
  "Correo Personal",
  "Correo Institucional",
  "Extensión",
  "Vigencia de la TIA",
  "Fotografía de la TIA",
  "Licencia de Manejo",
  "Tipo de licencia",
  "Licencia Vigencia",
  "Fotografia de licencia",
  "Edad",
  "Cumpleaños",
  "Doc. Para ingreso"
) VALUES (
  '590',
  'Paola Ochoa Alcantara',
  '2022-01-20',
  '29958.98',
  '497',
  'N4',
  'Dirección Comercial y de Servicios',
  'Subdirección de Servicios Comerciales',
  'Gerencia de Mercadotécnia',
  '---',
  'Especialista en Atención a Usuarios',
  '1',
  'Dir. Opn.',
  'SI',
  'Gerencia de Ingeniería Civil',
  '0',
  '0',
  '0',
  'POA',
  NULL,
  NULL,
  NULL,
  NULL,
  '4',
  '0',
  '2001-03-13',
  'Femenino',
  'OOAP010313MMCCLLA3',
  'OOAP010313HS8',
  '0',
  '2030',
  '0',
  '55 8562 7627',
  'C. RANCHO LA Herradura Mz.74 Lt.17 Casa 110, Col. Sierra Hermosa, Mun. Tecamac, Cp. 55749',
  'Civil',
  NULL,
  NULL,
  '0',
  'Soltero(a)',
  '2',
  'COOY151002MDFRCRA6
COOA180114MMCRCSA7',
  'A+',
  'No',
  'No',
  'Luis Enrique Ochoa Martínez',
  'Padre',
  '55 2723 5360',
  'Leticia Alcantara Martínez',
  'Mamá',
  '5533075935',
  '0',
  'Estudiante de Pedagogía',
  'Universidad Ukuepa',
  NULL,
  '0',
  '0',
  'paolaochoa708@gmail.com',
  'pochoaa@aifa.aero',
  '0',
  '2025-12-20',
  'ENTREGADA',
  '0',
  '0',
  NULL,
  '0',
  '24',
  '13-mar',
  '0'
) ON CONFLICT ("No. Empleado") DO UPDATE SET
  "Nombre" = COALESCE(EXCLUDED."Nombre", public.agenda_2026."Nombre"),
  "Fecha de alta" = COALESCE(EXCLUDED."Fecha de alta", public.agenda_2026."Fecha de alta"),
  "Sueldo_Bruto" = COALESCE(EXCLUDED."Sueldo_Bruto", public.agenda_2026."Sueldo_Bruto"),
  "Plaza" = COALESCE(EXCLUDED."Plaza", public.agenda_2026."Plaza"),
  "Nivel" = COALESCE(EXCLUDED."Nivel", public.agenda_2026."Nivel"),
  "Dir. Orgánica" = COALESCE(EXCLUDED."Dir. Orgánica", public.agenda_2026."Dir. Orgánica"),
  "Subdir. Orgánica" = COALESCE(EXCLUDED."Subdir. Orgánica", public.agenda_2026."Subdir. Orgánica"),
  "Gerencia Orgánica" = COALESCE(EXCLUDED."Gerencia Orgánica", public.agenda_2026."Gerencia Orgánica"),
  "Coordinación Orgánica" = COALESCE(EXCLUDED."Coordinación Orgánica", public.agenda_2026."Coordinación Orgánica"),
  "Puesto" = COALESCE(EXCLUDED."Puesto", public.agenda_2026."Puesto"),
  "Personal Comisionado" = COALESCE(EXCLUDED."Personal Comisionado", public.agenda_2026."Personal Comisionado"),
  "Dirección Comisionado" = COALESCE(EXCLUDED."Dirección Comisionado", public.agenda_2026."Dirección Comisionado"),
  "Subdirección Comisionado" = COALESCE(EXCLUDED."Subdirección Comisionado", public.agenda_2026."Subdirección Comisionado"),
  "Gerencia Comisionado" = COALESCE(EXCLUDED."Gerencia Comisionado", public.agenda_2026."Gerencia Comisionado"),
  "Coordinación Comisionado" = COALESCE(EXCLUDED."Coordinación Comisionado", public.agenda_2026."Coordinación Comisionado"),
  "Comentarios" = COALESCE(EXCLUDED."Comentarios", public.agenda_2026."Comentarios"),
  "Amonestaciones" = COALESCE(EXCLUDED."Amonestaciones", public.agenda_2026."Amonestaciones"),
  "Rúbrica" = COALESCE(EXCLUDED."Rúbrica", public.agenda_2026."Rúbrica"),
  "Anexo ""A"" Turno especial" = COALESCE(EXCLUDED."Anexo ""A"" Turno especial", public.agenda_2026."Anexo ""A"" Turno especial"),
  "Anexo ""A"" Fecha de activación" = COALESCE(EXCLUDED."Anexo ""A"" Fecha de activación", public.agenda_2026."Anexo ""A"" Fecha de activación"),
  "Anexo ""B"" Riesgos" = COALESCE(EXCLUDED."Anexo ""B"" Riesgos", public.agenda_2026."Anexo ""B"" Riesgos"),
  "Anexo ""B"" Fecha de activación" = COALESCE(EXCLUDED."Anexo ""B"" Fecha de activación", public.agenda_2026."Anexo ""B"" Fecha de activación"),
  "Antigüedad" = COALESCE(EXCLUDED."Antigüedad", public.agenda_2026."Antigüedad"),
  "Días de vacaciones disponibles" = COALESCE(EXCLUDED."Días de vacaciones disponibles", public.agenda_2026."Días de vacaciones disponibles"),
  "Fecha de nacimiento" = COALESCE(EXCLUDED."Fecha de nacimiento", public.agenda_2026."Fecha de nacimiento"),
  "Sexo" = COALESCE(EXCLUDED."Sexo", public.agenda_2026."Sexo"),
  "CURP" = COALESCE(EXCLUDED."CURP", public.agenda_2026."CURP"),
  "RFC" = COALESCE(EXCLUDED."RFC", public.agenda_2026."RFC"),
  "NSS" = COALESCE(EXCLUDED."NSS", public.agenda_2026."NSS"),
  "Vigencia de INE" = COALESCE(EXCLUDED."Vigencia de INE", public.agenda_2026."Vigencia de INE"),
  "Fotografia de INE" = COALESCE(EXCLUDED."Fotografia de INE", public.agenda_2026."Fotografia de INE"),
  "No. telefónico" = COALESCE(EXCLUDED."No. telefónico", public.agenda_2026."No. telefónico"),
  "Domicilio (calle, colonia, municipio, estado y código postal)" = COALESCE(EXCLUDED."Domicilio (calle, colonia, municipio, estado y código postal)", public.agenda_2026."Domicilio (calle, colonia, municipio, estado y código postal)"),
  "Persona Civil o Militar" = COALESCE(EXCLUDED."Persona Civil o Militar", public.agenda_2026."Persona Civil o Militar"),
  "Grado Militar" = COALESCE(EXCLUDED."Grado Militar", public.agenda_2026."Grado Militar"),
  "Personal en activo o retirado" = COALESCE(EXCLUDED."Personal en activo o retirado", public.agenda_2026."Personal en activo o retirado"),
  "Matrícula Militar" = COALESCE(EXCLUDED."Matrícula Militar", public.agenda_2026."Matrícula Militar"),
  "Estado civil" = COALESCE(EXCLUDED."Estado civil", public.agenda_2026."Estado civil"),
  "Dependientes (hijos)" = COALESCE(EXCLUDED."Dependientes (hijos)", public.agenda_2026."Dependientes (hijos)"),
  "RUSP" = COALESCE(EXCLUDED."RUSP", public.agenda_2026."RUSP"),
  "Tipo de sangre" = COALESCE(EXCLUDED."Tipo de sangre", public.agenda_2026."Tipo de sangre"),
  "Alérgico a algún medicamento Si ó No (Especificar)" = COALESCE(EXCLUDED."Alérgico a algún medicamento Si ó No (Especificar)", public.agenda_2026."Alérgico a algún medicamento Si ó No (Especificar)"),
  "Alérgico a algún alimento. Si ó No (Especificar)" = COALESCE(EXCLUDED."Alérgico a algún alimento. Si ó No (Especificar)", public.agenda_2026."Alérgico a algún alimento. Si ó No (Especificar)"),
  "Contacto de emergencia 1 Nombre completo" = COALESCE(EXCLUDED."Contacto de emergencia 1 Nombre completo", public.agenda_2026."Contacto de emergencia 1 Nombre completo"),
  "Parentesco 1" = COALESCE(EXCLUDED."Parentesco 1", public.agenda_2026."Parentesco 1"),
  "Teléfono de emergencia 1" = COALESCE(EXCLUDED."Teléfono de emergencia 1", public.agenda_2026."Teléfono de emergencia 1"),
  "Contacto de emergencia 2 Nombre completo" = COALESCE(EXCLUDED."Contacto de emergencia 2 Nombre completo", public.agenda_2026."Contacto de emergencia 2 Nombre completo"),
  "Parentesco 2" = COALESCE(EXCLUDED."Parentesco 2", public.agenda_2026."Parentesco 2"),
  "Teléfono de emergencia 2" = COALESCE(EXCLUDED."Teléfono de emergencia 2", public.agenda_2026."Teléfono de emergencia 2"),
  "Nivel de estudio" = COALESCE(EXCLUDED."Nivel de estudio", public.agenda_2026."Nivel de estudio"),
  "Nombre de la Licenciatura y/o Maestria" = COALESCE(EXCLUDED."Nombre de la Licenciatura y/o Maestria", public.agenda_2026."Nombre de la Licenciatura y/o Maestria"),
  "Nombre de la Universidad" = COALESCE(EXCLUDED."Nombre de la Universidad", public.agenda_2026."Nombre de la Universidad"),
  "Año de Titulación" = COALESCE(EXCLUDED."Año de Titulación", public.agenda_2026."Año de Titulación"),
  "No. Cédula Profesional" = COALESCE(EXCLUDED."No. Cédula Profesional", public.agenda_2026."No. Cédula Profesional"),
  "Fotografía (vest. Formal)" = COALESCE(EXCLUDED."Fotografía (vest. Formal)", public.agenda_2026."Fotografía (vest. Formal)"),
  "Correo Personal" = COALESCE(EXCLUDED."Correo Personal", public.agenda_2026."Correo Personal"),
  "Correo Institucional" = COALESCE(EXCLUDED."Correo Institucional", public.agenda_2026."Correo Institucional"),
  "Extensión" = COALESCE(EXCLUDED."Extensión", public.agenda_2026."Extensión"),
  "Vigencia de la TIA" = COALESCE(EXCLUDED."Vigencia de la TIA", public.agenda_2026."Vigencia de la TIA"),
  "Fotografía de la TIA" = COALESCE(EXCLUDED."Fotografía de la TIA", public.agenda_2026."Fotografía de la TIA"),
  "Licencia de Manejo" = COALESCE(EXCLUDED."Licencia de Manejo", public.agenda_2026."Licencia de Manejo"),
  "Tipo de licencia" = COALESCE(EXCLUDED."Tipo de licencia", public.agenda_2026."Tipo de licencia"),
  "Licencia Vigencia" = COALESCE(EXCLUDED."Licencia Vigencia", public.agenda_2026."Licencia Vigencia"),
  "Fotografia de licencia" = COALESCE(EXCLUDED."Fotografia de licencia", public.agenda_2026."Fotografia de licencia"),
  "Edad" = COALESCE(EXCLUDED."Edad", public.agenda_2026."Edad"),
  "Cumpleaños" = COALESCE(EXCLUDED."Cumpleaños", public.agenda_2026."Cumpleaños"),
  "Doc. Para ingreso" = COALESCE(EXCLUDED."Doc. Para ingreso", public.agenda_2026."Doc. Para ingreso");

-- [455] 1693 | Alberto Ayotitla Gayoso
INSERT INTO public.agenda_2026 (
  "No. Empleado",
  "Nombre",
  "Fecha de alta",
  "Sueldo_Bruto",
  "Plaza",
  "Nivel",
  "Dir. Orgánica",
  "Subdir. Orgánica",
  "Gerencia Orgánica",
  "Coordinación Orgánica",
  "Puesto",
  "Personal Comisionado",
  "Dirección Comisionado",
  "Subdirección Comisionado",
  "Gerencia Comisionado",
  "Coordinación Comisionado",
  "Comentarios",
  "Amonestaciones",
  "Rúbrica",
  "Anexo ""A"" Turno especial",
  "Anexo ""A"" Fecha de activación",
  "Anexo ""B"" Riesgos",
  "Anexo ""B"" Fecha de activación",
  "Antigüedad",
  "Días de vacaciones disponibles",
  "Fecha de nacimiento",
  "Sexo",
  "CURP",
  "RFC",
  "NSS",
  "Vigencia de INE",
  "Fotografia de INE",
  "No. telefónico",
  "Domicilio (calle, colonia, municipio, estado y código postal)",
  "Persona Civil o Militar",
  "Grado Militar",
  "Personal en activo o retirado",
  "Matrícula Militar",
  "Estado civil",
  "Dependientes (hijos)",
  "RUSP",
  "Tipo de sangre",
  "Alérgico a algún medicamento Si ó No (Especificar)",
  "Alérgico a algún alimento. Si ó No (Especificar)",
  "Contacto de emergencia 1 Nombre completo",
  "Parentesco 1",
  "Teléfono de emergencia 1",
  "Contacto de emergencia 2 Nombre completo",
  "Parentesco 2",
  "Teléfono de emergencia 2",
  "Nivel de estudio",
  "Nombre de la Licenciatura y/o Maestria",
  "Nombre de la Universidad",
  "Año de Titulación",
  "No. Cédula Profesional",
  "Fotografía (vest. Formal)",
  "Correo Personal",
  "Correo Institucional",
  "Extensión",
  "Vigencia de la TIA",
  "Fotografía de la TIA",
  "Licencia de Manejo",
  "Tipo de licencia",
  "Licencia Vigencia",
  "Fotografia de licencia",
  "Edad",
  "Cumpleaños",
  "Doc. Para ingreso"
) VALUES (
  '1693',
  'Alberto Ayotitla Gayoso',
  '2026-03-26',
  NULL,
  '579',
  'N3',
  'Dirección Comercial y de Servicios',
  'Subdirección de Coordinación y Seguimiento de Acuerdos',
  'Gerencia de Calidad',
  '---',
  'Especialista Encuestador',
  '1',
  'Dir. Opn.',
  'SI',
  'Gerencia de Ingeniería Electromecánica',
  '---',
  '1- Ingresa el 26 Mar. 2026 y es comisionado a la Subdirección de Ingeniería, indicaciones superiores.',
  '0',
  'AAG',
  '12x36',
  '2026-04-23',
  'RyR',
  '2026-04-23',
  '0',
  '0',
  '1995-06-14',
  'Masculino',
  'AOGA950614HMCYYL06',
  'AOGA9506148I2',
  '92109503463',
  '2034',
  '0',
  '5650500822',
  'Sector 26 Mz 79 LT 29, CS1 Fraccionamiento Heroes Tecámac., C.P. 55763',
  'Civil',
  NULL,
  NULL,
  NULL,
  'Soltero',
  '0',
  NULL,
  'O+',
  'No',
  'No',
  'David Ayotitla Gayoso',
  'Hermano',
  '5611758545',
  'Angela Gayoso Velasco',
  'Madre',
  '5548791561',
  'Licenciatura en curso',
  'Ingeniería Eléctrica Electrónica',
  'Universidad Nacional Autonoma de México',
  'Pendiente',
  'Pendiente',
  '0',
  'ayotitlaalberto@gmail.com',
  'aayotitlag@aifa.aero',
  'p',
  'p',
  'p',
  'Si',
  'C',
  '1905-07-18',
  '0',
  '30',
  '14-jun',
  '0'
) ON CONFLICT ("No. Empleado") DO UPDATE SET
  "Nombre" = COALESCE(EXCLUDED."Nombre", public.agenda_2026."Nombre"),
  "Fecha de alta" = COALESCE(EXCLUDED."Fecha de alta", public.agenda_2026."Fecha de alta"),
  "Sueldo_Bruto" = COALESCE(EXCLUDED."Sueldo_Bruto", public.agenda_2026."Sueldo_Bruto"),
  "Plaza" = COALESCE(EXCLUDED."Plaza", public.agenda_2026."Plaza"),
  "Nivel" = COALESCE(EXCLUDED."Nivel", public.agenda_2026."Nivel"),
  "Dir. Orgánica" = COALESCE(EXCLUDED."Dir. Orgánica", public.agenda_2026."Dir. Orgánica"),
  "Subdir. Orgánica" = COALESCE(EXCLUDED."Subdir. Orgánica", public.agenda_2026."Subdir. Orgánica"),
  "Gerencia Orgánica" = COALESCE(EXCLUDED."Gerencia Orgánica", public.agenda_2026."Gerencia Orgánica"),
  "Coordinación Orgánica" = COALESCE(EXCLUDED."Coordinación Orgánica", public.agenda_2026."Coordinación Orgánica"),
  "Puesto" = COALESCE(EXCLUDED."Puesto", public.agenda_2026."Puesto"),
  "Personal Comisionado" = COALESCE(EXCLUDED."Personal Comisionado", public.agenda_2026."Personal Comisionado"),
  "Dirección Comisionado" = COALESCE(EXCLUDED."Dirección Comisionado", public.agenda_2026."Dirección Comisionado"),
  "Subdirección Comisionado" = COALESCE(EXCLUDED."Subdirección Comisionado", public.agenda_2026."Subdirección Comisionado"),
  "Gerencia Comisionado" = COALESCE(EXCLUDED."Gerencia Comisionado", public.agenda_2026."Gerencia Comisionado"),
  "Coordinación Comisionado" = COALESCE(EXCLUDED."Coordinación Comisionado", public.agenda_2026."Coordinación Comisionado"),
  "Comentarios" = COALESCE(EXCLUDED."Comentarios", public.agenda_2026."Comentarios"),
  "Amonestaciones" = COALESCE(EXCLUDED."Amonestaciones", public.agenda_2026."Amonestaciones"),
  "Rúbrica" = COALESCE(EXCLUDED."Rúbrica", public.agenda_2026."Rúbrica"),
  "Anexo ""A"" Turno especial" = COALESCE(EXCLUDED."Anexo ""A"" Turno especial", public.agenda_2026."Anexo ""A"" Turno especial"),
  "Anexo ""A"" Fecha de activación" = COALESCE(EXCLUDED."Anexo ""A"" Fecha de activación", public.agenda_2026."Anexo ""A"" Fecha de activación"),
  "Anexo ""B"" Riesgos" = COALESCE(EXCLUDED."Anexo ""B"" Riesgos", public.agenda_2026."Anexo ""B"" Riesgos"),
  "Anexo ""B"" Fecha de activación" = COALESCE(EXCLUDED."Anexo ""B"" Fecha de activación", public.agenda_2026."Anexo ""B"" Fecha de activación"),
  "Antigüedad" = COALESCE(EXCLUDED."Antigüedad", public.agenda_2026."Antigüedad"),
  "Días de vacaciones disponibles" = COALESCE(EXCLUDED."Días de vacaciones disponibles", public.agenda_2026."Días de vacaciones disponibles"),
  "Fecha de nacimiento" = COALESCE(EXCLUDED."Fecha de nacimiento", public.agenda_2026."Fecha de nacimiento"),
  "Sexo" = COALESCE(EXCLUDED."Sexo", public.agenda_2026."Sexo"),
  "CURP" = COALESCE(EXCLUDED."CURP", public.agenda_2026."CURP"),
  "RFC" = COALESCE(EXCLUDED."RFC", public.agenda_2026."RFC"),
  "NSS" = COALESCE(EXCLUDED."NSS", public.agenda_2026."NSS"),
  "Vigencia de INE" = COALESCE(EXCLUDED."Vigencia de INE", public.agenda_2026."Vigencia de INE"),
  "Fotografia de INE" = COALESCE(EXCLUDED."Fotografia de INE", public.agenda_2026."Fotografia de INE"),
  "No. telefónico" = COALESCE(EXCLUDED."No. telefónico", public.agenda_2026."No. telefónico"),
  "Domicilio (calle, colonia, municipio, estado y código postal)" = COALESCE(EXCLUDED."Domicilio (calle, colonia, municipio, estado y código postal)", public.agenda_2026."Domicilio (calle, colonia, municipio, estado y código postal)"),
  "Persona Civil o Militar" = COALESCE(EXCLUDED."Persona Civil o Militar", public.agenda_2026."Persona Civil o Militar"),
  "Grado Militar" = COALESCE(EXCLUDED."Grado Militar", public.agenda_2026."Grado Militar"),
  "Personal en activo o retirado" = COALESCE(EXCLUDED."Personal en activo o retirado", public.agenda_2026."Personal en activo o retirado"),
  "Matrícula Militar" = COALESCE(EXCLUDED."Matrícula Militar", public.agenda_2026."Matrícula Militar"),
  "Estado civil" = COALESCE(EXCLUDED."Estado civil", public.agenda_2026."Estado civil"),
  "Dependientes (hijos)" = COALESCE(EXCLUDED."Dependientes (hijos)", public.agenda_2026."Dependientes (hijos)"),
  "RUSP" = COALESCE(EXCLUDED."RUSP", public.agenda_2026."RUSP"),
  "Tipo de sangre" = COALESCE(EXCLUDED."Tipo de sangre", public.agenda_2026."Tipo de sangre"),
  "Alérgico a algún medicamento Si ó No (Especificar)" = COALESCE(EXCLUDED."Alérgico a algún medicamento Si ó No (Especificar)", public.agenda_2026."Alérgico a algún medicamento Si ó No (Especificar)"),
  "Alérgico a algún alimento. Si ó No (Especificar)" = COALESCE(EXCLUDED."Alérgico a algún alimento. Si ó No (Especificar)", public.agenda_2026."Alérgico a algún alimento. Si ó No (Especificar)"),
  "Contacto de emergencia 1 Nombre completo" = COALESCE(EXCLUDED."Contacto de emergencia 1 Nombre completo", public.agenda_2026."Contacto de emergencia 1 Nombre completo"),
  "Parentesco 1" = COALESCE(EXCLUDED."Parentesco 1", public.agenda_2026."Parentesco 1"),
  "Teléfono de emergencia 1" = COALESCE(EXCLUDED."Teléfono de emergencia 1", public.agenda_2026."Teléfono de emergencia 1"),
  "Contacto de emergencia 2 Nombre completo" = COALESCE(EXCLUDED."Contacto de emergencia 2 Nombre completo", public.agenda_2026."Contacto de emergencia 2 Nombre completo"),
  "Parentesco 2" = COALESCE(EXCLUDED."Parentesco 2", public.agenda_2026."Parentesco 2"),
  "Teléfono de emergencia 2" = COALESCE(EXCLUDED."Teléfono de emergencia 2", public.agenda_2026."Teléfono de emergencia 2"),
  "Nivel de estudio" = COALESCE(EXCLUDED."Nivel de estudio", public.agenda_2026."Nivel de estudio"),
  "Nombre de la Licenciatura y/o Maestria" = COALESCE(EXCLUDED."Nombre de la Licenciatura y/o Maestria", public.agenda_2026."Nombre de la Licenciatura y/o Maestria"),
  "Nombre de la Universidad" = COALESCE(EXCLUDED."Nombre de la Universidad", public.agenda_2026."Nombre de la Universidad"),
  "Año de Titulación" = COALESCE(EXCLUDED."Año de Titulación", public.agenda_2026."Año de Titulación"),
  "No. Cédula Profesional" = COALESCE(EXCLUDED."No. Cédula Profesional", public.agenda_2026."No. Cédula Profesional"),
  "Fotografía (vest. Formal)" = COALESCE(EXCLUDED."Fotografía (vest. Formal)", public.agenda_2026."Fotografía (vest. Formal)"),
  "Correo Personal" = COALESCE(EXCLUDED."Correo Personal", public.agenda_2026."Correo Personal"),
  "Correo Institucional" = COALESCE(EXCLUDED."Correo Institucional", public.agenda_2026."Correo Institucional"),
  "Extensión" = COALESCE(EXCLUDED."Extensión", public.agenda_2026."Extensión"),
  "Vigencia de la TIA" = COALESCE(EXCLUDED."Vigencia de la TIA", public.agenda_2026."Vigencia de la TIA"),
  "Fotografía de la TIA" = COALESCE(EXCLUDED."Fotografía de la TIA", public.agenda_2026."Fotografía de la TIA"),
  "Licencia de Manejo" = COALESCE(EXCLUDED."Licencia de Manejo", public.agenda_2026."Licencia de Manejo"),
  "Tipo de licencia" = COALESCE(EXCLUDED."Tipo de licencia", public.agenda_2026."Tipo de licencia"),
  "Licencia Vigencia" = COALESCE(EXCLUDED."Licencia Vigencia", public.agenda_2026."Licencia Vigencia"),
  "Fotografia de licencia" = COALESCE(EXCLUDED."Fotografia de licencia", public.agenda_2026."Fotografia de licencia"),
  "Edad" = COALESCE(EXCLUDED."Edad", public.agenda_2026."Edad"),
  "Cumpleaños" = COALESCE(EXCLUDED."Cumpleaños", public.agenda_2026."Cumpleaños"),
  "Doc. Para ingreso" = COALESCE(EXCLUDED."Doc. Para ingreso", public.agenda_2026."Doc. Para ingreso");

-- [456] 1205 | Carlos Santiago Tenorio
INSERT INTO public.agenda_2026 (
  "No. Empleado",
  "Nombre",
  "Fecha de alta",
  "Sueldo_Bruto",
  "Plaza",
  "Nivel",
  "Dir. Orgánica",
  "Subdir. Orgánica",
  "Gerencia Orgánica",
  "Coordinación Orgánica",
  "Puesto",
  "Personal Comisionado",
  "Dirección Comisionado",
  "Subdirección Comisionado",
  "Gerencia Comisionado",
  "Coordinación Comisionado",
  "Comentarios",
  "Amonestaciones",
  "Rúbrica",
  "Anexo ""A"" Turno especial",
  "Anexo ""A"" Fecha de activación",
  "Anexo ""B"" Riesgos",
  "Anexo ""B"" Fecha de activación",
  "Antigüedad",
  "Días de vacaciones disponibles",
  "Fecha de nacimiento",
  "Sexo",
  "CURP",
  "RFC",
  "NSS",
  "Vigencia de INE",
  "Fotografia de INE",
  "No. telefónico",
  "Domicilio (calle, colonia, municipio, estado y código postal)",
  "Persona Civil o Militar",
  "Grado Militar",
  "Personal en activo o retirado",
  "Matrícula Militar",
  "Estado civil",
  "Dependientes (hijos)",
  "RUSP",
  "Tipo de sangre",
  "Alérgico a algún medicamento Si ó No (Especificar)",
  "Alérgico a algún alimento. Si ó No (Especificar)",
  "Contacto de emergencia 1 Nombre completo",
  "Parentesco 1",
  "Teléfono de emergencia 1",
  "Contacto de emergencia 2 Nombre completo",
  "Parentesco 2",
  "Teléfono de emergencia 2",
  "Nivel de estudio",
  "Nombre de la Licenciatura y/o Maestria",
  "Nombre de la Universidad",
  "Año de Titulación",
  "No. Cédula Profesional",
  "Fotografía (vest. Formal)",
  "Correo Personal",
  "Correo Institucional",
  "Extensión",
  "Vigencia de la TIA",
  "Fotografía de la TIA",
  "Licencia de Manejo",
  "Tipo de licencia",
  "Licencia Vigencia",
  "Fotografia de licencia",
  "Edad",
  "Cumpleaños",
  "Doc. Para ingreso"
) VALUES (
  '1205',
  'Carlos Santiago Tenorio',
  '2024-02-01',
  NULL,
  NULL,
  NULL,
  'Dirección de Administración',
  'Subdirección de Recursos Materiales',
  'Gerencia de Recursos Materiales',
  '---',
  'Auxiliar en Procedimientos de Adquisiciones',
  '1',
  'Dir. Opn.',
  'SGE',
  'Gerencia de Generación',
  '0',
  '1- 02 Mar. 2026, comisión laboral en la Gerencia de Proyectos y Concursos de la DO.
2- 09 Abr. 2026, comisión laboral en la Gerencia de Generación de la Subdirección de Gestión Energética',
  '0',
  'CST',
  NULL,
  NULL,
  NULL,
  NULL,
  '0',
  '0',
  '1991-09-10',
  'Masculino',
  'SATC010910HDFNNR02',
  'SATC9109101V4',
  '45099147683',
  '2033',
  NULL,
  '7341566116',
  'Calle Bellavista No.18 Colonia Bellavista, Iztapalapa, Ciudad De México C.P. 09860',
  'Civil',
  NULL,
  NULL,
  NULL,
  'Soltero',
  '0',
  NULL,
  'O+',
  'No',
  'No',
  'Diana Laura Santiago Tenorio',
  'Hermana',
  '55 7722 8655',
  'Aereopagita Tenorio Rodríguez',
  'Madre',
  '55 5443 6319',
  'Superior',
  'Licenciatura en Ingenieria en Sistemas Automotrices',
  'Instituto Politécnico Nacional',
  'Título en trámite',
  NULL,
  '0',
  'carlos.st1991@gmail.com',
  'csantiagot@aifa.aero',
  '13521',
  '2028-04-25',
  NULL,
  'Si',
  'A',
  '2028-04-25',
  '0',
  '0',
  NULL,
  '0'
) ON CONFLICT ("No. Empleado") DO UPDATE SET
  "Nombre" = COALESCE(EXCLUDED."Nombre", public.agenda_2026."Nombre"),
  "Fecha de alta" = COALESCE(EXCLUDED."Fecha de alta", public.agenda_2026."Fecha de alta"),
  "Sueldo_Bruto" = COALESCE(EXCLUDED."Sueldo_Bruto", public.agenda_2026."Sueldo_Bruto"),
  "Plaza" = COALESCE(EXCLUDED."Plaza", public.agenda_2026."Plaza"),
  "Nivel" = COALESCE(EXCLUDED."Nivel", public.agenda_2026."Nivel"),
  "Dir. Orgánica" = COALESCE(EXCLUDED."Dir. Orgánica", public.agenda_2026."Dir. Orgánica"),
  "Subdir. Orgánica" = COALESCE(EXCLUDED."Subdir. Orgánica", public.agenda_2026."Subdir. Orgánica"),
  "Gerencia Orgánica" = COALESCE(EXCLUDED."Gerencia Orgánica", public.agenda_2026."Gerencia Orgánica"),
  "Coordinación Orgánica" = COALESCE(EXCLUDED."Coordinación Orgánica", public.agenda_2026."Coordinación Orgánica"),
  "Puesto" = COALESCE(EXCLUDED."Puesto", public.agenda_2026."Puesto"),
  "Personal Comisionado" = COALESCE(EXCLUDED."Personal Comisionado", public.agenda_2026."Personal Comisionado"),
  "Dirección Comisionado" = COALESCE(EXCLUDED."Dirección Comisionado", public.agenda_2026."Dirección Comisionado"),
  "Subdirección Comisionado" = COALESCE(EXCLUDED."Subdirección Comisionado", public.agenda_2026."Subdirección Comisionado"),
  "Gerencia Comisionado" = COALESCE(EXCLUDED."Gerencia Comisionado", public.agenda_2026."Gerencia Comisionado"),
  "Coordinación Comisionado" = COALESCE(EXCLUDED."Coordinación Comisionado", public.agenda_2026."Coordinación Comisionado"),
  "Comentarios" = COALESCE(EXCLUDED."Comentarios", public.agenda_2026."Comentarios"),
  "Amonestaciones" = COALESCE(EXCLUDED."Amonestaciones", public.agenda_2026."Amonestaciones"),
  "Rúbrica" = COALESCE(EXCLUDED."Rúbrica", public.agenda_2026."Rúbrica"),
  "Anexo ""A"" Turno especial" = COALESCE(EXCLUDED."Anexo ""A"" Turno especial", public.agenda_2026."Anexo ""A"" Turno especial"),
  "Anexo ""A"" Fecha de activación" = COALESCE(EXCLUDED."Anexo ""A"" Fecha de activación", public.agenda_2026."Anexo ""A"" Fecha de activación"),
  "Anexo ""B"" Riesgos" = COALESCE(EXCLUDED."Anexo ""B"" Riesgos", public.agenda_2026."Anexo ""B"" Riesgos"),
  "Anexo ""B"" Fecha de activación" = COALESCE(EXCLUDED."Anexo ""B"" Fecha de activación", public.agenda_2026."Anexo ""B"" Fecha de activación"),
  "Antigüedad" = COALESCE(EXCLUDED."Antigüedad", public.agenda_2026."Antigüedad"),
  "Días de vacaciones disponibles" = COALESCE(EXCLUDED."Días de vacaciones disponibles", public.agenda_2026."Días de vacaciones disponibles"),
  "Fecha de nacimiento" = COALESCE(EXCLUDED."Fecha de nacimiento", public.agenda_2026."Fecha de nacimiento"),
  "Sexo" = COALESCE(EXCLUDED."Sexo", public.agenda_2026."Sexo"),
  "CURP" = COALESCE(EXCLUDED."CURP", public.agenda_2026."CURP"),
  "RFC" = COALESCE(EXCLUDED."RFC", public.agenda_2026."RFC"),
  "NSS" = COALESCE(EXCLUDED."NSS", public.agenda_2026."NSS"),
  "Vigencia de INE" = COALESCE(EXCLUDED."Vigencia de INE", public.agenda_2026."Vigencia de INE"),
  "Fotografia de INE" = COALESCE(EXCLUDED."Fotografia de INE", public.agenda_2026."Fotografia de INE"),
  "No. telefónico" = COALESCE(EXCLUDED."No. telefónico", public.agenda_2026."No. telefónico"),
  "Domicilio (calle, colonia, municipio, estado y código postal)" = COALESCE(EXCLUDED."Domicilio (calle, colonia, municipio, estado y código postal)", public.agenda_2026."Domicilio (calle, colonia, municipio, estado y código postal)"),
  "Persona Civil o Militar" = COALESCE(EXCLUDED."Persona Civil o Militar", public.agenda_2026."Persona Civil o Militar"),
  "Grado Militar" = COALESCE(EXCLUDED."Grado Militar", public.agenda_2026."Grado Militar"),
  "Personal en activo o retirado" = COALESCE(EXCLUDED."Personal en activo o retirado", public.agenda_2026."Personal en activo o retirado"),
  "Matrícula Militar" = COALESCE(EXCLUDED."Matrícula Militar", public.agenda_2026."Matrícula Militar"),
  "Estado civil" = COALESCE(EXCLUDED."Estado civil", public.agenda_2026."Estado civil"),
  "Dependientes (hijos)" = COALESCE(EXCLUDED."Dependientes (hijos)", public.agenda_2026."Dependientes (hijos)"),
  "RUSP" = COALESCE(EXCLUDED."RUSP", public.agenda_2026."RUSP"),
  "Tipo de sangre" = COALESCE(EXCLUDED."Tipo de sangre", public.agenda_2026."Tipo de sangre"),
  "Alérgico a algún medicamento Si ó No (Especificar)" = COALESCE(EXCLUDED."Alérgico a algún medicamento Si ó No (Especificar)", public.agenda_2026."Alérgico a algún medicamento Si ó No (Especificar)"),
  "Alérgico a algún alimento. Si ó No (Especificar)" = COALESCE(EXCLUDED."Alérgico a algún alimento. Si ó No (Especificar)", public.agenda_2026."Alérgico a algún alimento. Si ó No (Especificar)"),
  "Contacto de emergencia 1 Nombre completo" = COALESCE(EXCLUDED."Contacto de emergencia 1 Nombre completo", public.agenda_2026."Contacto de emergencia 1 Nombre completo"),
  "Parentesco 1" = COALESCE(EXCLUDED."Parentesco 1", public.agenda_2026."Parentesco 1"),
  "Teléfono de emergencia 1" = COALESCE(EXCLUDED."Teléfono de emergencia 1", public.agenda_2026."Teléfono de emergencia 1"),
  "Contacto de emergencia 2 Nombre completo" = COALESCE(EXCLUDED."Contacto de emergencia 2 Nombre completo", public.agenda_2026."Contacto de emergencia 2 Nombre completo"),
  "Parentesco 2" = COALESCE(EXCLUDED."Parentesco 2", public.agenda_2026."Parentesco 2"),
  "Teléfono de emergencia 2" = COALESCE(EXCLUDED."Teléfono de emergencia 2", public.agenda_2026."Teléfono de emergencia 2"),
  "Nivel de estudio" = COALESCE(EXCLUDED."Nivel de estudio", public.agenda_2026."Nivel de estudio"),
  "Nombre de la Licenciatura y/o Maestria" = COALESCE(EXCLUDED."Nombre de la Licenciatura y/o Maestria", public.agenda_2026."Nombre de la Licenciatura y/o Maestria"),
  "Nombre de la Universidad" = COALESCE(EXCLUDED."Nombre de la Universidad", public.agenda_2026."Nombre de la Universidad"),
  "Año de Titulación" = COALESCE(EXCLUDED."Año de Titulación", public.agenda_2026."Año de Titulación"),
  "No. Cédula Profesional" = COALESCE(EXCLUDED."No. Cédula Profesional", public.agenda_2026."No. Cédula Profesional"),
  "Fotografía (vest. Formal)" = COALESCE(EXCLUDED."Fotografía (vest. Formal)", public.agenda_2026."Fotografía (vest. Formal)"),
  "Correo Personal" = COALESCE(EXCLUDED."Correo Personal", public.agenda_2026."Correo Personal"),
  "Correo Institucional" = COALESCE(EXCLUDED."Correo Institucional", public.agenda_2026."Correo Institucional"),
  "Extensión" = COALESCE(EXCLUDED."Extensión", public.agenda_2026."Extensión"),
  "Vigencia de la TIA" = COALESCE(EXCLUDED."Vigencia de la TIA", public.agenda_2026."Vigencia de la TIA"),
  "Fotografía de la TIA" = COALESCE(EXCLUDED."Fotografía de la TIA", public.agenda_2026."Fotografía de la TIA"),
  "Licencia de Manejo" = COALESCE(EXCLUDED."Licencia de Manejo", public.agenda_2026."Licencia de Manejo"),
  "Tipo de licencia" = COALESCE(EXCLUDED."Tipo de licencia", public.agenda_2026."Tipo de licencia"),
  "Licencia Vigencia" = COALESCE(EXCLUDED."Licencia Vigencia", public.agenda_2026."Licencia Vigencia"),
  "Fotografia de licencia" = COALESCE(EXCLUDED."Fotografia de licencia", public.agenda_2026."Fotografia de licencia"),
  "Edad" = COALESCE(EXCLUDED."Edad", public.agenda_2026."Edad"),
  "Cumpleaños" = COALESCE(EXCLUDED."Cumpleaños", public.agenda_2026."Cumpleaños"),
  "Doc. Para ingreso" = COALESCE(EXCLUDED."Doc. Para ingreso", public.agenda_2026."Doc. Para ingreso");

-- [457] 1412-2 | Ricardo Alexis García Escobar
INSERT INTO public.agenda_2026 (
  "No. Empleado",
  "Nombre",
  "Fecha de alta",
  "Sueldo_Bruto",
  "Plaza",
  "Nivel",
  "Dir. Orgánica",
  "Subdir. Orgánica",
  "Gerencia Orgánica",
  "Coordinación Orgánica",
  "Puesto",
  "Personal Comisionado",
  "Dirección Comisionado",
  "Subdirección Comisionado",
  "Gerencia Comisionado",
  "Coordinación Comisionado",
  "Comentarios",
  "Amonestaciones",
  "Rúbrica",
  "Anexo ""A"" Turno especial",
  "Anexo ""A"" Fecha de activación",
  "Anexo ""B"" Riesgos",
  "Anexo ""B"" Fecha de activación",
  "Antigüedad",
  "Días de vacaciones disponibles",
  "Fecha de nacimiento",
  "Sexo",
  "CURP",
  "RFC",
  "NSS",
  "Vigencia de INE",
  "Fotografia de INE",
  "No. telefónico",
  "Domicilio (calle, colonia, municipio, estado y código postal)",
  "Persona Civil o Militar",
  "Grado Militar",
  "Personal en activo o retirado",
  "Matrícula Militar",
  "Estado civil",
  "Dependientes (hijos)",
  "RUSP",
  "Tipo de sangre",
  "Alérgico a algún medicamento Si ó No (Especificar)",
  "Alérgico a algún alimento. Si ó No (Especificar)",
  "Contacto de emergencia 1 Nombre completo",
  "Parentesco 1",
  "Teléfono de emergencia 1",
  "Contacto de emergencia 2 Nombre completo",
  "Parentesco 2",
  "Teléfono de emergencia 2",
  "Nivel de estudio",
  "Nombre de la Licenciatura y/o Maestria",
  "Nombre de la Universidad",
  "Año de Titulación",
  "No. Cédula Profesional",
  "Fotografía (vest. Formal)",
  "Correo Personal",
  "Correo Institucional",
  "Extensión",
  "Vigencia de la TIA",
  "Fotografía de la TIA",
  "Licencia de Manejo",
  "Tipo de licencia",
  "Licencia Vigencia",
  "Fotografia de licencia",
  "Edad",
  "Cumpleaños",
  "Doc. Para ingreso"
) VALUES (
  '1412-2',
  'Ricardo Alexis García Escobar',
  '2025-11-06',
  NULL,
  NULL,
  NULL,
  NULL,
  'Subdirección de Coordinación y Seguimiento de Acuerdos',
  'Gerencia de Relaciones Públicas y Salón Oficial',
  NULL,
  'Profesional Ejecutivo Aeroportuario',
  '1',
  'Dir. Opn.',
  'SSO',
  'Gerencia de Operaciones Parte Aeronáutica',
  '0',
  '1- Reingreso, pasa de plaza eventual 53E N4 a plaza fija de la Subdirección de Coodinación y Seguimiento de Acuerdos en la Gerencia de Relaciones Públicas, (indicaciones Superiores), solo nos informan, que quedará comisionado a GOPA.
2- Comisión laboral AIFA-DA-SRH-463-2025 06. Nov. 2025, Se le informa comisión laboral a ñla Gerencia de Operaciones Parte Aeronáutica, a partir de la fecha.',
  '0',
  'RAGE',
  '12X36',
  '2025-11-06',
  'RyR',
  '2025-11-06',
  '0',
  '0',
  '1995-11-25',
  'Masculino',
  'GAER951125HVZRSC01',
  NULL,
  '0',
  '2034',
  '0',
  '77 1708 3915',
  'C. Minillas No.207 Fracc. Pitahayas, Pachuca de Soto, Hgo. Cp. 42082',
  'Civil',
  NULL,
  NULL,
  NULL,
  'Unión libre',
  '2',
  'GAER951125HVZRSC01
GACE210721HHGRMBA1',
  'O+',
  'No',
  'No',
  'Yuliza Camargo Baltazar',
  'Pareja',
  '77 1329 6431',
  NULL,
  NULL,
  NULL,
  '0',
  'Pasante en Ingeniería Minera Metalurgica',
  NULL,
  NULL,
  'Pasante',
  '0',
  'richieeegaes@hotmail.com',
  'agarciae@aifa.aero',
  '0',
  NULL,
  NULL,
  '0',
  '0',
  NULL,
  '0',
  '30',
  '25-nov',
  '0'
) ON CONFLICT ("No. Empleado") DO UPDATE SET
  "Nombre" = COALESCE(EXCLUDED."Nombre", public.agenda_2026."Nombre"),
  "Fecha de alta" = COALESCE(EXCLUDED."Fecha de alta", public.agenda_2026."Fecha de alta"),
  "Sueldo_Bruto" = COALESCE(EXCLUDED."Sueldo_Bruto", public.agenda_2026."Sueldo_Bruto"),
  "Plaza" = COALESCE(EXCLUDED."Plaza", public.agenda_2026."Plaza"),
  "Nivel" = COALESCE(EXCLUDED."Nivel", public.agenda_2026."Nivel"),
  "Dir. Orgánica" = COALESCE(EXCLUDED."Dir. Orgánica", public.agenda_2026."Dir. Orgánica"),
  "Subdir. Orgánica" = COALESCE(EXCLUDED."Subdir. Orgánica", public.agenda_2026."Subdir. Orgánica"),
  "Gerencia Orgánica" = COALESCE(EXCLUDED."Gerencia Orgánica", public.agenda_2026."Gerencia Orgánica"),
  "Coordinación Orgánica" = COALESCE(EXCLUDED."Coordinación Orgánica", public.agenda_2026."Coordinación Orgánica"),
  "Puesto" = COALESCE(EXCLUDED."Puesto", public.agenda_2026."Puesto"),
  "Personal Comisionado" = COALESCE(EXCLUDED."Personal Comisionado", public.agenda_2026."Personal Comisionado"),
  "Dirección Comisionado" = COALESCE(EXCLUDED."Dirección Comisionado", public.agenda_2026."Dirección Comisionado"),
  "Subdirección Comisionado" = COALESCE(EXCLUDED."Subdirección Comisionado", public.agenda_2026."Subdirección Comisionado"),
  "Gerencia Comisionado" = COALESCE(EXCLUDED."Gerencia Comisionado", public.agenda_2026."Gerencia Comisionado"),
  "Coordinación Comisionado" = COALESCE(EXCLUDED."Coordinación Comisionado", public.agenda_2026."Coordinación Comisionado"),
  "Comentarios" = COALESCE(EXCLUDED."Comentarios", public.agenda_2026."Comentarios"),
  "Amonestaciones" = COALESCE(EXCLUDED."Amonestaciones", public.agenda_2026."Amonestaciones"),
  "Rúbrica" = COALESCE(EXCLUDED."Rúbrica", public.agenda_2026."Rúbrica"),
  "Anexo ""A"" Turno especial" = COALESCE(EXCLUDED."Anexo ""A"" Turno especial", public.agenda_2026."Anexo ""A"" Turno especial"),
  "Anexo ""A"" Fecha de activación" = COALESCE(EXCLUDED."Anexo ""A"" Fecha de activación", public.agenda_2026."Anexo ""A"" Fecha de activación"),
  "Anexo ""B"" Riesgos" = COALESCE(EXCLUDED."Anexo ""B"" Riesgos", public.agenda_2026."Anexo ""B"" Riesgos"),
  "Anexo ""B"" Fecha de activación" = COALESCE(EXCLUDED."Anexo ""B"" Fecha de activación", public.agenda_2026."Anexo ""B"" Fecha de activación"),
  "Antigüedad" = COALESCE(EXCLUDED."Antigüedad", public.agenda_2026."Antigüedad"),
  "Días de vacaciones disponibles" = COALESCE(EXCLUDED."Días de vacaciones disponibles", public.agenda_2026."Días de vacaciones disponibles"),
  "Fecha de nacimiento" = COALESCE(EXCLUDED."Fecha de nacimiento", public.agenda_2026."Fecha de nacimiento"),
  "Sexo" = COALESCE(EXCLUDED."Sexo", public.agenda_2026."Sexo"),
  "CURP" = COALESCE(EXCLUDED."CURP", public.agenda_2026."CURP"),
  "RFC" = COALESCE(EXCLUDED."RFC", public.agenda_2026."RFC"),
  "NSS" = COALESCE(EXCLUDED."NSS", public.agenda_2026."NSS"),
  "Vigencia de INE" = COALESCE(EXCLUDED."Vigencia de INE", public.agenda_2026."Vigencia de INE"),
  "Fotografia de INE" = COALESCE(EXCLUDED."Fotografia de INE", public.agenda_2026."Fotografia de INE"),
  "No. telefónico" = COALESCE(EXCLUDED."No. telefónico", public.agenda_2026."No. telefónico"),
  "Domicilio (calle, colonia, municipio, estado y código postal)" = COALESCE(EXCLUDED."Domicilio (calle, colonia, municipio, estado y código postal)", public.agenda_2026."Domicilio (calle, colonia, municipio, estado y código postal)"),
  "Persona Civil o Militar" = COALESCE(EXCLUDED."Persona Civil o Militar", public.agenda_2026."Persona Civil o Militar"),
  "Grado Militar" = COALESCE(EXCLUDED."Grado Militar", public.agenda_2026."Grado Militar"),
  "Personal en activo o retirado" = COALESCE(EXCLUDED."Personal en activo o retirado", public.agenda_2026."Personal en activo o retirado"),
  "Matrícula Militar" = COALESCE(EXCLUDED."Matrícula Militar", public.agenda_2026."Matrícula Militar"),
  "Estado civil" = COALESCE(EXCLUDED."Estado civil", public.agenda_2026."Estado civil"),
  "Dependientes (hijos)" = COALESCE(EXCLUDED."Dependientes (hijos)", public.agenda_2026."Dependientes (hijos)"),
  "RUSP" = COALESCE(EXCLUDED."RUSP", public.agenda_2026."RUSP"),
  "Tipo de sangre" = COALESCE(EXCLUDED."Tipo de sangre", public.agenda_2026."Tipo de sangre"),
  "Alérgico a algún medicamento Si ó No (Especificar)" = COALESCE(EXCLUDED."Alérgico a algún medicamento Si ó No (Especificar)", public.agenda_2026."Alérgico a algún medicamento Si ó No (Especificar)"),
  "Alérgico a algún alimento. Si ó No (Especificar)" = COALESCE(EXCLUDED."Alérgico a algún alimento. Si ó No (Especificar)", public.agenda_2026."Alérgico a algún alimento. Si ó No (Especificar)"),
  "Contacto de emergencia 1 Nombre completo" = COALESCE(EXCLUDED."Contacto de emergencia 1 Nombre completo", public.agenda_2026."Contacto de emergencia 1 Nombre completo"),
  "Parentesco 1" = COALESCE(EXCLUDED."Parentesco 1", public.agenda_2026."Parentesco 1"),
  "Teléfono de emergencia 1" = COALESCE(EXCLUDED."Teléfono de emergencia 1", public.agenda_2026."Teléfono de emergencia 1"),
  "Contacto de emergencia 2 Nombre completo" = COALESCE(EXCLUDED."Contacto de emergencia 2 Nombre completo", public.agenda_2026."Contacto de emergencia 2 Nombre completo"),
  "Parentesco 2" = COALESCE(EXCLUDED."Parentesco 2", public.agenda_2026."Parentesco 2"),
  "Teléfono de emergencia 2" = COALESCE(EXCLUDED."Teléfono de emergencia 2", public.agenda_2026."Teléfono de emergencia 2"),
  "Nivel de estudio" = COALESCE(EXCLUDED."Nivel de estudio", public.agenda_2026."Nivel de estudio"),
  "Nombre de la Licenciatura y/o Maestria" = COALESCE(EXCLUDED."Nombre de la Licenciatura y/o Maestria", public.agenda_2026."Nombre de la Licenciatura y/o Maestria"),
  "Nombre de la Universidad" = COALESCE(EXCLUDED."Nombre de la Universidad", public.agenda_2026."Nombre de la Universidad"),
  "Año de Titulación" = COALESCE(EXCLUDED."Año de Titulación", public.agenda_2026."Año de Titulación"),
  "No. Cédula Profesional" = COALESCE(EXCLUDED."No. Cédula Profesional", public.agenda_2026."No. Cédula Profesional"),
  "Fotografía (vest. Formal)" = COALESCE(EXCLUDED."Fotografía (vest. Formal)", public.agenda_2026."Fotografía (vest. Formal)"),
  "Correo Personal" = COALESCE(EXCLUDED."Correo Personal", public.agenda_2026."Correo Personal"),
  "Correo Institucional" = COALESCE(EXCLUDED."Correo Institucional", public.agenda_2026."Correo Institucional"),
  "Extensión" = COALESCE(EXCLUDED."Extensión", public.agenda_2026."Extensión"),
  "Vigencia de la TIA" = COALESCE(EXCLUDED."Vigencia de la TIA", public.agenda_2026."Vigencia de la TIA"),
  "Fotografía de la TIA" = COALESCE(EXCLUDED."Fotografía de la TIA", public.agenda_2026."Fotografía de la TIA"),
  "Licencia de Manejo" = COALESCE(EXCLUDED."Licencia de Manejo", public.agenda_2026."Licencia de Manejo"),
  "Tipo de licencia" = COALESCE(EXCLUDED."Tipo de licencia", public.agenda_2026."Tipo de licencia"),
  "Licencia Vigencia" = COALESCE(EXCLUDED."Licencia Vigencia", public.agenda_2026."Licencia Vigencia"),
  "Fotografia de licencia" = COALESCE(EXCLUDED."Fotografia de licencia", public.agenda_2026."Fotografia de licencia"),
  "Edad" = COALESCE(EXCLUDED."Edad", public.agenda_2026."Edad"),
  "Cumpleaños" = COALESCE(EXCLUDED."Cumpleaños", public.agenda_2026."Cumpleaños"),
  "Doc. Para ingreso" = COALESCE(EXCLUDED."Doc. Para ingreso", public.agenda_2026."Doc. Para ingreso");

-- [458] 1590-2 | Felipe Márquez Munguía
INSERT INTO public.agenda_2026 (
  "No. Empleado",
  "Nombre",
  "Fecha de alta",
  "Sueldo_Bruto",
  "Plaza",
  "Nivel",
  "Dir. Orgánica",
  "Subdir. Orgánica",
  "Gerencia Orgánica",
  "Coordinación Orgánica",
  "Puesto",
  "Personal Comisionado",
  "Dirección Comisionado",
  "Subdirección Comisionado",
  "Gerencia Comisionado",
  "Coordinación Comisionado",
  "Comentarios",
  "Amonestaciones",
  "Rúbrica",
  "Anexo ""A"" Turno especial",
  "Anexo ""A"" Fecha de activación",
  "Anexo ""B"" Riesgos",
  "Anexo ""B"" Fecha de activación",
  "Antigüedad",
  "Días de vacaciones disponibles",
  "Fecha de nacimiento",
  "Sexo",
  "CURP",
  "RFC",
  "NSS",
  "Vigencia de INE",
  "Fotografia de INE",
  "No. telefónico",
  "Domicilio (calle, colonia, municipio, estado y código postal)",
  "Persona Civil o Militar",
  "Grado Militar",
  "Personal en activo o retirado",
  "Matrícula Militar",
  "Estado civil",
  "Dependientes (hijos)",
  "RUSP",
  "Tipo de sangre",
  "Alérgico a algún medicamento Si ó No (Especificar)",
  "Alérgico a algún alimento. Si ó No (Especificar)",
  "Contacto de emergencia 1 Nombre completo",
  "Parentesco 1",
  "Teléfono de emergencia 1",
  "Contacto de emergencia 2 Nombre completo",
  "Parentesco 2",
  "Teléfono de emergencia 2",
  "Nivel de estudio",
  "Nombre de la Licenciatura y/o Maestria",
  "Nombre de la Universidad",
  "Año de Titulación",
  "No. Cédula Profesional",
  "Fotografía (vest. Formal)",
  "Correo Personal",
  "Correo Institucional",
  "Extensión",
  "Vigencia de la TIA",
  "Fotografía de la TIA",
  "Licencia de Manejo",
  "Tipo de licencia",
  "Licencia Vigencia",
  "Fotografia de licencia",
  "Edad",
  "Cumpleaños",
  "Doc. Para ingreso"
) VALUES (
  '1590-2',
  'Felipe Márquez Munguía',
  NULL,
  NULL,
  '37E',
  'N4',
  'Subdirección General Administrativa',
  'Subdirección General Administrativa',
  'Unidad de Transparencia',
  '---',
  'Profesional Ejecutivo Aeroportuario',
  '1',
  'Dir. Opn.',
  'SSO',
  'Gerencia de Operaciones Parte Aeronáutica',
  '0',
  '1- Comisión laboral AIFA-DA-SRH-930-2026 29 Ene. 2026  en la Gerencia de Operaciones Parte Aeronáutica, a partir de la fecha.',
  '0',
  '0',
  '0',
  NULL,
  'RyR',
  '2026-04-23',
  '0',
  '0',
  NULL,
  'Masculino',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  'Calle Puerto Vallarta Mz.57 Lt.9 Col., Loma la Palma, Gustavo A. Madero, CDMX, 07160',
  'Civil',
  NULL,
  NULL,
  NULL,
  '0',
  '0',
  NULL,
  '0',
  'No',
  'No',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  NULL,
  NULL,
  '0',
  '0',
  'felipe.mrqzmel@gmail.com',
  'fmarquezm@aifa.aero',
  '0',
  '2027-08-16',
  NULL,
  '0',
  '0',
  NULL,
  '0',
  '0',
  NULL,
  '0'
) ON CONFLICT ("No. Empleado") DO UPDATE SET
  "Nombre" = COALESCE(EXCLUDED."Nombre", public.agenda_2026."Nombre"),
  "Fecha de alta" = COALESCE(EXCLUDED."Fecha de alta", public.agenda_2026."Fecha de alta"),
  "Sueldo_Bruto" = COALESCE(EXCLUDED."Sueldo_Bruto", public.agenda_2026."Sueldo_Bruto"),
  "Plaza" = COALESCE(EXCLUDED."Plaza", public.agenda_2026."Plaza"),
  "Nivel" = COALESCE(EXCLUDED."Nivel", public.agenda_2026."Nivel"),
  "Dir. Orgánica" = COALESCE(EXCLUDED."Dir. Orgánica", public.agenda_2026."Dir. Orgánica"),
  "Subdir. Orgánica" = COALESCE(EXCLUDED."Subdir. Orgánica", public.agenda_2026."Subdir. Orgánica"),
  "Gerencia Orgánica" = COALESCE(EXCLUDED."Gerencia Orgánica", public.agenda_2026."Gerencia Orgánica"),
  "Coordinación Orgánica" = COALESCE(EXCLUDED."Coordinación Orgánica", public.agenda_2026."Coordinación Orgánica"),
  "Puesto" = COALESCE(EXCLUDED."Puesto", public.agenda_2026."Puesto"),
  "Personal Comisionado" = COALESCE(EXCLUDED."Personal Comisionado", public.agenda_2026."Personal Comisionado"),
  "Dirección Comisionado" = COALESCE(EXCLUDED."Dirección Comisionado", public.agenda_2026."Dirección Comisionado"),
  "Subdirección Comisionado" = COALESCE(EXCLUDED."Subdirección Comisionado", public.agenda_2026."Subdirección Comisionado"),
  "Gerencia Comisionado" = COALESCE(EXCLUDED."Gerencia Comisionado", public.agenda_2026."Gerencia Comisionado"),
  "Coordinación Comisionado" = COALESCE(EXCLUDED."Coordinación Comisionado", public.agenda_2026."Coordinación Comisionado"),
  "Comentarios" = COALESCE(EXCLUDED."Comentarios", public.agenda_2026."Comentarios"),
  "Amonestaciones" = COALESCE(EXCLUDED."Amonestaciones", public.agenda_2026."Amonestaciones"),
  "Rúbrica" = COALESCE(EXCLUDED."Rúbrica", public.agenda_2026."Rúbrica"),
  "Anexo ""A"" Turno especial" = COALESCE(EXCLUDED."Anexo ""A"" Turno especial", public.agenda_2026."Anexo ""A"" Turno especial"),
  "Anexo ""A"" Fecha de activación" = COALESCE(EXCLUDED."Anexo ""A"" Fecha de activación", public.agenda_2026."Anexo ""A"" Fecha de activación"),
  "Anexo ""B"" Riesgos" = COALESCE(EXCLUDED."Anexo ""B"" Riesgos", public.agenda_2026."Anexo ""B"" Riesgos"),
  "Anexo ""B"" Fecha de activación" = COALESCE(EXCLUDED."Anexo ""B"" Fecha de activación", public.agenda_2026."Anexo ""B"" Fecha de activación"),
  "Antigüedad" = COALESCE(EXCLUDED."Antigüedad", public.agenda_2026."Antigüedad"),
  "Días de vacaciones disponibles" = COALESCE(EXCLUDED."Días de vacaciones disponibles", public.agenda_2026."Días de vacaciones disponibles"),
  "Fecha de nacimiento" = COALESCE(EXCLUDED."Fecha de nacimiento", public.agenda_2026."Fecha de nacimiento"),
  "Sexo" = COALESCE(EXCLUDED."Sexo", public.agenda_2026."Sexo"),
  "CURP" = COALESCE(EXCLUDED."CURP", public.agenda_2026."CURP"),
  "RFC" = COALESCE(EXCLUDED."RFC", public.agenda_2026."RFC"),
  "NSS" = COALESCE(EXCLUDED."NSS", public.agenda_2026."NSS"),
  "Vigencia de INE" = COALESCE(EXCLUDED."Vigencia de INE", public.agenda_2026."Vigencia de INE"),
  "Fotografia de INE" = COALESCE(EXCLUDED."Fotografia de INE", public.agenda_2026."Fotografia de INE"),
  "No. telefónico" = COALESCE(EXCLUDED."No. telefónico", public.agenda_2026."No. telefónico"),
  "Domicilio (calle, colonia, municipio, estado y código postal)" = COALESCE(EXCLUDED."Domicilio (calle, colonia, municipio, estado y código postal)", public.agenda_2026."Domicilio (calle, colonia, municipio, estado y código postal)"),
  "Persona Civil o Militar" = COALESCE(EXCLUDED."Persona Civil o Militar", public.agenda_2026."Persona Civil o Militar"),
  "Grado Militar" = COALESCE(EXCLUDED."Grado Militar", public.agenda_2026."Grado Militar"),
  "Personal en activo o retirado" = COALESCE(EXCLUDED."Personal en activo o retirado", public.agenda_2026."Personal en activo o retirado"),
  "Matrícula Militar" = COALESCE(EXCLUDED."Matrícula Militar", public.agenda_2026."Matrícula Militar"),
  "Estado civil" = COALESCE(EXCLUDED."Estado civil", public.agenda_2026."Estado civil"),
  "Dependientes (hijos)" = COALESCE(EXCLUDED."Dependientes (hijos)", public.agenda_2026."Dependientes (hijos)"),
  "RUSP" = COALESCE(EXCLUDED."RUSP", public.agenda_2026."RUSP"),
  "Tipo de sangre" = COALESCE(EXCLUDED."Tipo de sangre", public.agenda_2026."Tipo de sangre"),
  "Alérgico a algún medicamento Si ó No (Especificar)" = COALESCE(EXCLUDED."Alérgico a algún medicamento Si ó No (Especificar)", public.agenda_2026."Alérgico a algún medicamento Si ó No (Especificar)"),
  "Alérgico a algún alimento. Si ó No (Especificar)" = COALESCE(EXCLUDED."Alérgico a algún alimento. Si ó No (Especificar)", public.agenda_2026."Alérgico a algún alimento. Si ó No (Especificar)"),
  "Contacto de emergencia 1 Nombre completo" = COALESCE(EXCLUDED."Contacto de emergencia 1 Nombre completo", public.agenda_2026."Contacto de emergencia 1 Nombre completo"),
  "Parentesco 1" = COALESCE(EXCLUDED."Parentesco 1", public.agenda_2026."Parentesco 1"),
  "Teléfono de emergencia 1" = COALESCE(EXCLUDED."Teléfono de emergencia 1", public.agenda_2026."Teléfono de emergencia 1"),
  "Contacto de emergencia 2 Nombre completo" = COALESCE(EXCLUDED."Contacto de emergencia 2 Nombre completo", public.agenda_2026."Contacto de emergencia 2 Nombre completo"),
  "Parentesco 2" = COALESCE(EXCLUDED."Parentesco 2", public.agenda_2026."Parentesco 2"),
  "Teléfono de emergencia 2" = COALESCE(EXCLUDED."Teléfono de emergencia 2", public.agenda_2026."Teléfono de emergencia 2"),
  "Nivel de estudio" = COALESCE(EXCLUDED."Nivel de estudio", public.agenda_2026."Nivel de estudio"),
  "Nombre de la Licenciatura y/o Maestria" = COALESCE(EXCLUDED."Nombre de la Licenciatura y/o Maestria", public.agenda_2026."Nombre de la Licenciatura y/o Maestria"),
  "Nombre de la Universidad" = COALESCE(EXCLUDED."Nombre de la Universidad", public.agenda_2026."Nombre de la Universidad"),
  "Año de Titulación" = COALESCE(EXCLUDED."Año de Titulación", public.agenda_2026."Año de Titulación"),
  "No. Cédula Profesional" = COALESCE(EXCLUDED."No. Cédula Profesional", public.agenda_2026."No. Cédula Profesional"),
  "Fotografía (vest. Formal)" = COALESCE(EXCLUDED."Fotografía (vest. Formal)", public.agenda_2026."Fotografía (vest. Formal)"),
  "Correo Personal" = COALESCE(EXCLUDED."Correo Personal", public.agenda_2026."Correo Personal"),
  "Correo Institucional" = COALESCE(EXCLUDED."Correo Institucional", public.agenda_2026."Correo Institucional"),
  "Extensión" = COALESCE(EXCLUDED."Extensión", public.agenda_2026."Extensión"),
  "Vigencia de la TIA" = COALESCE(EXCLUDED."Vigencia de la TIA", public.agenda_2026."Vigencia de la TIA"),
  "Fotografía de la TIA" = COALESCE(EXCLUDED."Fotografía de la TIA", public.agenda_2026."Fotografía de la TIA"),
  "Licencia de Manejo" = COALESCE(EXCLUDED."Licencia de Manejo", public.agenda_2026."Licencia de Manejo"),
  "Tipo de licencia" = COALESCE(EXCLUDED."Tipo de licencia", public.agenda_2026."Tipo de licencia"),
  "Licencia Vigencia" = COALESCE(EXCLUDED."Licencia Vigencia", public.agenda_2026."Licencia Vigencia"),
  "Fotografia de licencia" = COALESCE(EXCLUDED."Fotografia de licencia", public.agenda_2026."Fotografia de licencia"),
  "Edad" = COALESCE(EXCLUDED."Edad", public.agenda_2026."Edad"),
  "Cumpleaños" = COALESCE(EXCLUDED."Cumpleaños", public.agenda_2026."Cumpleaños"),
  "Doc. Para ingreso" = COALESCE(EXCLUDED."Doc. Para ingreso", public.agenda_2026."Doc. Para ingreso");

-- [459] 986 | Juan Pablo Cervantes Torres
INSERT INTO public.agenda_2026 (
  "No. Empleado",
  "Nombre",
  "Fecha de alta",
  "Sueldo_Bruto",
  "Plaza",
  "Nivel",
  "Dir. Orgánica",
  "Subdir. Orgánica",
  "Gerencia Orgánica",
  "Coordinación Orgánica",
  "Puesto",
  "Personal Comisionado",
  "Dirección Comisionado",
  "Subdirección Comisionado",
  "Gerencia Comisionado",
  "Coordinación Comisionado",
  "Comentarios",
  "Amonestaciones",
  "Rúbrica",
  "Anexo ""A"" Turno especial",
  "Anexo ""A"" Fecha de activación",
  "Anexo ""B"" Riesgos",
  "Anexo ""B"" Fecha de activación",
  "Antigüedad",
  "Días de vacaciones disponibles",
  "Fecha de nacimiento",
  "Sexo",
  "CURP",
  "RFC",
  "NSS",
  "Vigencia de INE",
  "Fotografia de INE",
  "No. telefónico",
  "Domicilio (calle, colonia, municipio, estado y código postal)",
  "Persona Civil o Militar",
  "Grado Militar",
  "Personal en activo o retirado",
  "Matrícula Militar",
  "Estado civil",
  "Dependientes (hijos)",
  "RUSP",
  "Tipo de sangre",
  "Alérgico a algún medicamento Si ó No (Especificar)",
  "Alérgico a algún alimento. Si ó No (Especificar)",
  "Contacto de emergencia 1 Nombre completo",
  "Parentesco 1",
  "Teléfono de emergencia 1",
  "Contacto de emergencia 2 Nombre completo",
  "Parentesco 2",
  "Teléfono de emergencia 2",
  "Nivel de estudio",
  "Nombre de la Licenciatura y/o Maestria",
  "Nombre de la Universidad",
  "Año de Titulación",
  "No. Cédula Profesional",
  "Fotografía (vest. Formal)",
  "Correo Personal",
  "Correo Institucional",
  "Extensión",
  "Vigencia de la TIA",
  "Fotografía de la TIA",
  "Licencia de Manejo",
  "Tipo de licencia",
  "Licencia Vigencia",
  "Fotografia de licencia",
  "Edad",
  "Cumpleaños",
  "Doc. Para ingreso"
) VALUES (
  '986',
  'Juan Pablo Cervantes Torres',
  '2022-10-13',
  NULL,
  '469',
  'N5',
  'Dirección Comercial y de Servicios',
  NULL,
  'Gerencia de Servicios  Comerciales',
  NULL,
  'Gestor de Contratos',
  '1',
  'Dirección de Operación',
  'Subdirección de Ingeniería',
  'Gerencia de Operaciones de Instalaciones Hidráulicas',
  '0',
  '1- Comisión laboral AIFA-DPE-SSC-GED-0911-2026, a partir del 23 Abr. 2026 en la Gerencia de Operaciones de  Instalaciones Hidráulicas.',
  '0',
  'JPCT',
  NULL,
  NULL,
  NULL,
  NULL,
  '0',
  '0',
  '1999-01-30',
  'Maculino',
  'CETJ999139HMCRRN04',
  'CETJ999139BF8',
  '8149997564',
  '2036',
  NULL,
  '55 5501 1236',
  'Callejon del Castillo, Col. Del Castillo, No. 8, Tecamac Edomex, CP. 55740',
  'Civil',
  NULL,
  NULL,
  NULL,
  'Soltero',
  '0',
  NULL,
  'O+',
  'No',
  'Nuez',
  'María Torres Contreras',
  'Madre',
  '55 5106 1646',
  'Juan Carlos Cervantes Rodríguez',
  'Padre',
  '55 5139 4334',
  'Superior',
  'Ingeniería Industrial',
  'Unidad Profesional Interdisciplinaria de Ingeniería y Ciencias Sociales y Administrativas (UPIICSA-IPN)',
  'En trámite',
  '0',
  NULL,
  'torrespablo1d.99@gmail.com',
  'jcervantest@aifa.aero',
  '0',
  '2028-05-21',
  NULL,
  'Si',
  'A',
  '2027-11-26',
  NULL,
  '27',
  NULL,
  '0'
) ON CONFLICT ("No. Empleado") DO UPDATE SET
  "Nombre" = COALESCE(EXCLUDED."Nombre", public.agenda_2026."Nombre"),
  "Fecha de alta" = COALESCE(EXCLUDED."Fecha de alta", public.agenda_2026."Fecha de alta"),
  "Sueldo_Bruto" = COALESCE(EXCLUDED."Sueldo_Bruto", public.agenda_2026."Sueldo_Bruto"),
  "Plaza" = COALESCE(EXCLUDED."Plaza", public.agenda_2026."Plaza"),
  "Nivel" = COALESCE(EXCLUDED."Nivel", public.agenda_2026."Nivel"),
  "Dir. Orgánica" = COALESCE(EXCLUDED."Dir. Orgánica", public.agenda_2026."Dir. Orgánica"),
  "Subdir. Orgánica" = COALESCE(EXCLUDED."Subdir. Orgánica", public.agenda_2026."Subdir. Orgánica"),
  "Gerencia Orgánica" = COALESCE(EXCLUDED."Gerencia Orgánica", public.agenda_2026."Gerencia Orgánica"),
  "Coordinación Orgánica" = COALESCE(EXCLUDED."Coordinación Orgánica", public.agenda_2026."Coordinación Orgánica"),
  "Puesto" = COALESCE(EXCLUDED."Puesto", public.agenda_2026."Puesto"),
  "Personal Comisionado" = COALESCE(EXCLUDED."Personal Comisionado", public.agenda_2026."Personal Comisionado"),
  "Dirección Comisionado" = COALESCE(EXCLUDED."Dirección Comisionado", public.agenda_2026."Dirección Comisionado"),
  "Subdirección Comisionado" = COALESCE(EXCLUDED."Subdirección Comisionado", public.agenda_2026."Subdirección Comisionado"),
  "Gerencia Comisionado" = COALESCE(EXCLUDED."Gerencia Comisionado", public.agenda_2026."Gerencia Comisionado"),
  "Coordinación Comisionado" = COALESCE(EXCLUDED."Coordinación Comisionado", public.agenda_2026."Coordinación Comisionado"),
  "Comentarios" = COALESCE(EXCLUDED."Comentarios", public.agenda_2026."Comentarios"),
  "Amonestaciones" = COALESCE(EXCLUDED."Amonestaciones", public.agenda_2026."Amonestaciones"),
  "Rúbrica" = COALESCE(EXCLUDED."Rúbrica", public.agenda_2026."Rúbrica"),
  "Anexo ""A"" Turno especial" = COALESCE(EXCLUDED."Anexo ""A"" Turno especial", public.agenda_2026."Anexo ""A"" Turno especial"),
  "Anexo ""A"" Fecha de activación" = COALESCE(EXCLUDED."Anexo ""A"" Fecha de activación", public.agenda_2026."Anexo ""A"" Fecha de activación"),
  "Anexo ""B"" Riesgos" = COALESCE(EXCLUDED."Anexo ""B"" Riesgos", public.agenda_2026."Anexo ""B"" Riesgos"),
  "Anexo ""B"" Fecha de activación" = COALESCE(EXCLUDED."Anexo ""B"" Fecha de activación", public.agenda_2026."Anexo ""B"" Fecha de activación"),
  "Antigüedad" = COALESCE(EXCLUDED."Antigüedad", public.agenda_2026."Antigüedad"),
  "Días de vacaciones disponibles" = COALESCE(EXCLUDED."Días de vacaciones disponibles", public.agenda_2026."Días de vacaciones disponibles"),
  "Fecha de nacimiento" = COALESCE(EXCLUDED."Fecha de nacimiento", public.agenda_2026."Fecha de nacimiento"),
  "Sexo" = COALESCE(EXCLUDED."Sexo", public.agenda_2026."Sexo"),
  "CURP" = COALESCE(EXCLUDED."CURP", public.agenda_2026."CURP"),
  "RFC" = COALESCE(EXCLUDED."RFC", public.agenda_2026."RFC"),
  "NSS" = COALESCE(EXCLUDED."NSS", public.agenda_2026."NSS"),
  "Vigencia de INE" = COALESCE(EXCLUDED."Vigencia de INE", public.agenda_2026."Vigencia de INE"),
  "Fotografia de INE" = COALESCE(EXCLUDED."Fotografia de INE", public.agenda_2026."Fotografia de INE"),
  "No. telefónico" = COALESCE(EXCLUDED."No. telefónico", public.agenda_2026."No. telefónico"),
  "Domicilio (calle, colonia, municipio, estado y código postal)" = COALESCE(EXCLUDED."Domicilio (calle, colonia, municipio, estado y código postal)", public.agenda_2026."Domicilio (calle, colonia, municipio, estado y código postal)"),
  "Persona Civil o Militar" = COALESCE(EXCLUDED."Persona Civil o Militar", public.agenda_2026."Persona Civil o Militar"),
  "Grado Militar" = COALESCE(EXCLUDED."Grado Militar", public.agenda_2026."Grado Militar"),
  "Personal en activo o retirado" = COALESCE(EXCLUDED."Personal en activo o retirado", public.agenda_2026."Personal en activo o retirado"),
  "Matrícula Militar" = COALESCE(EXCLUDED."Matrícula Militar", public.agenda_2026."Matrícula Militar"),
  "Estado civil" = COALESCE(EXCLUDED."Estado civil", public.agenda_2026."Estado civil"),
  "Dependientes (hijos)" = COALESCE(EXCLUDED."Dependientes (hijos)", public.agenda_2026."Dependientes (hijos)"),
  "RUSP" = COALESCE(EXCLUDED."RUSP", public.agenda_2026."RUSP"),
  "Tipo de sangre" = COALESCE(EXCLUDED."Tipo de sangre", public.agenda_2026."Tipo de sangre"),
  "Alérgico a algún medicamento Si ó No (Especificar)" = COALESCE(EXCLUDED."Alérgico a algún medicamento Si ó No (Especificar)", public.agenda_2026."Alérgico a algún medicamento Si ó No (Especificar)"),
  "Alérgico a algún alimento. Si ó No (Especificar)" = COALESCE(EXCLUDED."Alérgico a algún alimento. Si ó No (Especificar)", public.agenda_2026."Alérgico a algún alimento. Si ó No (Especificar)"),
  "Contacto de emergencia 1 Nombre completo" = COALESCE(EXCLUDED."Contacto de emergencia 1 Nombre completo", public.agenda_2026."Contacto de emergencia 1 Nombre completo"),
  "Parentesco 1" = COALESCE(EXCLUDED."Parentesco 1", public.agenda_2026."Parentesco 1"),
  "Teléfono de emergencia 1" = COALESCE(EXCLUDED."Teléfono de emergencia 1", public.agenda_2026."Teléfono de emergencia 1"),
  "Contacto de emergencia 2 Nombre completo" = COALESCE(EXCLUDED."Contacto de emergencia 2 Nombre completo", public.agenda_2026."Contacto de emergencia 2 Nombre completo"),
  "Parentesco 2" = COALESCE(EXCLUDED."Parentesco 2", public.agenda_2026."Parentesco 2"),
  "Teléfono de emergencia 2" = COALESCE(EXCLUDED."Teléfono de emergencia 2", public.agenda_2026."Teléfono de emergencia 2"),
  "Nivel de estudio" = COALESCE(EXCLUDED."Nivel de estudio", public.agenda_2026."Nivel de estudio"),
  "Nombre de la Licenciatura y/o Maestria" = COALESCE(EXCLUDED."Nombre de la Licenciatura y/o Maestria", public.agenda_2026."Nombre de la Licenciatura y/o Maestria"),
  "Nombre de la Universidad" = COALESCE(EXCLUDED."Nombre de la Universidad", public.agenda_2026."Nombre de la Universidad"),
  "Año de Titulación" = COALESCE(EXCLUDED."Año de Titulación", public.agenda_2026."Año de Titulación"),
  "No. Cédula Profesional" = COALESCE(EXCLUDED."No. Cédula Profesional", public.agenda_2026."No. Cédula Profesional"),
  "Fotografía (vest. Formal)" = COALESCE(EXCLUDED."Fotografía (vest. Formal)", public.agenda_2026."Fotografía (vest. Formal)"),
  "Correo Personal" = COALESCE(EXCLUDED."Correo Personal", public.agenda_2026."Correo Personal"),
  "Correo Institucional" = COALESCE(EXCLUDED."Correo Institucional", public.agenda_2026."Correo Institucional"),
  "Extensión" = COALESCE(EXCLUDED."Extensión", public.agenda_2026."Extensión"),
  "Vigencia de la TIA" = COALESCE(EXCLUDED."Vigencia de la TIA", public.agenda_2026."Vigencia de la TIA"),
  "Fotografía de la TIA" = COALESCE(EXCLUDED."Fotografía de la TIA", public.agenda_2026."Fotografía de la TIA"),
  "Licencia de Manejo" = COALESCE(EXCLUDED."Licencia de Manejo", public.agenda_2026."Licencia de Manejo"),
  "Tipo de licencia" = COALESCE(EXCLUDED."Tipo de licencia", public.agenda_2026."Tipo de licencia"),
  "Licencia Vigencia" = COALESCE(EXCLUDED."Licencia Vigencia", public.agenda_2026."Licencia Vigencia"),
  "Fotografia de licencia" = COALESCE(EXCLUDED."Fotografia de licencia", public.agenda_2026."Fotografia de licencia"),
  "Edad" = COALESCE(EXCLUDED."Edad", public.agenda_2026."Edad"),
  "Cumpleaños" = COALESCE(EXCLUDED."Cumpleaños", public.agenda_2026."Cumpleaños"),
  "Doc. Para ingreso" = COALESCE(EXCLUDED."Doc. Para ingreso", public.agenda_2026."Doc. Para ingreso");

COMMIT;
